### ISSUE TITLE
Constantly receiving hangups in the middle of my domain list when running httpx?

### ISSUE THREAD

**Issue by obheda12** [projectdiscovery/httpx#100]
I don't have this issue with httprobe, however, whenever I feed a list of domains to probe with httpx it always hangs, completes a portion, and then exits the program.

I love this tool however, the inconsistency in reading the entire domain list makes it unreliable for me. Any suggestions or reasoning behind this?

Command I've been running:

httpx -l domains.txt -threads 50 -title -status-code -no-color -follow-redirects -content-type

**Comment by bauthard** [comment]
@obheda12, for the same reason we have added `verbose` mode support that shows where the request getting failed. 

try `httpx -l domains.txt -verbose` also make sure you are on the latest version `v1.0.1`

**Comment by bauthard** [comment]
@obheda12 any update on this?

**Comment by bauthard** [comment]
Closing due to lack of information
