### ISSUE TITLE
Issue with urls containing commas

### ISSUE THREAD

**Issue by molitona** [projectdiscovery/httpx#1002]
### Discussed in https://github.com/projectdiscovery/httpx/discussions/1001

<div type='discussions-op-text'>

<sup>Originally posted by **molitona** February 25, 2023</sup>
hi comma in url broke httpx, if https://xx.xx?perms=X,Y,Z is used httpx will think X,Y,Z are paths but they're part of url as options to param perms.</div>

**Comment by ehsandeep** [comment]
This can be fixed by removing comma-separated input support for `-u` option, i.e single input or new line delimited file input `-list` for multiple host input.

**Comment by molitona** [comment]
> This can be fixed by removing comma-separated input support for `-u` option, i.e single input or new line delimited file input `-list` for multiple host input.

will the fix take a while ?

**Comment by Mzack9999** [comment]
@molitona a fix has been implemented at https://github.com/projectdiscovery/httpx/pull/1009 only for URLs from file as via stdin/cli it might introduce breaking changes.
