### ISSUE TITLE
[bug] csp domain extract doesn't work correctly when status code is 302

### ISSUE THREAD

**Issue by dmatrixx** [projectdiscovery/httpx#101]
I was trying this feature , it misses csp domain extraction when the status code is 302 not even while using -follow-redirects flag

For Example 

Try these following commands

echo admanagerplus.yahoo.com | httpx -status-code -title -csp-probe  
echo admanagerplus.yahoo.com | httpx -status-code -title -csp-probe -follow-redirects

but the 302 response has csp domains in them.

![image](https://user-images.githubusercontent.com/44583139/93021796-64384c00-f602-11ea-956b-9e997c9a798d.png)

**Comment by Mzack9999** [comment]
@dmatrixx Good catch! It seems like that the header used here is `Content-Security-Policy-Report-Only`, whereas we are currently using `Content-Security-Policy` to extract additional domains. I'm going to add also this to the list. Thanks for opening the issue!

**Comment by dmatrixx** [comment]
Awesome !! that was fast.

Can you also update github.com/projectdiscovery/httpx/common/slice

![image](https://user-images.githubusercontent.com/44583139/93034645-63320980-f658-11ea-8750-3b6c120394ae.png)

![image](https://user-images.githubusercontent.com/44583139/93034617-472e6800-f658-11ea-8a38-235f727adcb7.png)

**Comment by Mzack9999** [comment]
@dmatrixx the code is already in the pull request at https://github.com/projectdiscovery/httpx/pull/104/files#diff-58b1cd2994940895a3cec5606eb88a79R13. It seems like that your local branch somehow didn't checkout all the code. I think this should be solved automatically once the corresponding PR is merged in master.

**Comment by dmatrixx** [comment]
Very well !! many thanks for the awesome tool . :)

**Comment by bauthard** [comment]
@dmatrixx this is now fixed and merged in master code.
