### ISSUE TITLE
[FTL] json: cannot unmarshal string into Go value of type []asnmap.Response

### ISSUE THREAD

**Issue by leveryd** [projectdiscovery/httpx#1017]
```
echo www.baidu.com:80 | httpx -sc -cl -ct -location -lc -wc -rt -title -server -td -ip -cname -asn -cdn -probe -json -ec -fc 0
```
httpx v1.2.7 will fail

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/1846319/222914212-68306c5e-54fc-4a68-8ecd-7ae80755eec7.png">

**Comment by ehsandeep** [comment]
@leveryd duplicate of https://github.com/projectdiscovery/httpx/issues/989 and fixed in dev branch!
