### ISSUE TITLE
Dependency Issues with httpx / asnmap / subfinder latest release versions as go modules.

### ISSUE THREAD

**Issue by mr-pmillz** [projectdiscovery/httpx#1025]
### httpx versions:
httpx v1.2.7 and/or  v1.2.8-0.20230305080631-c6998f494ebb

### subfinder version
v2.5.6

### asnmap version
v1.0.1 or v1.0.0

### Current Behavior:
Cannot use the latest release version of httpx natively as a go module due to asnmap method conflicts with subfinder and httpx.

Go build output
```shell
# github.com/projectdiscovery/httpx/runner
../../go/pkg/mod/github.com/projectdiscovery/httpx@v1.2.7/runner/runner.go:80:22: undefined: asn.ASNClient
../../go/pkg/mod/github.com/projectdiscovery/httpx@v1.2.7/runner/runner.go:87:18: undefined: asn.New
../../go/pkg/mod/github.com/projectdiscovery/httpx@v1.2.7/runner/runner.go:493:14: undefined: asn.New
../../go/pkg/mod/github.com/projectdiscovery/httpx@v1.2.7/runner/runner.go:1373:14: multiple-value asnmap.NewClient() (value of type (*asnmap.Client, error)) in single-value context
../../go/pkg/mod/github.com/projectdiscovery/httpx@v1.2.7/runner/runner.go:1373:41: invalid operation: cannot call non-function asnmap.IP (constant 2 of type asnmap.InputType)
../../go/pkg/mod/github.com/projectdiscovery/httpx@v1.2.7/runner/runner.go:1376:25: multiple-value asnmap.GetCIDR(results) (value of type ([]*net.IPNet, error)) in single-value context
```

### Expected Behavior:
should be able to use both packages natively in go via go modules without build errors or dependency conflicts.

### Steps To Reproduce:
using the following modules in go.mod causes a build failure.
```go
github.com/projectdiscovery/asnmap v1.0.1
github.com/projectdiscovery/httpx v1.2.7
github.com/projectdiscovery/subfinder/v2 v2.5.6
```

Using these versions works together:
```go
github.com/projectdiscovery/asnmap v0.0.1
github.com/projectdiscovery/httpx v1.2.5
github.com/projectdiscovery/subfinder/v2 v2.5.5
```

### Anything else:
Please advise and/or look into resolving these dependency conflicts for the next stable release versions. Much appreciated as always and keep up the awesome work! 💯

**Comment by ehsandeep** [comment]
@mr-pmillz this is fixed in dev branch, you can point httpx to `dev` for now, soon we will be pushing new release for httpx.

**Comment by mr-pmillz** [comment]
Oh nice! Right on, thanks! @ehsandeep
