### ISSUE TITLE
output flag -o

### ISSUE THREAD

**Issue by Filipeasl** [projectdiscovery/httpx#1031]
Is this file output normal?

Command:
<img width="764" alt="image" src="https://user-images.githubusercontent.com/74147258/224382135-4a6f7624-11c6-4485-9c27-b19ff037fde2.png">
File:
<img width="553" alt="image" src="https://user-images.githubusercontent.com/74147258/224383030-fc32ee0a-e985-44d9-aa96-1b92aedb5819.png">

**Comment by ehsandeep** [comment]
Use `-nc` flag to avoid this in the output file.
