### ISSUE TITLE
Go Install 

### ISSUE THREAD

**Issue by slossy88** [projectdiscovery/httpx#1054]
> go version
go version go1.19.6 linux/amd64

error codes
go/pkg/mod/go.etcd.io/bbolt@v1.3.7/allocate_test.go:1:1: expected 'package', found 'EOF'
go/pkg/mod/gopkg.in/djherbis/times.v1@v1.3.0/bench_test.go:1:1: expected 'package', found 'EOF'
go/pkg/mod/gopkg.in/ini.v1@v1.67.0/bench_test.go:1:1: expected 'package', found 'EOF'
go/pkg/mod/gopkg.in/yaml.v3@v3.0.1/apic.go:1:1: expected 'package', found 'EOF'

i don't know what is happening

**Comment by Mzack9999** [comment]
@slossy88 We need all the information specified in the bug submission [template](https://github.com/projectdiscovery/httpx/issues/new?assignees=&labels=Type%3A+Bug&template=issue-report.md) to be able to investigate the issue. In particular, please provide the full command used to reproduce the problem.
At first sight, it seems like a temporary network failure. Are you able to reproduce it consistently?
