### ISSUE TITLE
ASGI lifespan state

### ISSUE THREAD

**Issue by GuillaumeDesforges** [projectdiscovery/httpx#1058]
### Please describe your feature request:

Support ASGI's lifespan state: https://asgi.readthedocs.io/en/latest/specs/lifespan.html

> ### Scope
> ...
> `state` Optional(dict[Unicode string, Any]) – An empty namespace where the application can persist state to be used when handling subsequent requests. Optional; if missing the server does not support this feature.

### Describe the use case of this feature:

Lifespan state allows to share state between requests, such as a ML model in GPU or a connection to a database.

It is supported by other important ASGI servers such as uvicorn (ref: https://github.com/encode/uvicorn/pull/1818)

However `httpx` is the recommended library to test FastAPI apps (`AsyncClient`) so we can't test such applications.

**Comment by AaronChen0** [comment]
This is a Go repository. What you want to request is this one, https://github.com/encode/httpx/ .

**Comment by GuillaumeDesforges** [comment]
Oops. My bad! Sorry about that.
