### ISSUE TITLE
expose custom config file input support (goflags)

### ISSUE THREAD

**Issue by hakrishi** [projectdiscovery/httpx#1102]
Hi there,

I'd like to be able to use a configuration file with httpx scans. The exact same implementation as with Nuclei, where I can add multiple flags to a .yaml file and use the -config argument with Nuclei to add the configuration file. 

Describe the use case of this feature:
This would be used to organise all flags and start scans a lot quicker instead of listing out 5-10 flags in a single httpx scan

![image](https://user-images.githubusercontent.com/59293085/232744143-4bc81d5e-1b2c-404b-8c3a-42a38f5bb1a5.png)

Flags to add:

```console
   -config string  path to the httpx configuration file (default $HOME/.config/httpx/config.yaml)
```

Many thanks,

Rishi

**Comment by ehsandeep** [comment]
@hakrishi custom input support will be added, for the time being, you can still update the existing default config file `$HOME/.config/httpx/config.yaml` to set default cli flags.

**Comment by hakrishi** [comment]
thanks for adding this! 💖 @dogancanbakir @ehsandeep
