### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Deepaklahari** [projectdiscovery/httpx#111]
While using - cat x.txt | httpx         
Getting error -   Segmentation fault (core dumped)

**Comment by bauthard** [comment]
Hey @Deepaklahari, 

Before reviewing this, please include the required information. 

1. The version of httpx you are using. 

```
httpx -version
```

2. Paste the error details in this issue.

**Comment by bauthard** [comment]
Closing this due to lack of information
