### ISSUE TITLE
Suggestions on HTTPS

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/httpx#1122]
@ehsandeep 
# Suggestions on HTTPS

It is recommended to call tlsx to obtain the ssl/tls structured information before accessing https, and output it. At the same time, it is recommended to determine whether it is verifiable ssl/tls. If it is not verifiable, the https access should be accompanied by ignoring the validation

**Comment by adam-pawluczuk** [comment]
We also need this feature. It important to verify e.g. TLS versions about to being used prior to making an actual request.

How I can imagine this happening is e.g. adding a respective method to `BaseClient`:

```
class BaseClient:

    # ...

    def ssl_context(self) -> SSLContext:
        return self._transport._pool._ssl_context
```

Or something to that extent.

**Comment by adam-pawluczuk** [comment]
@Mzack9999 Indeed wrong project :) Sorry about that

**Comment by hktalent** [comment]
thanks
