### ISSUE TITLE
Issue using -port (tried "auqatone -ports xlarge" port list)

### ISSUE THREAD

**Issue by its0x08** [projectdiscovery/httpx#114]
Hello 
I was trying a large port list for the -port argument and noticed 2 misfunctions.

1. It prints result for the same host:port multiple times when using -follow-host-redirects
2. Doesnt detect if the port is ssl or plain text therefore it prints results like http://example.com:443 with a 400 error and a title like this "[400 The plain HTTP request was sent to HTTPS port]"

I suggest it saves all previous results in an array and check for duplicates before printing a new one if -x is not used and also check if the port is ssl to not use http:// to print false positives.
Thanks!

**Comment by bauthard** [comment]
Hi @its0x08, 

Can you please post an example for both the case you listed above?

**Comment by its0x08** [comment]
This week I wont be able to screenshot examples but I'll try to explain!
1. When you use -follow-host-redirects for example 8.8.8.8 redirects to google.com and also 8.8.8.8:8080 may redirect to google.com and httpx prints 2 different lines for the same redirected site, so in my case it printed 100 times the same line. :/
2. I test a big list from top-http-ports and to not go nmap then format it and pipe to httpx, would be awesome if httpx detected if a port is serving http or httpx to not give error 400 for half of the ports that arent http..
for example I tried a list of 100 hosts and for each port it printed 2 lines.. http://8.8.8.8:8443/ - error  and https://8.8.8.8:8443/ - success.
I assumed it automatically checked if it was servin https to report only https and not also the http.

**Comment by bauthard** [comment]
Hi @its0x08, 

> It prints result for the same host:port multiple times when using -follow-host-redirects

As you used `-follow-host-redirects` flag, it will print the end result after following each redirect, it doesn't matter if the results are the same or not, even the results are the same, it's going to print as it is, and this is expected behavior, you can always do `sort -u` on the output locally or using `pipe, | sort -u` on the output of httpx. 

> Doesnt detect if the port is ssl or plain text therefore it prints results like http://example.com:443 with a 400 error and a title like this "[400 The plain HTTP request was sent to HTTPS port]"

We have updated the code here https://github.com/projectdiscovery/httpx/pull/129, now you can define which protocol you want to connect along with the port list.

```
cat list.txt | ./httpx -ports https:443, https:8443, http:80
```

**Comment by its0x08** [comment]
Hmm
Thank you for updating the project but anyway nothing got solved as I still have to use an alternative tool to know if 8443 for ex. is running default ssl protocol or ssh/ftp/smtp/telnet/http.. so to know that I will have to port scan before the target:port and based on the information I'll have to build for every target a custom proto:port list. This doesnt make the life easier by any mean.
And about the sort -u method... not a bad one but totally useless because I'll have to wait for everything to finish (last time it was a week or so) to submit found results to the next stage of discovery. 
Thank you again for your time !!
