### ISSUE TITLE
square brackets no longer work

### ISSUE THREAD

**Issue by sathio** [projectdiscovery/httpx#1141]
A GET request such as `/?arr[]=1&arr[]=2` is perfectly legal and it means that you are trying to send an array of values to the endpoint. 

unluckily after 0.23.3 it stopped working because urls are sent as `/?arr%5B%5D=1&arr%5B%5D=2`

**Comment by ehsandeep** [comment]
@sathio looks like it's about - https://github.com/encode/httpx
