### ISSUE TITLE
Proxychains bypassed by httpx

### ISSUE THREAD

**Issue by ocervell** [projectdiscovery/httpx#1143]
### httpx version:
v1.2.9

### Current Behavior:
Running proxychains on httpx does not work. `httpx` seems to bypass the proxychains somehow.

### Expected Behavior:
I would expect `proxychains httpx` to work as intended.

### Steps To Reproduce:
`proxychains httpx -u ifconfig.me/ip -irr -debug-resp` gives the real IP, not the proxychains proxy IP.

**Comment by jimen0** [comment]
Hi @ocervell - The way [proxychains](https://github.com/rofl0r/proxychains-ng) works is by hooking some calls.

```
  The way it works is basically a HACK; so it is possible that it doesn't
  work with your program, especially when it's a script, or starts
  numerous processes like background daemons or uses dlopen() to load
  "modules" (bug in glibc dynlinker).
  It should work with simple compiled (C/C++) dynamically linked programs
  though.
```

Go is (generally) statically linked and proxychains won't work with it.

cc @ehsandeep

**Comment by ocervell** [comment]
Sounds good thanks for this explanation I had no idea how it worked ;)

**Comment by Mzack9999** [comment]
I'm closing the issue as it seems like things are working as expected
