### ISSUE TITLE
Problem while extracting URLs title (regex)

### ISSUE THREAD

**Issue by flacostec** [projectdiscovery/httpx#115]
Hello,

There's some website that are using specific CSS selector so the regex doesn't match the title HTML tag adequately. I'd suggest changing it to something like that 
```
	var re = regexp.MustCompile(`(?im)<\s*title.*>(.*?)<\s*/\s*title>`)
```
Instead of being 
```
	var re = regexp.MustCompile(`(?im)<\s*title *>(.*?)<\s*/\s*title>`)
```

That way, the title will be extracted.

**Comment by bauthard** [comment]
Thank you @flacostec, surely we can update this, do you have an example to share where the current one is not picking the title?

**Comment by flacostec** [comment]
You can try the following URL : [https://www.ired.team/offensive-security/credential-access-and-credential-dumping/dumping-lsass-passwords-without-mimikatz-minidumpwritedump-av-signature-bypass](https://www.ired.team/offensive-security/credential-access-and-credential-dumping/dumping-lsass-passwords-without-mimikatz-minidumpwritedump-av-signature-bypass)

```
<title data-react-helmet="true">Dumping LSASS without Mimikatz with MiniDumpWriteDump == Reduced Chances of Getting Flagged by AVs - Red Teaming Experiments</title>
```

**Comment by bauthard** [comment]
Thank you for sharing more info @flacostec, this has been added here https://github.com/projectdiscovery/httpx/pull/120
