### ISSUE TITLE
Add golangci-lint to the current GitHub workflow

### ISSUE THREAD

**Issue by vzamanillo** [projectdiscovery/httpx#117]
`golangci-lint-action` It's the official `GitHub` action for `golangci-lint` from it's authors. The action runs `golangci-lint` and reports issues from linters.
`
golangci-lint` is a fast Go linters runner. It runs linters in parallel, uses caching, supports yaml config, has integrations with all major IDE and has dozens of linters included.

Including this action into the workflow would increment the project code quality and could prevent possible future leaks and/or failures setting a minimum of checks and rules, I think it could be very favorable.

**Comment by bauthard** [comment]
Added here https://github.com/projectdiscovery/httpx/pull/121
