### ISSUE TITLE
Screenshots don't work in docker

### ISSUE THREAD

**Issue by XTeam-Wing** [projectdiscovery/httpx#1200]
### httpx version:
1.3.1

### Current Behavior:
can't fetch screenshot,
[WRN] Could not take screenshot 'https://google.com': write tcp 127.0.0.1:42556->127.0.0.1:36439: use of closed network connection

### Expected Behavior:
get screeshot data

### Steps To Reproduce:
run in docker Ubuntu 18.04.6 LTS 
```
./httpx -u google.com -ss -system-chrome -json -fr -debug  -v
```
<img width="857" alt="image" src="https://github.com/projectdiscovery/httpx/assets/25416365/65a7f015-d143-411a-a02a-040fcf11d4c5">

```
root@6ada48fa9aaf:/tmp# cat screenshot_path":"/tmp/output/screenshot/google.com/baea954b95731c68ae6e45bd1e252eb4560cdc45.png
cat: 'screenshot_path:/tmp/output/screenshot/google.com/baea954b95731c68ae6e45bd1e252eb4560cdc45.png': No such file or directory
root@6ada48fa9aaf:/tmp#
```

**Comment by freeAhao** [comment]
Using auto download chrome:
```
[FTL] Could not create runner: fork/exec /root/.cache/rod/browser/chromium-1131003/chrome: no such file or directory
bash-5.1# ls /root/.cache/rod/browser/chromium-1131003/chrome
/root/.cache/rod/browser/chromium-1131003/chrome

bash-5.1# ls -alh /root/.cache/rod/browser/chromium-1131003/chrome
-rwxr-xr-x 1 root root 342M Jun 20 06:38 /root/.cache/rod/browser/chromium-1131003/chrome
```

System-chrome:
using system /usr/bin/chromium-browser works with no error  but nothing happened, and a empty index_screenshot.txt created

Version:
[INF] Current httpx version v1.3.2 (latest)

when using --srd option, we need create 'response' and 'screenshot' folder manually

**Comment by dogancanbakir** [comment]
I tried with and without the `-system-chrome` flag but couldn't reproduce the issue and was unsuccessful. Here are the details:

```console
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```

```console
$ tree output/
output/
├── response
│   ├── google.com
│   │   └── 3565ad633884dfb24d1b7de7cb912dc454f1face.txt
│   └── index.txt
└── screenshot
    ├── google.com
    │   └── 3565ad633884dfb24d1b7de7cb912dc454f1face.png
    ├── index_screenshot.txt
    └── screenshot.html

4 directories, 5 files
```

```console
 $ cat output/screenshot/index_screenshot.txt 
/workspaces/httpx/cmd/httpx/output/screenshot/google.com/3565ad633884dfb24d1b7de7cb912dc454f1face.png https://google.com (200 OK)
```

This is how I set up the environment, step by step:
Setup docker env for `Ubuntu 18.04.6 LTS`
Install Golang
Install `chromium-browser` for the `-system-chrome` flag  -OR run it without the `-system-chrome` flag

I tested it using the newest version of `httpx` This is the only variation in our setups. I want to assist further, but I require your help. Would you be able to test it using the latest version as well? Additionally, please provide details about your environment setup.

@XTeam-Wing @freeAhao

**Comment by dogancanbakir** [comment]
I am closing this for now. If you are still experiencing the same issue, please feel free to reopen and provide additional details.
