### ISSUE TITLE
Add reporting to elasticsearch

### ISSUE THREAD

**Issue by ResistanceIsUseless** [projectdiscovery/httpx#1207]
Please add an option to send results of different levels to elasticsearch. Similar to nuclei reporting.

It would be nice to choose from two levels:
- just the found open ports
- more detailed reporting with the full response

**Comment by acidvegas** [comment]
They have JSON output, which you can use logstash or various other things to monitor a directory to upload. Problem is their json output is entirely uncustomizable.

Come on irc.supernets.org if you wanna chat about httpx/elasticsearch, I have a working pipeline I can share with you.

**Comment by Mzack9999** [comment]
Closing as relevant json fields can be extracted with jq. We will try to work on a new utility to manipulate and export data in a generic way, so that it can work cross-tools. Feel free to reopen if necessary

**Comment by acidvegas** [comment]
> Please add an option to send results of different levels to elasticsearch. Similar to nuclei reporting.
> 
> It would be nice to choose from two levels:
> 
>     * just the found open ports
> 
>     * more detailed reporting with the full response

https://github.com/acidvegas/eris/
