### ISSUE TITLE
Basic HTML Index file to visualize created screenshot 

### ISSUE THREAD

**Issue by saurinn** [projectdiscovery/httpx#1208]
### Feature request:
Add a folder with all the screenshots there so it should be easier to skim through them. 

### Use case of this feature:
It is really tedious to go back to another folder so we can see the next screenshot, that's why having a folder or at least a HTML with all the resulting images, sort of like [EyeWitness](https://github.com/FortyNorthSecurity/EyeWitness) does, would be so useful in terms of productivity.

**Comment by MetzinAround** [comment]
Thanks for the request! I think part of screenshot capability is that you can designate a folder where they go.  

<img width="874" alt="Screenshot -0605 at 08 15 @2x" src="https://github.com/projectdiscovery/httpx/assets/65838556/1059c67b-d8fb-4c2f-8440-526282062881">

**Comment by saurinn** [comment]
@ehsandeep exactly! Because it doesn't matter where I designate the custom folder with the -srd flag, they are going to be divided on their related dns name key folder. So, that HTML file with all the pictures indexed will be so useful to have.
