### ISSUE TITLE
Issue with file read input flag

### ISSUE THREAD

**Issue by eur0pa** [projectdiscovery/httpx#123]
Reproduce with:

```sh
$ echo -e "example.com\ngoogle.com" > x
$ httpx -l x
```

Expected:

```
http://example.com
https://exampe.com
http://google.com
https://google.com
```

Outcome: none

Obtain expected outcome with:

```sh
$ httpx < x
```

**Comment by bauthard** [comment]
Thank you for creating this issue @eur0pa, this is reproducible on Linux, working as expected on Mac, for the time being, we suggest to use the released (stable) version.

**Comment by bauthard** [comment]
@eur0pa this is now fixed in master code as well.
