### ISSUE TITLE
Add page similarity comparison function

### ISSUE THREAD

**Issue by a3vilc0de** [projectdiscovery/httpx#1251]
### Discussed in https://github.com/projectdiscovery/httpx/discussions/1250

<div type='discussions-op-text'>

<sup>Originally posted by **a3vilc0de** June 26, 2023</sup>
Add page similarity comparison function to improve the accuracy of path scanning and reduce false positives，and -fs, -filter-string String filter responses with specified strings, add support for importing string files, in order to support a large number of target scans, need to filter multiple strings. Thanks</div>
```[tasklist]
### Tasks
```

**Comment by Mzack9999** [comment]
@a3vilc0de I'm not sure if it's what you are looking for, but there are already similarity hashes (simhash, perceptual hash and visual clustering if you use screenshot functionality). I'm creating a follow up issue to turn single value CLI flags into multi-value at https://github.com/projectdiscovery/httpx/issues/1749

**Comment by Mzack9999** [comment]
Closing this issue as not actionable since there are already similarity hashes. Relevant changes are tracked at https://github.com/projectdiscovery/httpx/issues/1749
