### ISSUE TITLE
Just output jpg of screenshot, nothing else

### ISSUE THREAD

**Issue by Viss** [projectdiscovery/httpx#1260]
Hi!

It would be really helpful to be able to aim httpx at a website, and have it output just a jpg, nothing else, into a directory. Part of my workflow involves screenshots and having to wade through a directory structure to fish out jpegs with long, unique filenames makes it harder to then do post-processing on those images, or group together images with other findings based on apex domain name. 

if httpx can already do this, thats awesome, I just haven't figured it out yet.

**Comment by MetzinAround** [comment]
hi @Viss! So you want a jpg screenshot while httpx works. You want that output into a specified directory and you want control over the jpg name, is that correct?

**Comment by Viss** [comment]
yep, exactly! 

something like this:

httpx -ss -o hax.lol.jpg -u https://hax.lol

it makes processing images afterward a lot easier!

**Comment by Mzack9999** [comment]
You can obtain this result with nuclei:

```console
echo https://hax.lol/ | nuclei -id screenshot -headless
```
