### ISSUE TITLE
Empty A records when port is used in as input or as ports option

### ISSUE THREAD

**Issue by Miracles666** [projectdiscovery/httpx#1263]
httpx version:
v1.3.2

```console
echo scanme.sh:443 | httpx -ip -json | jq .a

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

		projectdiscovery.io

[INF] Current httpx version v1.3.4 (latest)
null
```

like this :

![image](https://github.com/projectdiscovery/httpx/assets/40236845/9c318ebc-4de4-46ff-aa82-f593e07665c2)

There is only a host record and no A record.

**Comment by MetzinAround** [comment]
HI @Miracles666 ! Thanks for the issue. Are these for websites that you know have an A record?

**Comment by Mzack9999** [comment]
@Miracles666 Can you provide the full command used and a target to reproduce the issue (feel free to DM me or pdteam on discord if you don't want to share it here)?

The A/AAAA record should definitely be present, otherwise no website would be able to work. The only case I might think about is that there is only a CNAME alias which points to an A record later in the resolution chain. In this case the particular domain has no strictly direct A record associated.

**Comment by Miracles666** [comment]
like this :
url is :http://ys.yishion.cn:85

command : httpx.exe -silent -t 20 -rl 50 -fr  -ec -sc -cl -title -td  -cname -l 1.txt -favicon -hash md5 -o result.json -json -irr

result: 
{
    "timestamp":"2023-08-20T14:26:08.1182606+08:00",
    "hash":{
        "body_md5":"f1af44a9cede48daad4e6a046cd882f7",
        "header_md5":"3ec6e30b0bae163214e26ad97b0707f9"
    },
    "port":"85",
    "url":"http://ys.yishion.cn:85",
    "input":"http://ys.yishion.cn:85",
    "title":"Redirect to...",
    "scheme":"http",
    "body":"\u003c!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"\u003e\r\n\u003chtml xmlns=\"http://www.w3.org/1999/xhtml\"\u003e\r\n\u003chead\u003e\r\n\u003cmeta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" /\u003e\r\n\u003ctitle\u003eRedirect to...\u003c/title\u003e\r\n\u003c/head\u003e\r\n\u003cbody\u003e\r\n\u003cscript type=\"text/javascript\"\u003e\r\nwindow.open(\"/LogInOut.php\", \"_top\");\r\n\u003c/script\u003e\r\n\u003c/body\u003e\r\n\u003c/html\u003e\r",
    "content_type":"text/html",
    "method":"GET",
    "host":"116.6.87.12",
    "path":"/",
    "favicon_path":"/favicon.ico",
    "final_url":"http://ys.yishion.cn:85/Redirect.php?url=/LogInOut.php\u0026type=logout",
    "header":{
        "cache_control":"private, proxy-revalidate no-transform",
        "content_type":"text/html",
        "date":"Sun, 20 Aug 2023 06:25:58 GMT",
        "expires":"Thu, 19 Nov 1981 08:52:00 GMT",
        "pragma":"no-cache",
        "server":"",
        "set_cookie":"PHPSESSID=khql5iqrpe3hsd4lc7ssi5cja4; path=/; HttpOnly",
        "vary":"Accept-Encoding,User-Agent",
        "x_frame_options":"SAMEORIGIN"
    },
    "raw_header":"HTTP/1.1 200 OK\r\nConnection: close\r\nCache-Control: private, proxy-revalidate no-transform\r\nContent-Type: text/html\r\nDate: Sun, 20 Aug 2023 06:25:58 GMT\r\nExpires: Thu, 19 Nov 1981 08:52:00 GMT\r\nPragma: no-cache\r\nServer: \r\nSet-Cookie: PHPSESSID=khql5iqrpe3hsd4lc7ssi5cja4; path=/; HttpOnly\r\nVary: Accept-Encoding,User-Agent\r\nX-Frame-Options: SAMEORIGIN\r\n\r\n",
    "request":"GET / HTTP/1.1\r\nHost: ys.yishion.cn:85\r\nUser-Agent: Opera/9.20 (Macintosh; Intel Mac OS X; U; en)\r\nAccept-Charset: utf-8\r\nAccept-Encoding: gzip\r\n\r\n",
    "time":"492.955ms",
    "chain_status_codes":[
        302,
        200
    ],
    "tech":[
        "PHP"
    ],
    "words":16,
    "lines":12,
    "status_code":200,
    "content_length":395,
    "failed":false,
    "knowledgebase":{
        "PageType":"other"
    }
}

There is only a host record and no A record or cname

**Comment by ehsandeep** [comment]
@Miracles666 @Mzack9999 this bug is now identified and fixed in https://github.com/projectdiscovery/httpx/pull/1347
