### ISSUE TITLE
Centralised Screenshots With Domain Names

### ISSUE THREAD

**Issue by lewilewi41** [projectdiscovery/httpx#1293]
Hi there folks, been using this a bit but its a real pain in the rear to get to the screenshots for reporting purposes.

Obviously i can point it at a directory, but with each image being in the domain named subfolder, makes it very hard for reporting on said screenshot.

Is there any way it could be integrated into the main branch to take the screenshots, title each screenshot the domain it was taken on (or overlay the domain as text/stamp on the image itself) and put them all in one folder, rather than the screenshots being named random things in the folder named as the domain. 

Thanks

The tool is brilliant btw.

:)

**Comment by MetzinAround** [comment]
Thanks for the issue and we're glad you like the tool, @lewilewi41. We're excited about having added screenshots recently, and appreciate the feedback on ways to make it more useful for folks' workflows. 

The OSS team looks at issues as they're working on new versions for enhancements. Someone may come in here and ask for more clarification on your use case, so keep an eye to this issue. 

Thanks again!

**Comment by Mzack9999** [comment]
@lewilewi41 now the tool generates an html summary with a few metadata, I'm not sure if this might fit your needs?

https://github.com/projectdiscovery/httpx/pull/1226

**Comment by lewilewi41** [comment]
@Mzack9999 thanks for the reply, what would be an example command for this, can't seem to get it to output screenshots and metadata displayed in a html page.

Thanks.

**Comment by dogancanbakir** [comment]
Have you had a chance to try it out, @lewilewi41?

**Comment by RFHACKE** [comment]
Is it possibe to add a features that outputs all screenshot under a screenshot folder and does not create subfolder for the domain name instead saves jpeg files with domain name

**Comment by RFHACKE** [comment]
@dogancanbakir the new feature seem extremely useful but the html files fails to load the images for some reason

**Comment by RFHACKE** [comment]
ok fixed it! the path to the screenshot does not include the whole path because of which it fails to load the png files and there is a 
url encoded \ %5c  which the browers does not decode for some reason 
![Capture](https://github.com/projectdiscovery/httpx/assets/43932773/c9c69d1b-9663-479a-8f60-3b8a3dfbb9a6)
here you can see the browser is unable to reach the file

**Comment by dogancanbakir** [comment]
@RFHACKE,  the issue you mentioned will be resolved once we merge this PR https://github.com/projectdiscovery/httpx/pull/1431.

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen this if the issue persists.

**Comment by RFHACKE** [comment]
thanks @dogancanbakir for solving the issue
