### ISSUE TITLE
HTTPX returns 403, but requests 200. Python

### ISSUE THREAD

**Issue by fakeastap** [projectdiscovery/httpx#1307]
I'm trying to parse one site. I'm sending a naked http request, just by setting a User-Agent.

It's surprising how a request using "requests" returns a 200 response. But the same query using httpx returns 403. I have tried making the request with both the 1.1 version of the http protocol and the 2.0 version. It didn't give any result.

I know that this site uses some protection against bots.

But why does the primitive "requests" do the job, as opposed to httpx?

I noticed that httpx adds a 'Host' header in its default request, which 'requests' does not. But I don't know how to get rid of it.

30 sec video: https://i.imgur.com/tWOe0sZ.mp4

httpx==0.24.1

**In my thread on stackoverflow I found one user with a similar problem: https://stackoverflow.com/questions/76133055/httpx-returns-403-but-requests-200-python?noredirect=1#comment135200607_76133055.
That's why I created a topic here.**

**Comment by fail-open** [comment]
I do not believe this is the httpx you are looking for.

**Comment by Mzack9999** [comment]
@fakeastap I think this is the wrong repository project, probably you should post your issue at https://github.com/encode/httpx

Being a python developer myself I guess that probably the CDN is rejecting the request based on the User Agent or TLS fingerprint, it's a very common issue also in go projects
