### ISSUE TITLE
[Feature] Fingerprint host via favicon hash

### ISSUE THREAD

**Issue by jayeshjodhawat** [projectdiscovery/httpx#131]
Add feature to fingerprint host via favicon hash like [FavFreak](https://github.com/devanshbatham/FavFreak/) tool.

This will allow identifying host running common services like Jira, Confluence, Grafana, etc.

**Comment by bauthard** [comment]
Hey @jayeshjodhawat, 

You can already do this with [nuclei](https://github.com/projectdiscovery/nuclei).

```
subfinder -d target.com | httpx | nuclei -t technologies/favicon-detection.yaml
```
