### ISSUE TITLE
The output result to csv is in a wrong format

### ISSUE THREAD

**Issue by wkend** [projectdiscovery/httpx#1312]
### httpx version:
V1.3.4
![image](https://github.com/projectdiscovery/httpx/assets/37563697/cdd3481d-ca23-4032-b1ac-0d4f92fd44fd)

### Steps To Reproduce:
1. Run 'httpx -l url.txt -random-agent -csvo utf-8 -o result.csv'
2. See error in csv file:
![image](https://github.com/projectdiscovery/httpx/assets/37563697/12d6f2f6-593d-4b32-b0c1-f79c2f782ac8)

**Comment by MetzinAround** [comment]
Hi! Thanks for the issue. I wasn't able to reproduce this issue on my end. Are you getting this error with any other targets other than the one that should be on line 7? For instance, if you remove the target for line 7, does the error still happen?

**Comment by wkend** [comment]
> Hi! Thanks for the issue. I wasn't able to reproduce this issue on my end. Are you getting this error with any other targets other than the one that should be on line 7? For instance, if you remove the target for line 7, does the error still happen?

My command is 
`httpx -u https://33a41a6c26a6c.cdn.sohucs.com -random-agent -csvo utf-8 -o 1.csv`
this problem can be reproduced
![image](https://github.com/projectdiscovery/httpx/assets/37563697/ca50a78f-ffae-4cdd-a1f9-2f75311c6e26)

**Comment by wkend** [comment]
> Hi! Thanks for the issue. I wasn't able to reproduce this issue on my end. Are you getting this error with any other targets other than the one that should be on line 7? For instance, if you remove the target for line 7, does the error still happen?

My command is 
`httpx -u https://33a41a6c26a6c.cdn.sohucs.com -random-agent -csvo utf-8 -o 1.csv`
this problem can be reproduced
![image](https://github.com/projectdiscovery/httpx/assets/37563697/ca50a78f-ffae-4cdd-a1f9-2f75311c6e26)

**Comment by wkend** [comment]
> Hi! Thanks for the issue. I wasn't able to reproduce this issue on my end. Are you getting this error with any other targets other than the one that should be on line 7? For instance, if you remove the target for line 7, does the error still happen?

My command is 
`httpx -u https://33a41a6c26a6c.cdn.sohucs.com -random-agent -csvo utf-8 -o 1.csv`
this problem can be reproduced
![image](https://github.com/projectdiscovery/httpx/assets/37563697/ca50a78f-ffae-4cdd-a1f9-2f75311c6e26)

**Comment by mr-rizwan-syed** [comment]
I am facing this issue too
CSV Output Feature was working in httpx version v1.3.0 properly

**Comment by Mzack9999** [comment]
It seems like the csv renderer is messing up with the new lines of the body. The sequences are escaped correctly, in fact google spreadsheet can import them without issues (as you can see only row 2 gets created):

<img width="1261" alt="Screenshot 2023-08-08 at 10 37 33" src="https://github.com/projectdiscovery/httpx/assets/13421144/7adc7b01-fc62-49da-90c5-c949700bcb74">

Are you using Microsoft Excel?

**Comment by mr-rizwan-syed** [comment]
> It seems like the csv renderer is messing up with the new lines of the body. The sequences are escaped correctly, in fact google spreadsheet can import them without issues (as you can see only row 2 gets created):
> 
> <img width="1261" alt="Screenshot 2023-08-08 at 10 37 33" src="https://github.com/projectdiscovery/httpx/assets/13421144/7adc7b01-fc62-49da-90c5-c949700bcb74">
> 
> Are you using Microsoft Excel?

Yes, I am using Microsoft Excel

**Comment by mr-rizwan-syed** [comment]
is this issue fixed ?

**Comment by iamthefrogy** [comment]
![image](https://github.com/projectdiscovery/httpx/assets/8291014/5b931648-aaa4-47d6-aa48-19a6952021ec)
Also facing the same issue.

**Comment by iamthefrogy** [comment]
@Mzack9999 @wkend @MetzinAround @mr-rizwan-syed @ndejong 

I solved this problem in an unconventional way temp for me.

Basically CSP output gets messed up but luckily, JSON does not. There are no HTML responses in JSON. So I am creating JSON and then converting that into CSV too whatever fields I want only. Hope that helps.

𝘩𝘵𝘵𝘱𝘹 -𝘭 𝘴𝘶𝘣𝘥𝘰𝘮𝘢𝘪𝘯𝘴.𝘵𝘹𝘵 -𝘴𝘪𝘭𝘦𝘯𝘵 -𝘯𝘤 -𝘫 -𝘰 𝘰𝘱.𝘫𝘴𝘰𝘯 | 𝘫𝘲 . > 𝘰𝘱2.𝘫𝘴𝘰𝘯 | 𝘦𝘤𝘩𝘰 '𝘐𝘯𝘱𝘶𝘵_𝘥𝘰𝘮𝘢𝘪𝘯,𝘜𝘙𝘓,𝘗𝘰𝘳𝘵,𝘏𝘰𝘴𝘵,𝘛𝘪𝘵𝘭𝘦,𝘊𝘰𝘯𝘵𝘦𝘯𝘵_𝘵𝘺𝘱𝘦,𝘊𝘰𝘯𝘵𝘦𝘯𝘵_𝘭𝘦𝘯𝘨𝘵𝘩,𝘈_𝘳𝘦𝘤𝘰𝘳𝘥,𝘊𝘕𝘈𝘔𝘌,𝘊𝘚𝘗 𝘋𝘰𝘮𝘢𝘪𝘯𝘴' > 𝘸𝘦𝘣𝘰𝘮𝘦𝘵𝘳𝘺.𝘤𝘴𝘷 && 𝘫𝘲 -𝘳 '[.𝘪𝘯𝘱𝘶𝘵, .𝘶𝘳𝘭, .𝘱𝘰𝘳𝘵, .𝘩𝘰𝘴𝘵, .𝘵𝘪𝘵𝘭𝘦, .𝘤𝘰𝘯𝘵𝘦𝘯𝘵_𝘵𝘺𝘱𝘦, .𝘤𝘰𝘯𝘵𝘦𝘯𝘵_𝘭𝘦𝘯𝘨𝘵𝘩, ((.𝘢 // 𝘦𝘮𝘱𝘵𝘺) | 𝘫𝘰𝘪𝘯(", ")) , ((.𝘤𝘯𝘢𝘮𝘦 // 𝘦𝘮𝘱𝘵𝘺) | 𝘫𝘰𝘪𝘯(", ")), (.𝘤𝘴𝘱.𝘥𝘰𝘮𝘢𝘪𝘯𝘴 // 𝘦𝘮𝘱𝘵𝘺 | 𝘫𝘰𝘪𝘯(", "))] | @𝘤𝘴𝘷' 𝘰𝘱2.𝘫𝘴𝘰𝘯 >> 𝘸𝘦𝘣𝘰𝘮𝘦𝘵𝘳𝘺.𝘤𝘴𝘷

**Comment by wkend** [comment]
As mentioned above, google spreadsheet can import them without any problem, so I will import to google spreadsheet first and then download to Microsoft Excel, this way will solve our problem.
