### ISSUE TITLE
Added fullURL is breaking RFC when storing response

### ISSUE THREAD

**Issue by ggranjus** [projectdiscovery/httpx#1317]
### Current Behavior:

When using `-store-response` option, *httpx* writes the url at the beginning of the stored response file.
As it is no more compatible with RFC Request followed by a Response when using it with `nuclei -passive`, it does not work.

It fallbacks to find the latest `HTTP/` pattern in content (see https://github.com/projectdiscovery/nuclei/blob/3894d466ada5d940f19cdfc82f58182f86dfadae/v2/pkg/protocols/offlinehttp/read_response.go#L28) and when response body contains that pattern, the parsing fails.

**Current stored response content**
```
https://pastebin.com/raw/TYsVwM0n

GET /raw/TYsVwM0n HTTP/1.1
Host: pastebin.com
User-Agent: Mozilla/5.0 (Windows NT 6.0; rv:36.0) Gecko/20100101 Firefox/36.0 SeaMonkey/2.33.1
Accept-Charset: utf-8
Accept-Encoding: gzip


HTTP/1.1 200 OK
Connection: close
[..]
```

### Expected Behavior:

The same response content file but without the url at the beginning.

**Expected stored response content**
```
GET /raw/TYsVwM0n HTTP/1.1
Host: pastebin.com
User-Agent: Mozilla/5.0 (Windows NT 6.0; rv:36.0) Gecko/20100101 Firefox/36.0 SeaMonkey/2.33.1
Accept-Charset: utf-8
Accept-Encoding: gzip


HTTP/1.1 200 OK
Connection: close
[...]
```

### Steps To Reproduce:

Using the same file mentionned in https://github.com/projectdiscovery/nuclei/issues/2068

1. `httpx -target https://pastebin.com/raw/TYsVwM0n -sr`
2. `nuclei -target output/response/pastebin.com/cdd3c9ae0a637aab7e139187408ed6ff1b12448d.txt -passive`

```shell
[INF] Current nuclei version: v2.9.10 (latest)
[INF] Current nuclei-templates version: v9.6.0 (latest)
[INF] New templates added in latest release: 33
[INF] Templates loaded for current scan: 878
[INF] Targets loaded for current scan: 1
[ERR] Could not read raw response output/response/pastebin.com/cdd3c9ae0a637aab7e139187408ed6ff1b12448d.txt: malformed HTTP status code "FOO"
[ERR] Could not read raw response output/response/pastebin.com/cdd3c9ae0a637aab7e139187408ed6ff1b12448d.txt: malformed HTTP status code "FOO"
[ERR] Could not read raw response output/response/pastebin.com/cdd3c9ae0a637aab7e139187408ed6ff1b12448d.txt: malformed HTTP status code "FOO"
[ERR] Could not read raw response output/response/pastebin.com/cdd3c9ae0a637aab7e139187408ed6ff1b12448d.txt: malformed HTTP status code "FOO"
[ERR] Could not read raw response output/response/pastebin.com/cdd3c9ae0a637aab7e139187408ed6ff1b12448d.txt: malformed HTTP status code "FOO"
[...]
```

### Anything else:

My guess is to remove that URL at the beginning of the stored reponse, added in https://github.com/projectdiscovery/httpx/commit/45f9f5c199409aa5aee9cbe10626fb1c0485ec08#diff-20e6696d056b9497806d8852a99dad01af18dab2c3378ebf73dee3ccbea93f45R1551 to remain compatible with the RFC and so the parsing with Nuclei when using `-passive` option. 

Another solution is to take this use case [when parsing in Nuclei](https://github.com/projectdiscovery/nuclei/blob/3894d466ada5d940f19cdfc82f58182f86dfadae/v2/pkg/protocols/offlinehttp/read_response.go#L14).

**Comment by dogancanbakir** [comment]
@ggranjus, Thank you for bringing up this issue. There may be a bug or limitation in Go's chunked decoding that is causing some response data to be misinterpreted. I tested this using `scanme.sh` and found no errors, but I encountered an error when using `projectdiscovery.io`. Also, removing the URL will make the output RFC compliant but won't affect the parsing. Still investigating the issue...
