### ISSUE TITLE
[Feature] To Remove Duplicate Entries for IPs 

### ISSUE THREAD

**Issue by teslatheg0d** [projectdiscovery/httpx#132]
Can you add a feature to filter duplicate entries for IPs...

**Comment by bauthard** [comment]
Hey @teslatheg0d, 

Can you elaborate more on how your input looks like? the output of any other tool or file with a list of IPs?

**Comment by teslatheg0d** [comment]
![Screenshot from 2020-10-04 12-19-00](https://user-images.githubusercontent.com/61558155/95008982-e33a0680-063b-11eb-9018-218ecba54ac7.png)
![Screenshot from 2020-10-04 12-18-30](https://user-images.githubusercontent.com/61558155/95008991-ecc36e80-063b-11eb-86ce-53ec6ef4f60f.png)

**Comment by teslatheg0d** [comment]
Hi @bauthard 

Sometimes IPs get duplicates in the list while recon and when we use httpx it also get duplicate.

**Comment by bauthard** [comment]
Hi @teslatheg0d, thank you for adding more context, in that case, we suggest to use `cat list.txt | sort -u | httpx`
