### ISSUE TITLE
tool is not wooooooorking. sir ji 

### ISSUE THREAD

**Issue by taku65maku** [projectdiscovery/httpx#1320]
when i run the command
1.  cat  apple.com.txt | httpx -status-code 
2. Error: no such option: -s
3. i download th tool from the official github repo. and it still not working

**Comment by ehsandeep** [comment]
See https://github.com/projectdiscovery/httpx/issues/632

You are running python version of httpx - https://www.python-httpx.org/

make sure to remove either of one or rename one of it.

**Comment by nbandodk** [comment]
┌──(pentest㉿pentestkalilinux)-[~]
└─$ which httpx      
/usr/bin/httpx
                                                                                                                                                                                                                                                                        
┌──(pentest㉿pentestkalilinux)-[~]
└─$ sudo rm /usr/bin/httpx

**Comment by dogancanbakir** [comment]
Were you able to solve the issue, @taku65maku? If not, please let us know so we can assist you.

**Comment by dogancanbakir** [comment]
Closing this now. If the issue persists, please feel free to reopen it.
