### ISSUE TITLE
HTTPX sets wrong path on WSL in screenshot function

### ISSUE THREAD

**Issue by SAMALAMA37** [projectdiscovery/httpx#1328]
### Steps To Reproduce:

Run example command
cat domains.txt | httpx -screenshot

After that when i visit the output/screenshot folder and open html file. It always sets a wrong path in the img src, sometimes missing folder, or sometimes extra folder

**Comment by lewilewi41** [comment]
I have the same issue, posted a bit ago but no fix/workaround as of yet.
