### ISSUE TITLE
httpx get stuck at the end

### ISSUE THREAD

**Issue by Kiblyn11** [projectdiscovery/httpx#134]
Hello,

I'm running httpx version 1.0.2.
I have httpx getting stuck and never finishing job (though I think it did), which makes it hard to pipe it to something else.
For instance it's been 3 times I try this command and its getting stuck at the end (few days and nothing move).

```
cat "subdomains.txt" | httpx -sr -srd httpx-responses -title -http2 -pipeline -cdn -web-server -json -content-length -content-type -status-code -vhost -websocket -ports 80,81,443,1080 -retries 2 -timeout 8 -threads 60 -o httpx.json
```

Subdomains file has 2470 lines.
I will forward it to you by discord.

**Comment by 00xfd** [comment]
I have the same problem with the docker instance :/

**Comment by bauthard** [comment]
This is not an issue in `httpx`,  causing delay due to the use of multiple probes and mixing up the checks as discussed in the discord. 

also `-debug` flag can be used to inspect the issue.

**Comment by 00xfd** [comment]
@bauthard In my case I only send `-ports 80,443,81,1099,1311,2082,2087,2095,2096,3000,3128,7000,8000,8001,8080,8081,8090,8443,8888,9000,9080,9090,9443,10199,10443 -follow-redirects -json -title -content-length -status-code -response-in-json `
