### ISSUE TITLE
New feature: The same target is only executed once in an hour

### ISSUE THREAD

**Issue by hktalent** [projectdiscovery/httpx#1349]
New feature: The same target is only executed once in an hour
now
```
cat xxx.txt|httpx -json -location -fr -o chaos-bugbounty-list-httpx.json -p 80,443

Targets may be added here

cat xxx.txt|httpx -json -location -fr -o chaos-bugbounty-list-httpx.json -p 80,443

```
Running the same command multiple times in this way can achieve better network optimization.

@ehsandeep 
It is recommended that all tools be limited to a certain time range and not be executed repeatedly, directly return the last result, and set up a cache
````
nuclei
subfinder
katana
httpx
naabu
proxify
uncover
dnsx
shuffledns
public-bugbounty-programs
tlsx
asnmap
wappalyzergo
````

**Comment by hktalent** [comment]
@ehsandeep 
Regarding caching, it is recommended to use "github.com/blevesearch/bleve/v2". I have proven in project practice that on SSD 4core CPU, 1 billion data queries are very fast.

**Comment by ehsandeep** [comment]
@hktalent, thanks for the feature suggestion, this is out of scope for a specific project, we have an alternate solution for this problem that will apply on all projects, and hopefully, we will release in the future.
