### ISSUE TITLE
Some json fields are inconsistent under linux and mac environments.

### ISSUE THREAD

**Issue by ttonys** [projectdiscovery/httpx#1350]
### different

linux: status_code、content_length、etc
mac:  status-code、content-length、etc

Is it possible to achieve unification? Special processing is required during integration with tools. Thank you.

**Comment by dogancanbakir** [comment]
@ttonys ,
Might I request additional information to understand the context better and repro the issue? Like, at what point you're doing preprocessing? Thanks!
