### ISSUE TITLE
Failed to launch the browse - Screenshot error

### ISSUE THREAD

**Issue by 0xPugazh** [projectdiscovery/httpx#1361]
### httpx version: 
```
Current httpx version v1.3.5 (latest)
```

### Current Behavior:

```
➜  httpx -l urls.txt -ss

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[INF] Current httpx version v1.3.5 (latest)
[FTL] Could not create runner: [launcher] Failed to launch the browser, the doc might help https://go-rod.github.io/#/compatibility?id=os: /home/user/.cache/rod/browser/chromium-1131003/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

**Comment by dogancanbakir** [comment]
The error message you see, "`error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory`," indicates that the `libnss3.so` shared library is missing from your system or not in a location where the system can find it. To fix this issue, install the `libnss3` package or ensure the library is correctly located in your system's library path. Here is how you can go about resolving this issue on a Linux system:

```bash
sudo apt update
sudo apt install libnss3
```

After installing the `libnss3` package, verify that the `libnss3.so` library is properly installed and in the system library path. You can do this with the following command:

```bash
ldconfig -p | grep libnss3
```

You should see `libnss3.so` in the output, indicating that it is available in the system's library path. Once you have confirmed that `libnss3.so` is appropriately installed, try running your `httpx` command again:

```bash
httpx -l urls.txt -ss
```

Hopefully, this should resolve the issue!

**Comment by dogancanbakir** [comment]
I'm closing this. Feel free to reopen if the issue persists.
