### ISSUE TITLE
When update the engine, got executable httpx not found in release asset `126018927` 

### ISSUE THREAD

**Issue by serundengsapi** [projectdiscovery/httpx#1362]
### Please describe your feature request:
1. My httpx version is 
[INF] Current httpx version v1.3.4 (outdated)
2. when want to update the to latest version using command, i got error like this
[updater] executable httpx not found in release asset `126018927` got: [:RUNTIME] failed to read response body <- context deadline exceeded (Client.Timeout or context cancellation while reading body)
![image](https://github.com/projectdiscovery/httpx/assets/79839503/883ac7b1-dbfb-4559-a90e-700e5b0301c2)

**Comment by serundengsapi** [comment]
@dogancanbakir, 
here for the additional information

$ uname -a
Linux TryHackMe 4.4.0-22621-Microsoft #1635-Microsoft Fri Jan 01 08:00:00 PST 2016 x86_64 x86_64 x86_64 GNU/Linux

$ httpx -version
    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[INF] Current Version: v1.3.4

$ httpx -up
    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

714.80 KiB / 13.15 MiB [-->____________________________________________________] 5.31% 24.67 KiB p/s
[updater] executable httpx not found in release asset `126018927` got: [:RUNTIME] failed to read response body <- context deadline exceeded (Client.Timeout or context cancellation while reading body)

**Comment by dogancanbakir** [comment]
Thanks for sharing @serundengsapi! While this method should work, it's not currently functioning. In the meantime, you can use our installation method to install any version. Check it out here: https://github.com/projectdiscovery/httpx#installation-instructions

**Comment by dogancanbakir** [comment]
@serundengsapi,
Can you give it another go and let me know if it's working now?

**Comment by dogancanbakir** [comment]
This is probably a temporary problem. I'm closing this. Feel free to reopen if the issue continues.
