### ISSUE TITLE
return `favicon_url` to output with `-favicon` option

### ISSUE THREAD

**Issue by Wnltc** [projectdiscovery/httpx#1381]
### Please describe your feature request:

Favicons for some sites may be saved on other hosts. It is recommended to save the full `favicon_url` for easier identification

```diff
{
  "timestamp": "2024-06-22T12:44:07.303516-07:00",
  "port": "443",
  "url": "https://support.dbappsecurity.com.cn",
  "input": "https://support.dbappsecurity.com.cn",
  "title": "安恒信息服务平台",
  "scheme": "https",
  "webserver": "nginx",
  "content_type": "text/html",
  "method": "GET",
  "host": "101.69.227.195",
  "path": "/",
  "favicon": "211261816",
  "favicon_path": "/image/favicon.ico",
+ "favicon_url": "https://internal10.dbappsecurity.com.cn:65525/image/favicon.ico",
  "time": "2.014704667s",
  "a": [
    "101.69.227.195"
  ],
  "tech": [
    "Nginx"
  ],
  "words": 201,
  "lines": 43,
  "status_code": 200,
  "content_length": 1198,
  "failed": false,
  "knowledgebase": {
    "PageType": "nonerror",
    "pHash": 0
  },
  "resolvers": [
    "100.95.0.252:53",
    "100.95.0.253:53"
  ]
}
```

### Describe the use case of this feature:

https://support.dbappsecurity.com.cn/

**Comment by yhy0** [comment]
It is recommended to check whether the domain name information is included. If there is a way to request to change the favicon url instead of updating the relative path, for example, the favicon path here in jd.com is incorrect.

https://www.jd.com/
```html
<link rel="icon" href="//www.jd.com/favicon.ico" mce_href="//www.jd.com/favicon.ico" type="image/x-icon"/>
```

Determine whether href is a relative path. If so, update the relative path. Others suggest creating a new request full path.

**Comment by ehsandeep** [comment]
@Wnltc @yhy0 `faivon_url` is now additionally returned in latest release - https://github.com/projectdiscovery/httpx/releases/tag/v1.6.5
