### ISSUE TITLE
freezing and no output

### ISSUE THREAD

**Issue by kuromaku001** [projectdiscovery/httpx#1389]
httpx was freezing after getting 4 lines of urls then now just freezes and dosent show any results 
the version is : 1.2.4

**Comment by kuromaku001** [comment]
![Untitled design](https://github.com/projectdiscovery/httpx/assets/133908339/ee0ec2cb-bb07-4b18-bbc2-f0b892bb5cb5)

**Comment by dogancanbakir** [comment]
@kuromaku001,
Thank you for reporting. Have you tried using the latest version?

**Comment by kuromaku001** [comment]
> @kuromaku001, Thank you for reporting. Have you tried using the latest version?

i installed it via `go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest` when it didnt work 
i changed latest to master

**Comment by dogancanbakir** [comment]
@kuromaku001,
Please provide the exact steps for me to reproduce the issue. Thanks. If you prefer not to share here, you can reach out over Discord.

**Comment by dogancanbakir** [comment]
Closing this. Feel free to reopen if the issue continues.
