### ISSUE TITLE
Since v1.3.5 I cannot build httpx on termux/android

### ISSUE THREAD

**Issue by intrd** [projectdiscovery/httpx#1414]
### httpx version:
v1.3.5

### Current Behavior:
Since version 1.3.5, I have been unable to successfully build httpx on Termux for Android.

### Expected Behavior:
v1.3.4 build normally.

### Steps To Reproduce:
```
~/test $ go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest

github.com/projectdiscovery/utils/permission
# github.com/projectdiscovery/utils/permission
../../go/pkg/mod/github.com/projectdiscovery/utils@v0.0.54/permission/permission_other.go:10:6: checkCurrentUserRoot redeclared in this block                                                                 
../../go/pkg/mod/github.com/projectdiscovery/utils@v0.0.54/permission/permission_linux.go:16:6: other declaration of checkCurrentUserRoot                                                     
../../go/pkg/mod/github.com/projectdiscovery/utils@v0.0.54/permission/permission_other.go:15:6: checkCurrentUserCapNetRaw redeclared in this block                                                            
../../go/pkg/mod/github.com/projectdiscovery/utils@v0.0.54/permission/permission_linux.go:21:6: other declaration of checkCurrentUserCapNetRaw
```

To avoid this build error, I need to downgrade to version 1.3.4.

```
go install -v github.com/projectdiscovery/httpx/cmd/httpx@v1.3.4
```

I am experiencing the same issue with other ProjectDiscovery tools such as naabu and uncover.

**Comment by intrd** [comment]
@RamanaReddy0M fix worked, thank you!
..also a temporary fix for other projects (naabu, uncover, nuclei etc..) is renaming `checkCurrentUserRoot` and `checkCurrentUserCapNetRaw` functions @ `utils@v.0.0.X/permission/permission_linux.go` and `permission_other.go`

**Comment by ehsandeep** [comment]
@intrd should be fixed in the latest release.
