### ISSUE TITLE
When using httpx's screenshot params, it creates a lot of zombie processes that can't be killed.

### ISSUE THREAD

**Issue by monitor403** [projectdiscovery/httpx#1416]
### Discussed in https://github.com/projectdiscovery/httpx/discussions/1415

<div type='discussions-op-text'>

<sup>Originally posted by **monitor403** October 26, 2023</sup>
When I use httpx's screenshot function to get website images in bulk, the process generates a lot of zombie processes, and after a large number of zombie processes have appeared, I can no longer create the httpx task, and report an error: **runtime: failed to create new OS thread (have 19 already; errno=11)**
![image](https://github.com/projectdiscovery/httpx/assets/45124775/32f57dd8-a3e1-4ef8-b6fe-5e43c9f7cbe8)
</div>

**Comment by MetzinAround** [comment]
Started working on this in discussions. Removing this one to keep single place for help.
