### ISSUE TITLE
-ec flag is ignored when -ports is used

### ISSUE THREAD

**Issue by tr3ss** [projectdiscovery/httpx#1417]
### httpx version:
v1.3.5

### Current Behavior:
httpx ignores the `-ec` flag when passing the `-ports` argument

### Expected Behavior:
CDN hosts are excluded

### Steps To Reproduce:
```bash
echo HOST | httpx -ec -threads 300 -no-fallback -random-agent -ports 80,443
```

![image](https://github.com/projectdiscovery/httpx/assets/21034728/2f0fc122-4bf4-499e-adb8-d31e72b4d8d4)

**Comment by acidvegas** [comment]
Dude httpx is really stupid the way arguments are parsed. I had the same issue, Try doing `-t 300` as the FIRST argument. I had an issue where when I used args that took an int as a value in the middle of the list of args, it would also ignore everything after that.

Let me know if that fixes it for you.

**Comment by meme-lord** [comment]
`-ec` isn't a flag on the latest version. To get the same behaviour you want to do `-e cdn`
