### ISSUE TITLE
The relative position of the image path does not render properly on html

### ISSUE THREAD

**Issue by enomothem** [projectdiscovery/httpx#1421]
### httpx version:
v1.3.6

### Current Behavior:

Displaying images
### Expected Behavior:

The image cannot be displayed.
### Steps To Reproduce:

```
httpx -l 1.txt -ss
```
![image](https://github.com/projectdiscovery/httpx/assets/45089051/0abd8e21-693c-46df-bdd8-de2f94347112)

**Comment by dogancanbakir** [comment]
@enomothem,
Thanks for letting us know. Can you add the screenshot output-dir structure and HTML file?

**Comment by enomothem** [comment]
- Windows11
- command:
`.\httpx.exe -ss -u bing.com`
- version: httpx 1.3.6
- output-dir
```
C:.
│  httpx.exe
│  httpx_1.3.6_windows_amd64.zip
│
└─output
    ├─response
    │  │  index.txt
    │  │
    │  ├─bing.com
    │  │      8c809e94e5ab7c2dfa18d0bc828c84cb5850e55f.txt
    │  │
    │  └─eonianxxx.com
    │          f20b3a07d09253844309304e3a768af30c3713ec.txt
    │
    └─screenshot
        │  index_screenshot.txt
        │  screenshot.html
        │
        ├─bing.com
        │      8c809e94e5ab7c2dfa18d0bc828c84cb5850e55f.png
        │
        └─eonianxxx.com
                f20b3a07d09253844309304e3a768af30c3713ec.png
```
![image](https://github.com/projectdiscovery/httpx/assets/45089051/ae6517f3-3408-47a8-9e4d-9c7158edcaa1)
