### ISSUE TITLE
 Could not take screenshot

### ISSUE THREAD

**Issue by eiko4** [projectdiscovery/httpx#1428]
### httpx version:
last, macOS Ventura

### Current Behavior:
`httpx -ss -retries 2 -v -u https://www.bugcrowd.com/`

```
    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

		projectdiscovery.io

[INF] Current httpx version v1.3.6 (latest)
[DBG] automatically enabling store response
[DBG] Store response directory not specified, using "output"
[WRN] Could not take screenshot 'https://www.bugcrowd.com/': context deadline exceeded
https://www.bugcrowd.com/
```
It works with other hosts! exception called `bugcrowd.com` and `www.bugcrowd.com`

### Expected Behavior:
Success Screenshot

### Steps To Reproduce:
steps to reproduce the behavior:
1. Run `httpx -ss -retries 2 -v -u https://www.bugcrowd.com/`
2. See error...

**Comment by MetzinAround** [comment]
Hi @eiko4 , thanks for the issue. 

I have to screenshots, one where the command worked fine with an older version, and one where it didn't' (latest version). but I have a slightly different error in mine. Is your error always the same? 
![Screenshot -1106 at 16 13 @2x](https://github.com/projectdiscovery/httpx/assets/65838556/d27010cd-2fca-4302-baa0-de5eac1af99d)
![Screenshot -1106 at 16 14 @2x](https://github.com/projectdiscovery/httpx/assets/65838556/337649fc-a52f-4f26-ae37-79ba19ecf168)


Does appear to be an issue, and a weird one with two different errors. I'll see what else I can find.
