### ISSUE TITLE
-match-string not working

### ISSUE THREAD

**Issue by Phoenix1112** [projectdiscovery/httpx#145]
hello team.. thanks for this project. I am experimenting with the Werkzeug debug console on the local network. I can access the werkzeug debug console website with this url address. http://127.0.0.1/console

Since there is the word "werkzeug" in response, I use the -match-string Werkzeug command.

```
cat urls.txt:

https://www.google.com
http://127.0.0.1
https://www.facebook.com

```

```
cat urls.txt | httpx -ports 80,443 -timeout 10 -path /console -match-string Werkzeug
```

When I run this command, the program ends without giving me any results. If the program was running correctly it would show me this url in the results.>>(http://127.0.0.1:80/console) ..but it shows no results.

**Comment by Phoenix1112** [comment]
example video:

https://www.youtube.com/watch?v=bQiwmtQYtZA

**Comment by bauthard** [comment]
@Phoenix1112 thank you for reporting this, this is now fixed in the master code.

**Comment by ahmed1231230** [comment]
It seems that the problem is there

``` bash
abdalla@eg~/go/bin/httpx/cmd/httpx$ echo 'https://www.google.com/' |httpx -match-string https

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.0.3

                projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
https://www.google.com/
abdalla@eg:~/go/bin/httpx/cmd/httpx$
```

**Comment by bauthard** [comment]
Hey @ahmed1231230, 

That's how it supposed to work, in case of a valid match you will notice the output, as in this case, `https` is matched in the response, so the output, in case of no match, no URL will be printed in the output.
