### ISSUE TITLE
error in "go build" command

### ISSUE THREAD

**Issue by learn-alam** [projectdiscovery/httpx#147]
Hi.....
when i am running "go build" command i am facing following issue.
So please help me.
/httpx/cmd/httpx$ go build
httpx.go:5:2: use of internal package not allowed

**Comment by bauthard** [comment]
Hi @learn-alam, 

This is because you have an old version of `GO` installed on your system, either you can update the GO before installing the https or simply download the ready to use binary file from here https://github.com/projectdiscovery/httpx/releases
