### ISSUE TITLE
Output file detected as binary file

### ISSUE THREAD

**Issue by Curiosa04** [projectdiscovery/httpx#148]
When outputting the results to a file the file content-type is detected as binary. This is caused by the output coloring and the combination of flags.

## Steps to reproduce
1. echo example.com | httpx  -status-code -content-type -content-length -title -web-server -websocket -cname -o test1
2. less test1
### Bash output
"test1" may be a binary file.  See it anyway?
### File contents
https://example.com [ESC[32m200ESC[0m] [ESC[35m1256ESC[0m] [ESC[35mtext/htmlESC[0m] [ESC[36mExample DomainESC[0m] [ECS (dcb/7EEC)]

## Workaround
Add the -no-color flag with the other flags. E.g. httpx **-no-color**  -status-code -content-type -content-length -title -web-server -websocket -cname -o test1

**Comment by bauthard** [comment]
@Curiosa04 there is already `-no-color` flag ^ not sure you missed or?

**Comment by Curiosa04** [comment]
sorry for not being clear in my workaround. I meant add the -no-color flag with the other flags to disable the coloring and have a correct output file.
It seems a bug that I have to specify an extra flag to get the correct output in my file (without ESC[32m and ESC[0m])

**Comment by bauthard** [comment]
@Curiosa04 `-no-color` will work for all flags, you only need to add `no-color` flag with your existing command 

```
echo example.com | httpx -no-color -status-code -content-type -content-length -title -web-server -websocket -cname -o test1
```

**Comment by bauthard** [comment]
Closing as this is not an issue, adding `-no-color` will solve the issue.
