### ISSUE TITLE
fatal error: runtime: out of memory   httpx - signal SIGKILL (Forced quit)

### ISSUE THREAD

**Issue by atlassion** [projectdiscovery/httpx#1496]
Process xxx, 'httpx' from job 1, 'cat ~/file.txt…' terminated by signal SIGKILL (Forced quit)

cat file.txt | httpx -o file.json

how to resolve this error?  rate-limit: default

**Comment by acidvegas** [comment]
use `-stream -sd` at the end of httpx
```
-s, -stream                   stream mode - start elaborating input targets without sorting
-sd, -skip-dedupe             disable dedupe input items (only used with stream mode)
```

This will start the scanning right away....but I feel as if it has memory leaks over time....I Had this same issue and the only fix was using a box with better specs.

**Comment by acidvegas** [comment]
Yeah Im using a box with 4gb ram and it hasnt broke yet. I highly suspect memory leak issues with httpx.
