### ISSUE TITLE
How can I scan http first?

### ISSUE THREAD

**Issue by imlonghao** [projectdiscovery/httpx#15]
Hello,

I am trying to scan some websites and detect its title and status code.

Those website only serve at http, even it have valid SSL certificate (*.example.com) but it is a Nginx default page for https.

I fed httpx with list of domains starting with `http://`, but currently httpx will try https first, if fail, fallback to http.

How can I force httpx to scan the list in http protocol without auto upgrade to https?

Thanks in advance.

**Comment by bauthard** [comment]
Hey @imlonghao, 

You can make use of ports if you want to force to probe HTTP only.

```
httpx -ports 80
```

**Comment by imlonghao** [comment]
What if I want to scan some domain in http while some in https?

list.txt

```
http://a.example.com
https://b.example.com
http://c.example.com
```

**Comment by bauthard** [comment]
Hey, that's how it works on default run, it checks for `https` first, if it doesn't work it checks for `http`, if you want both, you can do `-ports 80,443`

also if you feed input like below, you don't have to deal with this manually and as `httpx` will handle it on its own. 

```
a.example.com
b.example.com
c.example.com
```

**Comment by bauthard** [comment]
please drop additonal comments for more questions, closing this for now.
