### ISSUE TITLE
Failure to Follow Redirects with the `-ports` Option

### ISSUE THREAD

**Issue by Osb0rn3** [projectdiscovery/httpx#1518]
I've encountered an issue with the HTTPX tool. It appears that when I include the `-ports https:443` switch, the tool fails to follow redirects. However, when I remove it, everything works as expected.

Here are the two commands I've been running:

```bash
echo "uatworkspace.sprint.com" | httpx -rate-limit 10 -json -td -fhr -irr -silent | jq
echo "uatworkspace.sprint.com" | httpx -ports https:443 -rate-limit 10 -json -td -fhr -irr -silent | jq
```

Follow redirect working correctly without using `-ports`:
<img src="https://github.com/projectdiscovery/httpx/assets/88091064/b70e7269-6ddf-4f1e-87fa-bfdf57a43594" alt="">

It fails to follow redirect when adding `-ports`:
<img src="https://github.com/projectdiscovery/httpx/assets/88091064/45ba9b8d-8b59-4af9-8289-8b33c0e7a178">

**Comment by acidvegas** [comment]
Ok so I noticed with HTTPX it is very weird the way it parses arguments that have input after them. All I can suggest is you try to record the arguments. Put the rate limit first.

HTTPx is like horrible @ how it parses arguments and will ignore everything after certain arguments if it's not in the right order. No idea why.
