### ISSUE TITLE
Json parsing error while validating the json output in JSONLint

### ISSUE THREAD

**Issue by sA74n** [projectdiscovery/httpx#152]
while beautifying the output of json in any online website i encounter an error saying

**Error: Parse error on line 22:
...": "500.794337ms"} {	"ips": ["13.227.1
----------------------^
Expecting 'EOF', '}', ',', ']', got '{'**

**Comment by bauthard** [comment]
@sA74n Can you share the complete output block that you are trying to `beautify`?

**Comment by sA74n** [comment]
u want me to show u the json output

**Comment by bauthard** [comment]
Yes @sA74n

**Comment by sA74n** [comment]
{
	"ips": ["121.241.160.187"],
	"cnames": ["connect.vpn.indeed.com"],
	"url": "https://cloud.vpn.indeed.com",
	"location": "",
	"title": "",
	"webserver": "",
	"content-type": "text/html",
	"method": "GET",
	"ip": "121.241.160.187",
	"content-length": 170,
	"status-code": 200,
	"tls": {
		"dns_names": ["*.vpn.indeed.com", "vpn.indeed.com"],
		"common_name": ["*.vpn.indeed.com", "DigiCert SHA2 High Assurance Server CA", "DigiCert High Assurance EV Root CA"],
		"organization": ["Indeed, Inc.", "DigiCert Inc", "DigiCert Inc"],
		"issuer_common_name": ["DigiCert SHA2 High Assurance Server CA", "DigiCert High Assurance EV Root CA", "DigiCert High Assurance EV Root CA"],
		"issuer_organization": ["DigiCert Inc", "DigiCert Inc", "DigiCert Inc"]
	},
	"vhost": false,
	"http2": false,
	"response-time": "256.134466ms"
} {
	"ips": ["121.241.160.187"],
	"cnames": ["connect.vpn.indeed.com"],
	"url": "https://external.vpn.indeed.com",
	"location": "",
	"title": "",
	"webserver": "",
	"content-type": "text/html",
	"method": "GET",
	"ip": "121.241.160.187",
	"content-length": 170,
	"status-code": 200,
	"tls": {
		"dns_names": ["*.vpn.indeed.com", "vpn.indeed.com"],
		"common_name": ["*.vpn.indeed.com", "DigiCert SHA2 High Assurance Server CA", "DigiCert High Assurance EV Root CA"],
		"organization": ["Indeed, Inc.", "DigiCert Inc", "DigiCert Inc"],
		"issuer_common_name": ["DigiCert SHA2 High Assurance Server CA", "DigiCert High Assurance EV Root CA", "DigiCert High Assurance EV Root CA"],
		"issuer_organization": ["DigiCert Inc", "DigiCert Inc", "DigiCert Inc"]
	},
	"vhost": false,
	"http2": false,
	"response-time": "287.754073ms"
}

**Comment by sA74n** [comment]
![js](https://user-images.githubusercontent.com/66728876/97841488-ee03bc00-1d0b-11eb-849c-32290aac1f57.png)

**Comment by bauthard** [comment]
Hi @sA74n, 

I mean the output content that you trying to validate, can you post here, for example:- `echo 1.1.1.1 | httpx -silent -json` gives following output and it's valid on https://jsonlint.com


```
{"url":"https://1.1.1.1","content-length":48916,"status-code":200,"location":"","title":"1.1.1.1 — The free app that makes your Internet faster.","vhost":false,"webserver":"cloudflare","content-type":"text/html","tls":{"dns_names":["cloudflare-dns.com","*.cloudflare-dns.com","one.one.one.one"],"common_name":["cloudflare-dns.com","DigiCert ECC Secure Server CA"],"organization":["Cloudflare, Inc.","DigiCert Inc"],"issuer_common_name":["DigiCert ECC Secure Server CA","DigiCert Global Root CA"],"issuer_organization":["DigiCert Inc","DigiCert Inc"]},"http2":false,"method":"GET"}
```

**Comment by sA74n** [comment]
but i am not doing httpx for a single url, inputting a list of urls
`cat shuffledns.txt aiodnsbrute.txt | sort -u |httpx -title -location -o httpx-output.txt -threads 200 -cdn -status-code retries 5`

**Comment by sA74n** [comment]
> but i am not doing httpx for a single url, inputting a list of urls
> `cat shuffledns.txt aiodnsbrute.txt | sort -u |httpx -title -location -o httpx-output.txt -threads 200 -cdn -status-code retries 5`

json validation works for only one url, but not for multiple urls as input

**Comment by bauthard** [comment]
@sA74n it works for multiple URLs as well, you can confirm with the following:- 

```
subfinder -d hackerone.com -sources crtsh | httpx -json -silent | jq .
```

**Comment by sA74n** [comment]
`cat http.json | jq .
parse error: Invalid numeric literal at line 1, column 6`
i am getting this error:(

**Comment by sA74n** [comment]
sry bymistakely i closed it

**Comment by sA74n** [comment]
![test](https://user-images.githubusercontent.com/66728876/97843138-c9f5aa00-1d0e-11eb-95c1-53a7039112b0.png)

**Comment by sA74n** [comment]
![test](https://user-images.githubusercontent.com/66728876/97843193-e0036a80-1d0e-11eb-98e5-7d3d028bff3f.png)

**Comment by bauthard** [comment]
@sA74n Can you upload `http.json` file here or join the discord server linked in the project to discuss this further.
