### ISSUE TITLE
A lot of false status codes 

### ISSUE THREAD

**Issue by MR-pentestGuy** [projectdiscovery/httpx#153]
https://be.hardware.info/forum/attachment.php?attachmentid=19310&d=1366206216&thumb=1 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=19374&stc=1&thumb=1&d=1366819301 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=18043&stc=1&thumb=1&d=1360584737 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=19375&stc=1&thumb=1&d=1366819130 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=19373&stc=1&thumb=1&d=1366819116 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=18046&stc=1&thumb=1&d=1360584737 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=19298&stc=1&thumb=1&d=1365889866 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=19379&stc=1&thumb=1&d=1366853694 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=19309&d=1366206189&thumb=1 [200]

while all these urls are 301 

if you want you can check it

**Comment by bauthard** [comment]
Hi @MR-pentestGuy, 

It's the cookie page before the redirect, if you open in a new browser, you will see 200, as such this is expected. 

![image](https://user-images.githubusercontent.com/8293321/98160319-0b9b7600-1f04-11eb-88c2-2702b6a04f02.png)
