### ISSUE TITLE
httpx strugles when probing and writing result ot a file on disk huge subdomains lists (> 20k subdomains)

### ISSUE THREAD

**Issue by MinhPham123456789** [projectdiscovery/httpx#1534]
### httpx version:

httpx version: 1.3.7
Running in Kali Linux ARM64

### Current Behavior:

With a list of more than 80k subdomains, httpx starts to struggle when probing more than 18k of subdomains and saving the result in a file on disk. It took httpx over an hours to go through the first 19k subdomain.

Update on 14/01/2024:
After a couple more test with the -timeout 2 and -retries 1 flags, httpx stills hangs or struggle when passing the first 3k subdomains in a list

### Expected Behavior:

httpx should completed the list within an hour

### Steps To Reproduce:

Used command:
`httpx -sc -silent -rl 300 -l [subdomain_list] -o output.txt > /dev/null`

**Comment by acidvegas** [comment]
I am with you on this, I have tinkered with httpx so much but it's always slow as shit for a golang project when you want to handling hundreds of thousands of domains.

**Comment by Skzimm** [comment]
my problem is that the "-l" command isn't working

**Comment by acidvegas** [comment]
Have -l be the first argument you provider @Skzimm there is really dumb parsing issuing with the arguments and their order with httpx right now lol.

**Comment by MinhPham123456789** [comment]
My guess is that the target may try to block the requests from httpx after a couple of thousands requests were made as a DOS protection mechanism.
In case it is the scenario, httpx should implement a timeout for a subdomain and then put in the output the subdomain with the label timeout or the status code and go on with the other ones to avoid wasting time.

One outside of topic question is which kind of VPN do you use to avoid being banned. Anybody tried proxychain before it is an old tool (around couple years ago), I heard it couple of times back then but have not tried it yet

**Comment by Skzimm** [comment]
> Have -l be the first argument you provider @Skzimm there is really dumb parsing issuing with the arguments and their order with httpx right now lol.

forget it! I've already solved my issues
