### ISSUE TITLE
lot of false response codes 

### ISSUE THREAD

**Issue by MR-pentestGuy** [projectdiscovery/httpx#154]
https://be.hardware.info/forum/attachment.php?attachmentid=19310&d=1366206216&thumb=1 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=19374&stc=1&thumb=1&d=1366819301 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=18043&stc=1&thumb=1&d=1360584737 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=19375&stc=1&thumb=1&d=1366819130 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=19373&stc=1&thumb=1&d=1366819116 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=18046&stc=1&thumb=1&d=1360584737 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=19298&stc=1&thumb=1&d=1365889866 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=19379&stc=1&thumb=1&d=1366853694 [200]
https://be.hardware.info/forum/attachment.php?attachmentid=19309&d=1366206189&thumb=1 [200]

while all these urls are 301 

if you want you can check it

**Comment by bauthard** [comment]
Please see https://github.com/projectdiscovery/httpx/issues/153#issuecomment-721937122
