### ISSUE TITLE
httpx giving false positive results

### ISSUE THREAD

**Issue by aravindb26** [projectdiscovery/httpx#1554]
### httpx version:
httpx (v1.3.9)

### Current Behavior:
When utilizing the following command to retrieve status codes:
```bash
httpx -u https://twitter.com/nanicyb -sc
```
The tool occasionally outputs both 200 and 400 status codes upon multiple executions.

### Expected Behavior:
It is suggested that the tool should consistently display the exact status code for a given URL, providing unambiguous information. For instance, executing the command should ideally result in a clear output such as `https://twitter.com/nanicyb is 200`.

### Anything else:
The current behavior may lead to confusion for users relying on httpx as a trustworthy tool for status code information. Updating the tool to consistently provide precise results would enhance its usability and save users' time.

I appreciate your attention to this matter and look forward to any improvements that can be made in future releases.

Thank you for your time and dedication to maintaining the httpx tool.
<img width="408" alt="httpx" src="https://github.com/projectdiscovery/httpx/assets/89305482/d02b647e-f0ac-4686-ad8f-6d88532de66c">

**Comment by dogancanbakir** [comment]
To temporarily fix the issue of the target blocking a randomly assigned user agent, you can use the `-random-agent false` option. We are working to replace the current library with https://github.com/projectdiscovery/useragent soon to prevent such issues from happening in the future.

**Comment by dogancanbakir** [comment]
depends on https://github.com/projectdiscovery/useragent/pull/108

**Comment by aravindb26** [comment]
> To temporarily fix the issue of the target blocking a randomly assigned user agent, you can use the `-random-agent false` option -this might not work every time. We are working to replace the current library with https://github.com/projectdiscovery/useragent soon to prevent such issues from happening in the future.

I used the flag `-random-agent false` but that too has same issue.

**Comment by aravindb26** [comment]
How could i solve the issue and get exact status code ? I mean it's difficult to check thousands of urls manually

**Comment by dogancanbakir** [comment]
As previously mentioned, we will resolve this problem once we merge https://github.com/projectdiscovery/useragent/pull/108. We appreciate your patience as we work on resolving the issue.

**Comment by aravindb26** [comment]
> As previously mentioned, we will resolve this problem once we merge [projectdiscovery/useragent#108](https://github.com/projectdiscovery/useragent/pull/108). We appreciate your patience as we work on resolving the issue.

Ok sir that's fine :) Hoping to resolved it soon. So does it comes under a bug category, I mean will it be accepted if we submit at H1 ?

**Comment by dogancanbakir** [comment]
Regarding your question, the problem you mentioned does not fall under the category of a security issue/bug, so there wouldn't be any need to submit it at H1. But, thank you for opening this issue!

**Comment by aravindb26** [comment]
Hi team,

I think still issue was not fixed
<img width="347" alt="httpx_" src="https://github.com/projectdiscovery/httpx/assets/89305482/97aee0bd-dcb5-412c-a50b-84fe29c62e4f">
