### ISSUE TITLE
Request CDN IP ranges only when `-cdn` flag is passed

### ISSUE THREAD

**Issue by bugbaba** [projectdiscovery/httpx#158]
Hi Team,

httpx failed due to `https://www.cloudflare.com/ips-v4` being blocked on the network, I would suggest a better approach would be to request these CDN IP ranges only when user has passed `-cdn` flag. Which will make the httpx work in environments where these specific urls are blocked or in the ones which doesn't have internet access at all.

![image](https://user-images.githubusercontent.com/29960776/98469905-41907100-2208-11eb-96d6-40e03e6317f1.png)

--
Regards,
@bugbaba

**Comment by bauthard** [comment]
Thank you @bugbaba, this is fixed here https://github.com/projectdiscovery/httpx/pull/130, new release will be pushed shortly.
