### ISSUE TITLE
[Feature Request] match-regex to headers matches

### ISSUE THREAD

**Issue by bminossi** [projectdiscovery/httpx#159]
Hi guys =),
First of all, thank u all again for this amazing tool which is helping us and giving back so much value to hack comunity <3.
I was checking all closed issues to see if this wont be a duplicated request but i couldnt find something similar.
On my recon proccess, i was needing some flag/feature to match results from -csp-probe / -tls-probe, for example:
- You do a request to an IP which have an invalid certificate.
- It will pop up a new wildcard domain
- I think that nowadays it could be extracted from httpx using -tls-probe but,
Can we filter it to match these domains with a regex and return default output like [matchedextracted.domain.tld]?
Thank u all

**Comment by bauthard** [comment]
Hi @bminossi, 

Thank you for sharing feedbacks, `httpx` does have `string` and `regex` based matcher and filter support, but that works on the response data, not on the result itself, also we think what you suggesting here can be done with post text processing with `grep`, `awk`, `sed` or any similar utility and the right way to do it, with `httpx` we are trying to keep it simple and support as much as possible HTTP based probings, with that said closing this issue.
