### ISSUE TITLE
CSV output ignores command line options for what to extract

### ISSUE THREAD

**Issue by Spidle** [projectdiscovery/httpx#1593]
### httpx version:
v1.4.0

### Current Behavior:
When 

### Expected Behavior:
When running http with -csv as the output, I should only get the data columns that I've specified in the command line. However, I get everything instead. no problem for one site, but for hundreds, its way too much data.

### Steps To Reproduce:
run httpx without csv
echo "yahoo.com" | httpx -title -status-code -tech-detect -follow-redirects -asn -ip -cdn -server -ss

![image](https://github.com/projectdiscovery/httpx/assets/90011249/47fc1f77-43a6-42db-80a6-024fa92ef1dc)

run httpx with csv

echo "yahoo.com" | httpx -title -status-code -tech-detect -follow-redirects -asn -ip -cdn -server -ss -csv -o out.csv

![image](https://github.com/projectdiscovery/httpx/assets/90011249/d7000078-7b5e-45ef-9ae9-f97717f9a51c)

**Comment by ehsandeep** [comment]
@Spidle thanks for flagging this, although default output fields are not created based on CLI input, including body / header as default is unexpected and seems be a bug that we will fixing asap.

**Comment by Spidle** [comment]
> @Spidle thanks for flagging this, although default output fields are not created based on CLI input, including body / header as default is unexpected and seems be a bug that we will fixing asap.

Thanks for looking at it! I suppose another alternative would be to omit in the same way that PD's Katana does with -or and -ob.

**Comment by ehsandeep** [comment]
@Spidle now excluded as default, can be optionally included with latest release, see https://github.com/projectdiscovery/httpx/releases/tag/v1.6.0

**Comment by lovelyjuice** [comment]
The bug still exists in httpx now, when using the `-filter-condition` parameter
