### ISSUE TITLE
exclude option still has bugs in version 1.5.0

### ISSUE THREAD

**Issue by ipsecc** [projectdiscovery/httpx#1615]
### httpx version:
1.5.0

### Description:
Hi team, I created an [issue](https://github.com/projectdiscovery/httpx/issues/1580) last month, thanks for the quick response. However, after my test, there are still bugs in some scenarios.

### Flag "*" not work:
```
root@ubuntu:~# httpx -u docs.hackerone.com -exclude "doc*.hackerone.com" -v

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[INF] Current httpx version v1.5.0 (latest)
https://docs.hackerone.com
```

### Got the wrong output:
```
root@ubuntu:~# httpx -u durobotdev.baidu.com:8080 -exclude "docs.hackerone.com" -v

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[INF] Current httpx version v1.5.0 (latest)
[DBG] Skipping target due to network policy: durobotdev.baidu.com
[DBG] Failed 'durobotdev.baidu.com:8080': target host is not allowed by network policy
```

**Comment by dogancanbakir** [comment]
Thanks for opening this issue. See https://github.com/projectdiscovery/httpx/pull/1597#pullrequestreview-1898771260 - so, it should be `httpx -u docs.hackerone.com -exclude "doc.\.hackerone\.com" -v`. Feel free to let me know if you have any questions.

**Comment by dogancanbakir** [comment]
Great catch! I raised a PR at https://github.com/projectdiscovery/networkpolicy/pull/72, and I'll fix this once the PR is merged.

**Comment by dogancanbakir** [comment]
Depends on https://github.com/projectdiscovery/networkpolicy/issues/71

**Comment by ehsandeep** [comment]
should be fixed with latest release - https://github.com/projectdiscovery/httpx/releases/tag/v1.6.0
