### ISSUE TITLE
[issues] spaces in ports values ignores the port input

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/httpx#162]
```sh
echo hackerone.com | httpx -silent -ports 80,443
http://hackerone.com:80
https://hackerone.com:443
```

```sh
echo hackerone.com | httpx -silent -ports 80, 443
http://hackerone.com:80
```

**Comment by melardev** [comment]
Is this related to my pull request #156 ?

The TrimSpace is there:
```go
potentialPort = strings.TrimSpace(strings.ToLower(potentialPort))
```

Also, it should print a warning, was it the latest version?

**Comment by bauthard** [comment]
@melardev Yes, on the latest version.

```
echo hackerone.com | httpx -ports 80, 443

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.0.3

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
http://hackerone.com:80
```

**Comment by melardev** [comment]
@bauthard I am a little bit relieved to know it was not my pull request the causing of the issue, the function received "80, " as input, it makes sense, a space breaks everything, It is normal behaviour, if you want a to feed a string with spaces as input you have to quote it.

**Comment by Mzack9999** [comment]
Closing - This is working as expected as spaces are commonly used for CLI arguments tokenization (thanks for confirming @melardev ). It should be safe to use `gologger.warningf` since the library handles the print logic internally.
