### ISSUE TITLE
-mc matching code 200,300 

### ISSUE THREAD

**Issue by ashhadali10** [projectdiscovery/httpx#163]
-mc matching code 200,300  function not working

**Comment by bauthard** [comment]
@ashhadali10 Can you post the output of `httpx -verson`?

**Comment by ashhadali10** [comment]
Current Version: 1.0.2

**Comment by bauthard** [comment]
@ashhadali10 make sure you are running the latest version of the project -- https://github.com/projectdiscovery/httpx/releases

**Comment by bauthard** [comment]
Closing as this is not an issue @ashhadali10, updating to the latest version will fix this.
