### ISSUE TITLE
Split the response file into a header file and a body file.

### ISSUE THREAD

**Issue by gprime31** [projectdiscovery/httpx#1639]
Split the response file into a header file and a body file to make it easier to parse.

**Comment by GeorginaReeder** [comment]
Thanks so much for your suggestion @gprime31 , we appreciate it!

**Comment by gprime31** [comment]
you can just make a flag that does it, if needed.

**Comment by Mzack9999** [comment]
@gprime31 if you use `-json` with the flag `-irr` the fields are already separated in the `body` and `header/raw_header` fields
