### ISSUE TITLE
[Feature Request] add some site path

### ISSUE THREAD

**Issue by zuoookr** [projectdiscovery/httpx#168]
for example:

https://google.com

request url:
https://google.com/google.com.zip

you can add some dynamic parsing url

```
httpx -path /{site}.zip
```

**Comment by bauthard** [comment]
Hi @zuoookr, 

We have another project called [nuclei](https://github.com/projectdiscovery/nuclei) doing exactly what you looking for, as such we suggest using nuclei for similar use cases, closing this issue now.
