### ISSUE TITLE
Character display  abnormally

### ISSUE THREAD

**Issue by Am-ev** [projectdiscovery/httpx#169]
![image](https://user-images.githubusercontent.com/36665394/101431760-76483300-3942-11eb-8a1c-3f9dc01f4d99.png)
is there any way to fix this？I had try to use command "chcp 437".But it`s useless.
Current OS:Win10x64
chcp: 936 (ANSI/OEM - 简体中文 GBK)
Thks.

**Comment by bauthard** [comment]
Hi @Am-ev, 

You can use `no-color` flag to avoid this in the windows environment.
