### ISSUE TITLE
Changing runner.Options doesn't change live domain output, only goes to stdout

### ISSUE THREAD

**Issue by GeorginaReeder** [projectdiscovery/httpx#1692]
### httpx version:
v1.6.0

### Current Behavior:
When running a scan with httpx, it outputs the domains to stdout. It doesn't seem to be possible to put the live domains into a map, leaving the terminal empty.

`ResponseInStdout` [exists in the options.go](https://github.com/projectdiscovery/httpx/blob/76e61cc6036ec6533460777a355ffc8557eba77b/runner/options.go#L211), but changing/setting this in `runner.Options` doesn't seem to make a difference.

### Expected Behavior:
When changing `runner.Options`, it should be possible to change where live domains are sent (i.e. to a map, instead of to stdout).

### Steps To Reproduce:
`runner.Options` settings look like this, and seem to return an error:

<img width="740" alt="Screenshot 2024-05-08 at 13 06 42" src="https://github.com/projectdiscovery/httpx/assets/162604596/d5995ea4-945d-4406-9386-5075c127b08c">

### Anything else:
Reported in [Discord here](https://discord.com/channels/695645237418131507/716605549923270717/1237403503115112539).

**Comment by dogancanbakir** [comment]
As a workaround, you can try setting `gologger.DefaultLogger.SetMaxLevel(-1)`. Let me know if you have any other questions!

```go
package main

import (
	"fmt"
	"log"

	"github.com/projectdiscovery/goflags"
	"github.com/projectdiscovery/gologger"
	"github.com/projectdiscovery/httpx/runner"
)

func main() {
	gologger.DefaultLogger.SetMaxLevel(-1)
	results := map[string]struct{}{}

	options := runner.Options{
		Methods:         "GET",
		Timeout:         5,
		Threads:         80,
		Silent:          true,
		RandomAgent:     true,
		Retries:         2,
		InputTargetHost: goflags.StringSlice{"scanme.sh", "projectdiscovery.io", "localhost", "x"},
		OnResult: func(r runner.Result) {
			if r.Err != nil {
				return
			}
			results[r.URL] = struct{}{}
		},
	}

	if err := options.ValidateOptions(); err != nil {
		log.Fatal(err)
	}

	httpxRunner, err := runner.New(&options)
	if err != nil {
		log.Fatal(err)
	}
	defer httpxRunner.Close()

	httpxRunner.RunEnumeration()
	fmt.Println("Results:", results)
}

```

**Comment by meme-lord** [comment]
I don't think this issue should be closed, it's still present. Users of httpx as a library shouldn't have to set the gologger level to -1 to avoid the output of each URL. Using the `Silent` option should be enough.

**Comment by dogancanbakir** [comment]
Disabling stdout while silent will affect the CLI as well. This is not the cleanest solution to the problem and should not be considered the only option. I am open to suggestions - maybe an option to disable stdout 💭. Thanks for bringing this up.

**Comment by ehsandeep** [comment]
This is now fixed in https://github.com/projectdiscovery/httpx/pull/1871
