### ISSUE TITLE
Cannot use `gophish` from outside install directory (stand-alone bin)

### ISSUE THREAD

**Issue by ocervell** [projectdiscovery/httpx#1698]
When trying to run Gophish binary from outside the main directory (by path, or symlinked), `gophish` cannot find some relative paths.

For instance, I'm untarring Gophish binaries in `~/.local/share/gophish/`.

When I run `~/.local/share/gophish/gophish`, I'm getting:
```
time="2024-05-13T06:22:15-04:00" level=fatal msg="open ./VERSION: no such file or directory"
```

But if I `cd ~/.local/share/gophish/` and run `./gophish`, it works properly.

**Comment by ehsandeep** [comment]
@ocervell looks like issue you reporting is related to `gophish` and not httpx?

**Comment by ocervell** [comment]
Oops sorry ended up on the wrong repo =D
