### ISSUE TITLE
While using list of resolver can we check specifically which resolver is used to find if website is alive or not.

### ISSUE THREAD

**Issue by iamxhunt3r** [projectdiscovery/httpx#1701]
### Please describe your feature request:

While using list of resolver can we check specifically which resolver is used to find if website is alive or not.
i can't check it with debug or verbose.

**Comment by GeorginaReeder** [comment]
Thanks so much for your feature request @iamxhunt3r , we'll look into it!

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!

**Comment by ehsandeep** [comment]
this is now exposed in jsonl output in latest release.

**Comment by iamxhunt3r** [comment]
Thanks @ehsandeep .
