### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by riramar** [projectdiscovery/httpx#1716]
![image](https://github.com/projectdiscovery/httpx/assets/6748242/9877140b-0e05-4f88-bb0f-4459c9444760)

**Comment by Sowjanya-22** [comment]
![Screenshot_2024-05-21-22-49-30-95_5899ddb6da27ff03a791c7da66eb6f4b](https://github.com/projectdiscovery/httpx/assets/137325086/3810c068-21bd-472e-9e15-bdc395bbb87b)

**Comment by Sowjanya-22** [comment]
https://www.parkqwik.com/

**Comment by ehsandeep** [comment]
this is now fixed in latest release.
