### ISSUE TITLE
Remove tech-detect info from default output to stdout

### ISSUE THREAD

**Issue by lappsec** [projectdiscovery/httpx#1730]
### Please describe your feature request:
Starting in either 1.6.1 or 1.6.2 the default output to stdout includes the info from --tech-detect. While this info is useful in certain scenarios, it goes against the streamlined integration with other tools/utilities that httpx and other projectdiscovery tools are known for. Now it's required to add the -tech-detect=false flag every time you use httpx and want to pipe the output to another tool or just copy the URL list without extra data. 

This feature request is requesting that the default output be changed back to how it was in 1.6.0 and prior, removing the tech-detect info from stdout by default and only including it when the --tech-detect flag is used. 

Here's a screenshot of an example of the behaviour pre and post upgrade
![httpx](https://github.com/projectdiscovery/httpx/assets/22598243/f6ec8758-d5f0-4532-928e-47ce86072fd2)

### Describe the use case of this feature:
I know it's a minor annoyance, but when trying to integrate httpx with other tools and workflows it makes much more sense to include the additional information only when the user requests it rather than by default.

**Comment by ehsandeep** [comment]
@lappsec we meant to enable it for JSONL / CSV output as default, not on the CLI, so this looks like bug and will be fixed / update asap, thanks for flagging.

**Comment by lappsec** [comment]
Sounds good. Thanks for the quick response!

**Comment by ehsandeep** [comment]
this is now fixed in latest release.
