### ISSUE TITLE
httpx as a lib no longer use `Resolvers` since v1.6.2

### ISSUE THREAD

**Issue by babariviere** [projectdiscovery/httpx#1734]
### httpx version:
1.6.2

### Current Behavior:
Resolvers are being called but results are not used. Looks like it uses system resolver by default.

### Expected Behavior:
Resolvers should be correctly used.

### Steps To Reproduce:

1. Download repro case and run it: https://github.com/babariviere/httpx-repro
2. It doesn't print the result
3. Change httpx version in `go.mod` to `v1.6.1`
4. `go run .`
5. Result is correctly printed

**Comment by Mzack9999** [comment]
@babariviere I think this was due to a recent internal refactor of [fastdialer](https://github.com/projectdiscovery/fastdialer) and should be fixed in the `dev` branch via https://github.com/projectdiscovery/httpx/pull/1743
