### ISSUE TITLE
CSP Probing Shouldn't Break Scope and Httpx by Default should Only Visit What the User Specifies

### ISSUE THREAD

**Issue by NotoriousRebel** [projectdiscovery/httpx#1736]
As the title states when using the csp probe options such as `-csp-probe` or `-efqdn` the default functionality of httpx should not be to see if csp domains have active web services.

For example: `httpx -u "https://github.com" -fr -csp-probe -json -efqdn -o test.json` (using current dev branch), leading to httpx visting urls such as: `https://productionresultssa19.blob.core.windows.net` which while GitHub may own it, in other cases with different places this will not always be the case. This should be an additional flag to enable this functionality because by default httpx should just visit the urls that are provided to it and nothing else. This functionality can corrupt and taint results especially if the user is not aware this is happening and is using httpx in automated solutions and just doing jq ,url for example to obtain the results and piping it into tools such as katana and crawling things that are out of scope.

A new flag such as `-csp-check` or something like that that if true will tell httpx to attempt to check for web services for any csp results it finds and adds it to the output file. By default it should be false, and while yes I could just parse the urls and check if the domain matches what I need to be to stay in whatever scope may be, I should not have to do that as httpx by default should only visit the urls/ips/hosts I tell it to and nothing else.

**Comment by NotoriousRebel** [comment]
For some additional context to make the problem more obvious if it is not, let's take that example command I provided and then  parse the output: `cat test.json | jq .url -r | sort -u`

![image](https://github.com/projectdiscovery/httpx/assets/36310667/3e79c9cf-a653-4d5c-b06f-c852b3462b75)

Ideally I would just see "https://github.com" like how httpx has functioned before.

**Comment by dogancanbakir** [comment]
As stated in the [Notes](https://github.com/projectdiscovery/httpx?tab=readme-ov-file#notes) section, this flag `-csp-probe` should be used for specific use case instead of running them as default with other probes, as it is an optional flag and not used as default.
