### ISSUE TITLE
[Bug] Missing available titles / regex improvements

### ISSUE THREAD

**Issue by rank0** [projectdiscovery/httpx#176]
example：
124.127.92.139:8088
124.127.92.139
124.127.92.139:4430

./httpx_1.0.3 -l /tmp/httptest.txt -title -content-length -status-code -silent -follow-redirects
![image](https://user-images.githubusercontent.com/25348551/102194410-3fe95580-3ef8-11eb-9079-45e21dd04eee.png)

![image](https://user-images.githubusercontent.com/25348551/102194554-6a3b1300-3ef8-11eb-916a-b48a5033b44a.png)

**Comment by bauthard** [comment]
This is fixed in this PR in `dev` branch https://github.com/projectdiscovery/httpx/pull/181

```
echo 124.127.92.139:8088 | ./httpx -title -silent
http://124.127.92.139:8088 [南京万川医药-国家电子监管码系统（Varsal SDA）]
```
