### ISSUE TITLE
Supporting Scanning List Of URLs Through List Of Proxies OR Multiple Values To Specific Header

### ISSUE THREAD

**Issue by 0xAwali** [projectdiscovery/httpx#177]
**1 - It Is Possible To Scan List Of URLs Through List Of Proxies e.g. Assuming That , There Are List Of 403 Forbidden URLs But You Can Access Them Via Specific Proxy So This Feature Can Help Us**

**2 - With The same Previous Assuming But You Can Access Them Via Specific Value To X-Forwarded-For**
 

![0003](https://user-images.githubusercontent.com/54332136/102230333-6d80cf80-3ef5-11eb-9803-3726ff61dfd5.jpg)

**Comment by team-projectdiscovery** [comment]
Hi @0xAwali, 

You can use any proxy service that rotates your requests through multiple IP's on the go, you can set up with AWS for free, additionally you can feed as much as custom header you want with `H` flag. 

For example:- 

```
echo test.com | httpx -H 'X-Forwarded-For: 1.1.1.1' -H 'X-Client-IP: 2.2.2.2'
```

We can close this issue as nothing new needs to added here.

**Comment by 0xAwali** [comment]
Thank You For Trying help Me , But You Can Not Understand Me 
I Do not need Rotate My Request I need To Scan URLs Through Different Proxies e.g. 
1 - URL Like That https://www.company.com/ , While Scan It , I Got 403 Forbidden
2 - So I need To Scan This URLs With List Of Proxies By Using httpX Tool Because There Is Misconfiguration While Configure Internal Proxies To Make It Public Instead Of Make It Private e.g.

httpx Will send a lot Of Requests To https://www.company.com/ With Using Different Proxy Every Request
https://www.company.com/      With Proxy http://internal-company.com:5050
https://www.company.com/      With Proxy http://dev-company.com:4040
...........
**It Like I am Using For Loop 
for i in `cat list-of-proxies`
do
      httpx -l hosts.txt -http-proxy $i
done**

But I Need httpX Use Different Proxy With Every Request That httpX Will Do It Then Get Response If The Proxy Is Accessible OR Use Another Proxy If timeout 


And With Custom Header , I Know I Can Use This 
echo test.com | httpx -H 'X-Forwarded-For: 1.1.1.1' -H 'X-Client-IP: 2.2.2.2'
But I need To use httpX To Scan http://ww.company.com With A lot Values Of X-Forwarded-For e.g.
httpx Will send a lot Of Requests To https://www.company.com/ With Using Different Values To X-Forwarded-For 
First Request     --->  https://www.company.com/      With    X-Forwarded-For: 127.0.0.1
second Request ---> https://www.company.com/      With    X-Forwarded-For: 87.88.88.87
...........
and httpX Will Get Response Every Request
**I Wish You Understand Me**

**Comment by 0xAwali** [comment]
Thank You For Trying help Me , Forget The Second Part There Is Someone Helped me But You Can Not Understand Me In The First Part So I Do not need Rotate My Request I need To Scan URLs Through Different Proxies e.g.
1 - URL Like That https://www.company.com/ , While Scan It , I Got 403 Forbidden
2 - So I need To Scan This URLs With List Of Proxies By Using httpX Tool Because There Is Misconfiguration While Configure Internal Proxies To Make It Public Instead Of Make It Private e.g.
httpx Will send a lot Of Requests To https://www.company.com/ With Using Different Proxy Every Request
https://www.company.com/ With Proxy http://internal-company.com:5050
https://www.company.com/ With Proxy http://dev-company.com:4040
...........
It Like I am Using For Loop
for i in cat list-of-proxies
do
httpx -l hosts.txt -http-proxy $i
done

But I Need httpX Use Different Proxy With Every Request That httpX Will Do It Then Get Response If The Proxy Is Accessible OR Use Another Proxy If timeout
**It Is Like Fuzzing The Proxy URLS**

**Comment by Mzack9999** [comment]
@0xAwali - Actually, the proxy setting is global for running instance. Therefore it should be possible to parallelize the execution via bash script (as you did) or tools like parallel. Feel free to join our discord if you want to discuss this further or need any help.
