### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by AaronChen0** [projectdiscovery/httpx#1776]
### httpx version:
v1.6.4 (latest)

### Current Behavior:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1277a97]
```

### Expected Behavior:
run without panic

### Steps To Reproduce:
```
httpx -td -u https://www.totalwar.com
```

### Anything else:
![image](https://github.com/projectdiscovery/httpx/assets/18425462/772bfe86-fec0-45db-9bdd-250aac6b24c3)

**Comment by ehsandeep** [comment]
Fixed in latest release - https://github.com/projectdiscovery/httpx/releases/tag/v1.6.5
