### ISSUE TITLE
`-ss` flag does not support custom header input with `-H` option

### ISSUE THREAD

**Issue by humblelad** [projectdiscovery/httpx#1784]
### httpx version: v1.6.5
 v1.6.5
 Yes

### Current Behavior:

Suppose I use the below command to take screenshot, the SS generated shows login page instead of for example logged in dashboard. 
httpx -l done.txt -title -status-code -H "Cookie:xyz" -mc 200 -ss

### Expected Behavior:

Ideally , since i supply cookies in headers and also get valid 200 response in the reponse back, httpx should take screenshot of that page rather than headless chromium taking screenshot of login page.

### Steps To Reproduce:

Example: steps to reproduce the behavior:
1. Run ' httpx -l done.txt -title -status-code -H "Cookie:xyz" -mc 200 -ss
where done.txt may have example.com which has logged in dashboard if we supply cookes in headers like auth token. So -ss should take screenshot of logged in view not  , login page.

**Comment by ehsandeep** [comment]
@humblelad this is now fixed in dev version with https://github.com/projectdiscovery/httpx/pull/1785 and will be part of next release, thanks for creating issue for it.
