### ISSUE TITLE
Option to disable skipping host from scan list based on error count

### ISSUE THREAD

**Issue by eyms121** [projectdiscovery/httpx#1789]
Please describe your feature request:
-nmhe, -no-mhe                   disable skipping host from scan based on errors

Describe the use case of this feature:
Can it be possible to force scan all hosts or any flag to skip-check?
It has already been implemented in Nuclei, will be useful here too.
Some hosts have long response time for non-existing endpoints, while existing ones respond quickly.
So in case i run on a big list of endpoints on the same host, the host will be skipped thus missing actual endpoints that exist.

**Comment by GeorginaReeder** [comment]
Thanks for your feature request @eyms121 , we'll take a look into this!

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!

**Comment by Mzack9999** [comment]
@eyms121 This is already possible by setting the value to zero:
```console
httpx -maxhr 0
```
