### ISSUE TITLE
Grepable output on the screenshot feature

### ISSUE THREAD

**Issue by AlessandroZ** [projectdiscovery/httpx#1831]
Hello, 

I like the "screenshot" feature, not only to have screenshots but also to have responses in plain text. However, it would be nice to have a grepable output on the txt file to be able to parse results. 

For example, right now we have: 
```
GET / HTTP/1.1
Host: xxxxxxxx
User-Agent: xxxxxxx
Accept-Charset: utf-8
Accept-Encoding: gzip

HTTP/1.1 200 OK
Connection: close
Cache-Control: private, max-age=0, no-cache, no-store
Content-Type: text/html
Pragma: no-cache

<html>
....
</html>
```
To something like meg (https://github.com/tomnomnom/meg)

```
> GET / HTTP/1.1
> Host: xxxxxxxx
> User-Agent: xxxxxxx
> Accept-Charset: utf-8
> Accept-Encoding: gzip

< HTTP/1.1 200 OK
< Connection: close
< Cache-Control: private, max-age=0, no-cache, no-store
< Content-Type: text/html
< Pragma: no-cache

<html>
....
</html>
```

I will also separate the screenshot functionality to the output text file, depending on the needs, sometimes the screenshot is not necessary. 

Thank you again for your great work !!

Have a nice day.

**Comment by GeorginaReeder** [comment]
Thanks for your suggestion @AlessandroZ , we'll take a look into this!

**Comment by dogancanbakir** [comment]
@AlessandroZ, Can you provide some use cases to help us understand why this would be better - and the current output isn't? Thanks!

**Comment by dogancanbakir** [comment]
I'm interested, and that's why I'm asking these questions to better understand the problem. There's a flag that can provide you with response headers. Please let me know if that will solve the problem. If not, we can discuss whether adding this is necessary. The flag:

```console
$ httpx -u scanme.sh -silent -j -irh | jq .header
{
  "content_length": "2",
  "content_type": "text/plain; charset=utf-8",
  "date": "Mon, 22 Jul 2024 08:43:49 GMT"
}
```

**Comment by AlessandroZ** [comment]
Hi, yes I didn't know this feature. Sorry to miss it. 
It could do the job. 

Thank you for your help.
