### ISSUE TITLE
Stats (scan progress) doesn't properly calculate hosts/percentage when there are multiple probe paths 

### ISSUE THREAD

**Issue by hourianto** [projectdiscovery/httpx#1841]
### httpx version:
1.6.6

### Current Behavior:
If you provide multiple paths with `-path probe_paths.txt` when scanning, httpx will misreport progress:
```
[0:47:55] | RPS: 0 | Requests: 572528 | Hosts: 332392/41549 (800%)
```
In this case it's 800% because my `probe_paths.txt` has 8 paths.

### Expected Behavior:
Stats calculation should take the amount of paths into the account when calculating Hosts and progress percentage.

### Steps To Reproduce:
Start any httpx scan with `-path probe_paths.txt -stats` with probe_paths.txt containing more than 1 path.

**Comment by ehsandeep** [comment]
This is now fixed in latest release - https://github.com/projectdiscovery/httpx/releases/tag/v1.6.8
