### ISSUE TITLE
Broken output after updating to 1.6.7.

### ISSUE THREAD

**Issue by KarahanGuner** [projectdiscovery/httpx#1858]
### httpx version:
1.6.7

### Current Behavior:
When I pipe an input file into Httpx, and write its output to another file like this:
```cat domains.txt | httpx > httpxresults.txt```
There are empty lines at the beginning of the output file:
domainst.txt:
```
example.com
test.com
hackerone.com
bugcrowd.com
```
httpxresults.txt:
```



https://hackerone.com
https://example.com
https://bugcrowd.com
```

### Expected Behavior:
httpxresults.txt file should look like this:
```
https://hackerone.com
https://example.com
https://bugcrowd.com
```

### Steps To Reproduce:
Create the input file I mentioned before run the command I provided.

### Anything else:
- This behaviour started happening after updating to this version.
- This behaviour is not happening in the -silent mode.
- There was a problem with Nuclei's output in its latest version also but I dont know if the root cause is the same.
- It used to be that after the scan is finished, it would create a new line. Now it doesnt do that. This doesnt affect me but I thought it might help to solve the problem. 
![image](https://github.com/user-attachments/assets/62817160-5d46-4d09-95e3-764840fee63d)

**Comment by KarahanGuner** [comment]
I looked through my command history and I think the last time I had updated Httpx was around 2024-07-19 . That version was working fine. Today I updated it again and the problem started. I hope this helps you pinpoint the problem.

**Comment by ehsandeep** [comment]
This is now fixed in latest release - https://github.com/projectdiscovery/httpx/releases/tag/v1.6.8
