### ISSUE TITLE
ztls not work

### ISSUE THREAD

**Issue by iuliu8899** [projectdiscovery/httpx#1859]
### Current Behavior:
![image](https://github.com/user-attachments/assets/f0877dd6-cb5f-4bc5-9583-79e54c24d1d1)

### Expected Behavior:

it seems the r.Request.Context() done when DialTLS ing. 
https://github.com/projectdiscovery/httpx/blob/5f8e5d0dc5df536fec7cc6189a3e54a6d3a9e60e/common/httpx/tls.go#L65-L68

### Steps To Reproduce:

```
httpx -u google.com -ztls -tls-grab -json -silent | jq .tls
```

### Anything else:

btw, TLSGrab func (not ZTLSGrab) does not set Serial number of the cert...

**Comment by ehsandeep** [comment]
This is now fixed in latest release - https://github.com/projectdiscovery/httpx/releases/tag/v1.6.8
