### ISSUE TITLE
Getting vhosts out of an IP

### ISSUE THREAD

**Issue by adon90** [projectdiscovery/httpx#186]
Hello, I am using this command:

```mapcidr -cidr CIDR -silent | httpx -vhost -cname --follow-host-redirects -content-type -web-server -silent  -status-code```

It works like a charm but the thing is I don't happen to get any virtualhost, when, I can see in sources like hackertarget or virustotal (with the free) that there are virtual hosts (then I do host and check it really belongs to that IP)

So my question is, what I am doing wrong, or, what sources are you using to get vhosts out of an IP?

![httpx](https://user-images.githubusercontent.com/7115563/104106649-23e69300-52af-11eb-97ac-b1a0ac767856.png)

Regards!

**Comment by bauthard** [comment]
Hey, httpx determine `vhost` based on the following conditions:-https://github.com/projectdiscovery/httpx/blob/41a6ed4fe15967c78a1c28afa4e0d3f00b1a5bde/common/httpx/virtualhost.go#L13

**Comment by Mzack9999** [comment]
@adon90 - Thanks for opening the issue. As you can see in the linked code, the vhost check is done by requesting a non-existing page and comparing the result with the specified value. We are already planning an improvement to the algorithm for the next releases. If you have any suggestions to improve the detection, we are happy to hear about it and see how we can help.

I'm closing the issue for now as no immediate pull requests are going to be opened.
