### ISSUE TITLE
Wildcard filtering

### ISSUE THREAD

**Issue by shelld3v** [projectdiscovery/httpx#187]
`-wildcard`: *Filter wildcard responses*
**Workflow**:
- Send a test request to `http://example.com/randomstring`: content-length=1234
- Send the request with the path to check: `http://example.com/path/from/user`: content-length=1234
- If content lengths from 2 requests are the same (1234==1234): Don't print it, filter it!!

**Comment by bauthard** [comment]
Hi @shelld3v, 

Nuclei fits better for this, you can use DSL matcher and compare multiple requests as well, closing this issue as this is out of scope for the httpx.
