### ISSUE TITLE
Filter responses by title

### ISSUE THREAD

**Issue by shelld3v** [projectdiscovery/httpx#188]
Hi, currently, I am mapping Yahoo hosts through IP ranges. And a lot of hosts have the title: `Yahoo`. Those hosts aren't working anymore, and I really need to filter them! I can't do it with `-fl`, because a lot of the responses have the content length close to the length I tried to filter, but did not 100% match!

So a suggestion: `-ft` (filter by title)

**Comment by bauthard** [comment]
Hi @shelld3v, 

httpx already support `filter-string` and `match-string` for this.


filter-string | Filter results based on filtered string | httpx -filter-string XXX
-- | -- | --
match-string | Filter results based on matched string | httpx -match-string XXX

**Comment by shelld3v** [comment]
I can't use `filter-string`, because it will filter any response that contains the word `Yahoo`, but I need to filter that word in the title. And even the title contains `Yahoo`, that does not mean I want to filter that, `Yahoo - 403 Forbidden` is a thing. But `Yahoo` only, isn't!

**Comment by bauthard** [comment]
Hey @shelld3v, you can use any pattern, and not just string, for example, `<title> Yahoo! </title>` or any pattern you want, if you are looking for more advanced use cases, httpx also support, regex-based filter and match, unfortunately, we can not add filters for all flags.


filter-regex | Filter results based on filtered regex | httpx -filter-regex XXX
-- | -- | --
match-regex | Filter results based on matched regex | httpx -match-regex XXX

**Comment by shelld3v** [comment]
That made a lot of senses 👍
