### ISSUE TITLE
Failed to upload scan results on cloud

### ISSUE THREAD

**Issue by ipsecc** [projectdiscovery/httpx#1890]
### Steps To Reproduce:
Got status code 504
```
./httpx -u www.example.com

[INF] To view results in UI dashboard, visit https://cloud.projectdiscovery.io/assets upon completion.
[ERR] Failed to upload scan results on cloud: [:RUNTIME] could not upload chunk <- could not upload results got status code 504 on https://api.projectdiscovery.io/v1/assets/xxxx/contents?arch=amd64&go_version=go1.21.12&machine_id=xxxx&os=kali&utm_source=unknown&v=v1.6.8
```
![image](https://github.com/user-attachments/assets/13a4bc47-fd57-4dc8-8755-8280b1b26b57)

Keeps loading but gets nothing
![image](https://github.com/user-attachments/assets/fa755954-5274-4bae-9500-49aca60653f7)

### Anything else:
Maybe it's better to let users deploy locally for a stable upload experience

**Comment by ehsandeep** [comment]
@ipsecc we had issue with service and now it is resovled.

**Comment by ipsecc** [comment]
thanks
