### ISSUE TITLE
add option to load credentials from command

### ISSUE THREAD

**Issue by marz-hunter** [projectdiscovery/httpx#1905]
please add an option to load credentials from the command, for example -credential /path/to/credentials.yaml

default when using httpx -auth credentials will be automatically saved in /root/.pdcp/credentials.yaml

**Comment by GeorginaReeder** [comment]
Thanks for your feature request @marz-hunter , we'll take a look into this!

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!
