### ISSUE TITLE
getting both http and https

### ISSUE THREAD

**Issue by blackpungas** [projectdiscovery/httpx#191]
Hi there how are you doing?

Im trying to print both http and https when enable, for instance:

```
echo 'google.com' | httpx no-fallback
```
should give me

```
https://google.com
http://google.com
```
right?, according to the docs:
```
For printing both HTTP/HTTPS results, no-fallback flag can be used.
```

but im not getting that result, im I missing something?

**Comment by ehsandeep** [comment]
@blackpungas you are missing an additional `-` in front of the flag.

```
echo 'google.com' | httpx -no-fallback
```

**Comment by blackpungas** [comment]
oh god lord, sorry for this, had an old version, sorry guys

**Comment by ehsandeep** [comment]
np :)
