### ISSUE TITLE
Feature Request: Add Native WebSocket Support to HTTPX

### ISSUE THREAD

**Issue by FrameworkPython** [projectdiscovery/httpx#1916]
Hello,It would be great if HTTPX could natively support WebSockets. As modern web applications increasingly rely on real-time communication, having built-in WebSocket support would make HTTPX a more complete solution for both HTTP and WebSocket-based interactions. This feature would eliminate the need for developers to use separate libraries like websockets or aiohttp alongside HTTPX, providing a more seamless experience. Is this something that could be considered for future releases?

**Comment by dogancanbakir** [comment]
nux.gg/wrong-httpx
