### ISSUE TITLE
-ASN and Apikey / file

### ISSUE THREAD

**Issue by hastalamuerte** [projectdiscovery/httpx#1982]
Hello. 
Httpx now not showing an ASN in output. It was broken a lot of time seems in mine framework ( Glad that found it, even late .

Can you tell plz why now httpx not work with -asn flag? cause in output now there is just ping results. 
If it need a API key - how can i use flags 
  -auth                           configure projectdiscovery cloud (pdcp) api key (default true)
   -ac, -auth-config string        configure projectdiscovery cloud (pdcp) api key credential file

-if i use just -auth it ask me a key (but its not good idea, cause httpx in mine needs should work silently without any asking. 
-ac -  where is file describition? how it should look like? why there is nothing in readme (( ? 

can you plz tell how to hardcore a key into httpx, or how to create (wich format [] stings etc ) Api key file? 

And the main question is there is now a limit on requests on free api key on httpx?
thanks

**Comment by dogancanbakir** [comment]
Couldn't repro,
```console
go run . -u scanme.sh -asn

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/

                projectdiscovery.io

[INF] Current httpx version v1.6.9 (latest)
[WRN] UI Dashboard is disabled, Use -dashboard option to enable
https://scanme.sh [AS14061, digitalocean-asn, US]
```

Could you share the command you're using and the output you're not expecting?

**Comment by hastalamuerte** [comment]
![Image](https://github.com/user-attachments/assets/2c628a74-58cc-4a53-bbeb-958dcc17f44d)
Maybe it will be user friendly to print some example of usage in Readme or Wiki
https://docs.projectdiscovery.io/tools/httpx/usage
Cause in that pages there is even NO such option

**Comment by dogancanbakir** [comment]
@hastalamuerte Instead of `-auth` for a more interactive approach, you can use the `-ac` flag to specify the file.  If you use `-auth` to configure API Key, all the settings will be saved in $HOME/.pdcp/credentials.yaml. I'll add an example:

```yaml
- username: <USER>
  email: <MAIL>
  api-key: <API_KEY>
  server: https://api.projectdiscovery.io

```

Ref: https://github.com/projectdiscovery/httpx/issues/1905

Closing this. Feel free to reopen if you have further questions.

**Comment by hastalamuerte** [comment]
![Image](https://github.com/user-attachments/assets/b7441f4e-6726-4eda-a756-fbb1df7130e6)

**Comment by hastalamuerte** [comment]
Guys, thanks for you software and products, but those new Auth options , made it unusable.

**Comment by dogancanbakir** [comment]
@hastalamuerte Thank you for your patience. Let me take another look at this and explore our options.

**Comment by hastalamuerte** [comment]
> [@hastalamuerte](https://github.com/hastalamuerte) Thank you for your patience. Let me take another look at this and explore our options.

![Image](https://github.com/user-attachments/assets/375f7ce4-8e82-4a19-bc5e-ffd105ee38fa)
Thank you a lot. 
Honestly it drive me crazy - i  just want to get asn's like it was many years before))
Even if i  successfully login . i cant get results. 
Plz just add some option to provide key in command line and it will not only Logg you, but also made a work wich was setted in other parameters


and plz tell is there some limits for asn requests in free key? (or maybe its time to swtich for some another cloudresolvers)

**Comment by hastalamuerte** [comment]
@dogancanbakir Best regards. Seems it now work as previous. Asn is available , like in good old days. 
Have a nice day! And thanks for you ProjectDiscovery tools!
