### ISSUE TITLE
SkipVerify or Verify TLS

### ISSUE THREAD

**Issue by APT-ZERO** [projectdiscovery/httpx#1988]
Option to set if client must validate server's TLS certificate or ignore it and complete the request
for example when client's TLS SNI does not match the server's ssl cert

**Comment by Mzack9999** [comment]
@APT-ZERO httpx by default use `InsecureSkipVerify: true` to maximize connections success. You might want to have a look at https://github.com/projectdiscovery/tlsx if you are looking for more specific tls checks

**Comment by ehsandeep** [comment]
@APT-ZERO SkipVerify is enabled default, so you don't need option to enable it, do you example where you noticed error because of SkipVerify check? can you share example host?
