### ISSUE TITLE
 httpx -silent | Usage: httpx [OPTIONS] URL | Error: No such option: -s

### ISSUE THREAD

**Issue by hack-test-acc** [projectdiscovery/httpx#1996]
Backward Compatibility Concerns with Recent httpx Updates

Users report that the -silent flag is no longer recognized, disrupting workflows that rely on this option to suppress extra output:

waybackurls domain.com | grep "\.js" | httpx -silent

Error Message: Error: Usage: httpx [OPTIONS] URL
Error: No such option: -s

![Image](https://github.com/user-attachments/assets/f92e5bc2-bea8-4f47-8e3c-4e837e1ad1b9)

**Comment by dogancanbakir** [comment]
nux.gg/wrong-httpx
