### ISSUE TITLE
CustomIP setting in context not effective in dial function

### ISSUE THREAD

**Issue by Explorer1092** [projectdiscovery/httpx#2003]
httpx version:

1.6.9

Current Behavior:
The CustomIP setting, when provided, is supposed to be used in the dial function of the fastdialer package to direct connection attempts to a custom IP address. However, the actual implementation in dialer.go does not utilize the CustomIP provided via context. This leads to the CustomIP not being used during the dialing process, which defaults to the standard IP resolution.

Expected Behavior:
When CustomIP is set, the dial function should recognize and use this custom IP for the connection, overriding the standard DNS resolution process. This behavior is expected as part of the functionality described in dialer_private.go.

Steps To Reproduce:
Set CustomIP in a target configuration.
Initiate dialing through the fastdialer's dial function.
Observe that the connection does not use the CustomIP but follows standard DNS resolution.
```
if target.CustomIP != "" {
	var requestIP string
	if iputil.IsIPv6(target.CustomIP) {
		requestIP = fmt.Sprintf("[%s]", target.CustomIP)
	} else {
		requestIP = target.CustomIP
	}
	ctx = context.WithValue(context.Background(), fastdialer.IP, requestIP)
} else {
	ctx = context.Background()
}
```
Suggested Fix:
Ensure that the dial function properly checks for CustomIP from the context and uses it. If the implementation for handling CustomIP is supposed to be in dialer_private.go, then there might be a discrepancy or an import error. Please verify if the function in dialer_private.go is correctly linked and utilized in dialer.go.

Anything else:
I have verified that the latest version of the package is being used.
No relevant errors were visible in the logs, indicating that the CustomIP is silently ignored.
Reference to the functionality can be found here: [fastdialer/dialer_private.go](https://github.com/projectdiscovery/fastdialer/blob/v0.2.9/fastdialer/dialer_private.go)
This issue might require a review of how context values are passed and utilized within the dial process, or a clarification in the documentation if the current implementation differs from expected behavior.

**Comment by Mzack9999** [comment]
Automatically fixed upon next fastdialer auto-release
