### ISSUE TITLE
Client/QueryParams always percent-encodes '+' (plus sign)

### ISSUE THREAD

**Issue by innovimia-cto** [projectdiscovery/httpx#2006]
### Current Behavior:
When trying to pass a query string in the form of 'q=x+y+z', the parameters are always percent-encoded like 'q=x%20y%20z'. I'm trying to call an API endpoint which needs the query params with space to be specified with '+' sign (quote_plus() behaviour) but instead everything is percent encoded. I've found the issue to be in the line 485+ of the _urlparse.py library file:

```
def urlencode(items: list[tuple[str, str]]) -> str:
    """
    We can use a much simpler version of the stdlib urlencode here because
    we don't need to handle a bunch of different typing cases, such as bytes vs str.

    https://github.com/python/cpython/blob/b2f7b2ef0b5421e01efb8c7bee2ef95d3bab77eb/Lib/urllib/parse.py#L926

    Note that we use '%20' encoding for spaces. and '%2F  for '/'.
    This is slightly different than `requests`, but is the behaviour that browsers use.

    See
    - https://github.com/encode/httpx/issues/2536
    - https://github.com/encode/httpx/issues/2721
    - https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode
    """
    return "&".join(
        [
            percent_encoded(k, safe="") + "=" + percent_encoded(v, safe="")
            for k, v in items
        ]
    )

```
 It always encodes all the keys and values and the 'safe' parameters is hard-coded to be "", meaning it encodes all the characters.

### Expected Behavior:
I need a mechanism to prevent encoding '+' in the query parameters.

### Steps To Reproduce:

```
from httpx import QueryParams

p = { 'q': 'x+y+z' }
print(QueryParams(p))

#  'q=x%20y%20z'
```

### Anything else:
NA

**Comment by ehsandeep** [comment]
@innovimia-cto you might be referring to https://github.com/encode/httpx/issues

**Comment by innovimia-cto** [comment]
Thanks! Sorry for the confusion!
