### ISSUE TITLE
0.28.0 doesn't send client side certificates.

### ISSUE THREAD

**Issue by davidgroves** [projectdiscovery/httpx#2023]
### Steps To Reproduce:

```
client = httpx.Client(cert=("foo", "bar"))
client.get("https://some.url/")
```

Works on 0.27.2, doesn't send certificate on 0.28.0.

Bug was found in a restricted environment, will need to reproduce outside it to give more detail.

**Comment by dogancanbakir** [comment]
nux.gg/wrong-httpx
