### ISSUE TITLE
HTTP header information customization

### ISSUE THREAD

**Issue by superboy-zjc** [projectdiscovery/httpx#206]
Is it possible to increase the function of custom HTTP headers?Some web services will reject client requests that lack specific HTTP headers. Such as User-Agent.

**Comment by ehsandeep** [comment]
@superboy-zjc you can add / update any header using `-H` flag, for example, `httpx -H 'User-Agent: Hacker'`

**Comment by superboy-zjc** [comment]
> @superboy-zjc you can add / update any header using `-H` flag, for example, `httpx -H 'User-Agent: Hacker'`
Sorry, it's my mistake. hh....

**Comment by ehsandeep** [comment]
Np, closing the issue!
