### ISSUE TITLE
Filter results by the header

### ISSUE THREAD

**Issue by vipinbihari** [projectdiscovery/httpx#208]
There is no way to filter the url based on the content-type returned by the server. I a simple way can we have match and filter strings based on header of a response.

**Comment by ehsandeep** [comment]
I see **httpx** already supports using the below flags, do you have any example which is not covered?

Match:- `echo https://example.com | httpx -silent -filter-string text/html`
Filter:- `echo https://example.com | httpx -silent -match-string text/html`
