### ISSUE TITLE
httpx always stuck at the end 

### ISSUE THREAD

**Issue by FuckAllWorld** [projectdiscovery/httpx#213]
httpx always stuck at the end 

I always encounter situations like this... :-(

version v1.0.3

**Comment by ehsandeep** [comment]
@FuckAllWorld do you have a list or something you can share to replicate this on the discord server?

**Comment by FuckAllWorld** [comment]
i send mail for you , email address ?

**Comment by FuckAllWorld** [comment]
@ehsandeep i send mail for you , email address ?

**Comment by ehsandeep** [comment]
Sure, please send an email with the list to `contact@projectdiscovery.io`

**Comment by FuckAllWorld** [comment]
@ehsandeep done. wait for your reply

**Comment by ehsandeep** [comment]
Replied to the email, manage to complete the scan on the shared input list, as this is not a bug with httpx, closing this issue now.
