### ISSUE TITLE
[Feature] Show final URL if --follow-redirects is used

### ISSUE THREAD

**Issue by JoshuaMart** [projectdiscovery/httpx#215]
Hello,
It would be interesting I think to display the final URL when the `--follow-redirects` option is used.

For example if I use httpx on the domain google.com, there will be a redirection to https://www.google.com
![httpx](https://user-images.githubusercontent.com/17493961/112040715-d6579380-8b45-11eb-8df2-8e8b05aa98b8.png)

As it is, if I use another tool behind it such as nuclei, the requests will not be made on the right URL
![nuclei](https://user-images.githubusercontent.com/17493961/112041039-32bab300-8b46-11eb-8050-afa1ad457d7b.png)

Thank's

**Comment by ehsandeep** [comment]
Hi @JoshuaMart, 

Thanks for opening an issue for this, what you suggested here will result in many unexpected behaviors in general and for nuclei as input as well, as with `-follow-redirects` the final URL could lead to `hxxp://www.test.com/test/some_url` which is not expected input for the nuclei and also unrelated URLs which is also not expected when you probing for subs for the target domain, closing this issue as no changes required here.

**Comment by ehsandeep** [comment]
And here is how it will look like in CLI and the same can be exposed in JSON as well.

```bash
echo https://apps.tesla.com | httpx -silent -follow-redirects

https://apps.tesla.com [https://mobile.tesla.com/appstore/account/username?ReturnUrl=%2Fappstore%2F]
```

**Comment by ehsandeep** [comment]
@JoshuaMart this is now added into development version https://github.com/projectdiscovery/httpx/pull/267#issuecomment-835776631

**Comment by JoshuaMart** [comment]
Cool, Thank's @ehsandeep :)

**Comment by ehsandeep** [comment]
@JoshuaMart this is now live in the latest release of [httpx](https://github.com/projectdiscovery/httpx/releases/tag/v1.0.7)
