### ISSUE TITLE
Incorrect parsing of title tag when newlines occur

### ISSUE THREAD

**Issue by thapr0digy** [projectdiscovery/httpx#216]
I noticed while running a scan on a host that if the <title> tag has a newline in it, httpx will not grab the entire string inside of the tag. 

Example would be a title tag with this:
```
<title>
		My Title		</title>
```

It then produces an empty title when using the -title option. It would be nice to have this work based on what's inside the entire tag.

**Comment by ehsandeep** [comment]
Hi @thapr0digy, thanks for opening an issue for this, in the past, we identified multiple edge cases to extract the titles and after a point, we added support for `-match-regex` to write custom regex but looks like either we can extend this flag to print the values or have another flag to print the matched regex.

**Comment by ehsandeep** [comment]
@thapr0digy This works with the [latest](https://github.com/projectdiscovery/httpx/releases/tag/v1.0.5) version of httpx.

```html
cat index.html 
<title>
		My Title		</title>
```

```bash
echo http://0.0.0.0:8000 | httpx -title

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.0.5

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
http://0.0.0.0:8000 [My Title]
```
