### ISSUE TITLE
read: connection reset by peer

### ISSUE THREAD

**Issue by AkunWin** [projectdiscovery/httpx#218]
[FTL] Could not create httpx instance: Could not create cdn check: Get "https://www.cloudflare.com/ips-v4": read tcp 172.168.88.2:5678->104.16.123.96:443: read: connection reset by peer

**Comment by ehsandeep** [comment]
@AkunWin this was fixed in last release https://github.com/projectdiscovery/httpx/releases/tag/v1.0.3, make you are you are using latest version of httpx

**Comment by AkunWin** [comment]
> @AkunWin这已在最新版本[https://github.com/projectdiscovery/httpx/releases/tag/v1.0.3中](https://github.com/projectdiscovery/httpx/releases/tag/v1.0.3)修复，使您使用的是最新版本的httpx

thanks~

**Comment by ehsandeep** [comment]
Closing as this is resovled.
