### ISSUE TITLE
output is not grab-able using grep

### ISSUE THREAD

**Issue by Sy3Omda** [projectdiscovery/httpx#23]
when either using -o for store output or even pipe the output using | tee blah
the output result is just appear normal in bash but if u open it using text editor you will find it 
unicoded and not grab-able using grep later if i want to filter certain response code

**Comment by bauthard** [comment]
```bash
> chaos -d hackerone.com -silent | httpx -silent -status-code | tee ttt
https://docs.hackerone.com [200]
https://mta-sts.forwarding.hackerone.com [404]
https://api.hackerone.com [200]
https://support.hackerone.com [301]
https://resources.hackerone.com [301]
https://mta-sts.managed.hackerone.com [404]
https://mta-sts.hackerone.com [404]
https://www.hackerone.com [200]
```

```bash
> cat ttt | grep 404
https://mta-sts.forwarding.hackerone.com [404]
https://mta-sts.managed.hackerone.com [404]
https://mta-sts.hackerone.com [404]
```

Looks good here, can you share examples showing the issue?

**Comment by Sy3Omda** [comment]
nop i need to grep [200] as escaped chars because some times the link is containing the same number so i need to escape the whole block [200] OR [403] OR [302]

**Comment by bauthard** [comment]
Please use `-json` flag if you want to filter data as suggested here https://github.com/projectdiscovery/httpx/issues/7, the terminal output is not grep friendly.

**Comment by bauthard** [comment]
Hi @Sy3Omda, 

I see what you mean, this is a bug and we will get it fixed, thanks for pointing this out.

**Comment by bauthard** [comment]
Hi @Sy3Omda, 

This is because you were using colored output, if you want clean output with grep support, use `-no-color` flag with your command.
