### ISSUE TITLE
[Feature] Filter identical hosts.

### ISSUE THREAD

**Issue by celsec** [projectdiscovery/httpx#238]
It would be nice for httpx to have an option where it would hash the contents of a host and filter equal hosts so they are not given in the output.

**Comment by ehsandeep** [comment]
Hi @celsec, 

httpx already have `body-sha256` and `header-sha256` for response body and header with JSON output, you can achieve the same based on those hashes, but this requires post-processing and that's not something we should be adding withing httpx and doing it at run time, closing this issue, thanks for the idea but unfortunately, this is out of scope for httpx.
