### ISSUE TITLE
你好，像（http://target.com:8080）这种格式会获取不到网站标题

### ISSUE THREAD

**Issue by AkunWin** [projectdiscovery/httpx#240]
你好，像（http://target.com:8080）这种格式会获取不到网站标题

**Comment by ehsandeep** [comment]
@AkunWin do you have an example to share?

**Comment by ehsandeep** [comment]
@AkunWin it works, looks like an issue with the host you are probing, closing as this is not an issue.

```
echo http://zen.ly:8080 | httpx -silent -title
http://zen.ly:8080 [Error 404 (Not Found)!!1]
```
