### ISSUE TITLE
Support for full HTML grabbing?

### ISSUE THREAD

**Issue by RiversideRocks** [projectdiscovery/httpx#257]
I'd love to use this to collect HTML from many websites, is there an option to do that as of now?

**Comment by ehsandeep** [comment]
@RiversideRocks `-sr` flag to save the HTTP response.

**Comment by RiversideRocks** [comment]
That only seems to save headers and not HTML content.

**Comment by Mzack9999** [comment]
@RiversideRocks Probably you need to use also `-include-response`

**Comment by RiversideRocks** [comment]
That works, thanks.
