### ISSUE TITLE
[Feature] Support for more output format CSV/HTML

### ISSUE THREAD

**Issue by cyal1** [projectdiscovery/httpx#270]
## Description:-

Currently httpx support `plain` and `JSON` output format and we can add the followings

- CSV
- HTML

Additional flag support (`output-format`) to specify output formats + signal or multiple format support.

```
httpx -l subs.txt -output httpx => Plain output saved to httpx
httpx -l subs.txt -output httpx -json => JSON output saved to httpx
httpx -l subs.txt -output httpx -output-format plain => Plain output saved to httpx
httpx -l subs.txt -output httpx -output-format plain,csv,json,html  => Output saved to `httpx`, `httpx.csv`,`httpx.json`,`httpx.html` 
```

------

add flag `-o -html`, output  the follow html results
![image](https://user-images.githubusercontent.com/33282478/117901619-4987b580-b2fe-11eb-8a41-6f2a9dc71398.png)

**Comment by nvdadt** [comment]
what's the actual command to get the output in html file like show above ?
echo https://lapp.corp.vipshop.com:8443/core | httpx -status-code -title -silent -o 1.html
i get output like this 
![image](https://user-images.githubusercontent.com/15017281/121770328-552cfd00-cb86-11eb-926e-43952195871c.png)

**Comment by cyal1** [comment]
> what's the actual command to get the output in html file like show above ?
> `echo https://lapp.corp.vipshop.com:8443/core | httpx -status-code -title -silent -o 1.html`
> i get output like this
> ![image](https://user-images.githubusercontent.com/15017281/121770328-552cfd00-cb86-11eb-926e-43952195871c.png)

That is my modified version in my repositories https://github.com/cyal1/httpx/tree/master/cmd/httpx

**Comment by nvdadt** [comment]
> > what's the actual command to get the output in html file like show above ?
> > `echo https://lapp.corp.vipshop.com:8443/core | httpx -status-code -title -silent -o 1.html`
> > i get output like this
> > ![image](https://user-images.githubusercontent.com/15017281/121770328-552cfd00-cb86-11eb-926e-43952195871c.png)
> 
> That is my modified version in my repositories https://github.com/cyal1/httpx/tree/master/cmd/httpx

How do I make use of this later modification ? Should need to install latest build from your repo ?

**Comment by cyal1** [comment]
> > > what's the actual command to get the output in html file like show above ?
> > > `echo https://lapp.corp.vipshop.com:8443/core | httpx -status-code -title -silent -o 1.html`
> > > i get output like this
> > > ![image](https://user-images.githubusercontent.com/15017281/121770328-552cfd00-cb86-11eb-926e-43952195871c.png)
> > 
> > 
> > That is my modified version in my repositories https://github.com/cyal1/httpx/tree/master/cmd/httpx
> 
> How do I make use of this latest modification ? Should need to install latest build from your repo ?

You need to compile it yourself, or download my compiled program here: https://github.com/cyal1/httpx/tree/master/cmd/httpx

**Comment by KingOfBugbounty** [comment]
Hy team! I am and my Friend [@gustavorobertux](https://github.com/gustavorobertux) we developed a tool that makes the conversion..

![image](https://github.com/user-attachments/assets/f466983c-be90-44d9-96a8-f7fdd74fcfc1)

![image](https://github.com/user-attachments/assets/85971194-0b45-4d0e-b637-aba4ca1f82fe)

tool = https://github.com/KingOfBugbounty/KingOfBugBountyTips/blob/master/resolvhtml.go
