### ISSUE TITLE
[Issue] Default http protocol being used when proxy mode is enabled

### ISSUE THREAD

**Issue by 0x0msg** [projectdiscovery/httpx#274]
Version: 1.0.6

A file already having the domains with https in url is overridden with http when using -http-proxy mode

![image](https://user-images.githubusercontent.com/59406891/118361500-5d0a7900-b5a9-11eb-9604-fae3c283a5a3.png)
![image](https://user-images.githubusercontent.com/59406891/118361587-c4282d80-b5a9-11eb-8963-c66513bd2fdc.png)
 Tried AWK as well but same issue
cat JS | awk -F "//"  '{print$2}' | httpx -http-proxy http://host:port

**Comment by ehsandeep** [comment]
```sh
# No proxy

$ echo engage.tesla.com | httpx -silent
https://engage.tesla.com

# With Porxy

$ echo engage.tesla.com | httpx -silent -http-proxy http://127.0.0.1:8080
http://engage.tesla.com

```

**Comment by Mzack9999** [comment]
* Potentially related to https://github.com/projectdiscovery/nuclei/issues/709
* Tracked at https://github.com/projectdiscovery/retryablehttp-go/issues/2

**Comment by ehsandeep** [comment]
@0x0msg thanks for reporting, this is now supported in the latest release of [httpx v1.0.7](https://github.com/projectdiscovery/httpx/releases/tag/v1.0.7)
