### ISSUE TITLE
[Feature] Support the "new" 307 & 308 status codes for redirect

### ISSUE THREAD

**Issue by stigkj** [projectdiscovery/httpx#280]
It would be nice if the `-follow-redirects` and `-follow-host-redirects` would support the 307 & 308 status codes for redirect.

**Comment by ehsandeep** [comment]
Here is an example that shows httpx currently doesn't follow 307,308 redirects.

```bash
echo https://toolbox-beta.tesla.com | httpx -silent -status-code -follow-redirects

https://toolbox-beta.tesla.com [307]
```

**Comment by ehsandeep** [comment]
@stigkj, thanks for suggesting this, this is now supported in the latest release of [httpx v1.0.7](https://github.com/projectdiscovery/httpx/releases/tag/v1.0.7)
