### ISSUE TITLE
[Issue] - Go: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by nikammarafiy** [projectdiscovery/httpx#290]
Received an error below when running the command:

>panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x887433]
goroutine 26 [running]:
github.com/projectdiscovery/httpx/runner.(*Runner).analyze(0xc0001a2240, 0xc0000714a0, 0x98191a, 0xa, 0xc00186e060, 0x12, 0x97bbce, 0x3, 0xc0001a2258, 0x0, ...)
	/home/nxxx/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.8/runner/runner.go:555 +0x173
github.com/projectdiscovery/httpx/runner.(*Runner).process.func1(0xc000062140, 0xc0001a2240, 0xc0000714a0, 0xc0001a2258, 0xc000be5ec0, 0xc00186e060, 0x12, 0x97bbce, 0x3, 0x98191a, ...)
	/home/nxxx/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.8/runner/runner.go:463 +0xe5
created by github.com/projectdiscovery/httpx/runner.(*Runner).process
	/home/nxxx/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.8/runner/runner.go:461 +0x54a

**Comment by ehsandeep** [comment]
@nikammarafiy thanks for reporting, do you have an example cmd to reproduce this?

**Comment by nikammarafiy** [comment]
httpx -l /nxxx/urllist.txt -no-fallback -o /nxxx/result.txt

**Comment by nikammarafiy** [comment]
> @nikammarafiy thanks for reporting, do you have an example cmd to reproduce this?

Example cmd below:

> httpx -l /nxxx/urllist.txt -no-fallback -o /nxxx/result.txt

**Comment by Krosskid12** [comment]
![Uploading image.png…]()

hii i have got same error

**Comment by Krosskid12** [comment]
> @nikammarafiy thanks for reporting, do you have an example cmd to reproduce this?
![image](https://user-images.githubusercontent.com/73221787/120060488-ede85680-c077-11eb-9988-88159b5465f7.png)
Hiii i have got same error

**Comment by ehsandeep** [comment]
@nikammarafiy @Krosskid12 this is now fixed in the latest release.

**Comment by nikammarafiy** [comment]
t

> @nikammarafiy @Krosskid12 this is now fixed in the latest release.

thank you @ehsandeep
