### ISSUE TITLE
Return annotation of `response.json()`

### ISSUE THREAD

**Issue by jonathanslenders** [projectdiscovery/httpx#298]
Right now, the function signature of ``response.json()`` returns ``Any``.

The issue with this is that mypy won't complain when we write:
```python
data = await response.json()
```
The result is not awaitable. This is common however, when migrating from other HTTP clients like aiohttp.

Ideally, I'd like the return type to be something like this:
```python
-> Union[str, int, dict, list]
```

I'm not sure whether that's feasible.

**Comment by Mzack9999** [comment]
@jonathanslenders may it be possible that this issue was meant for https://github.com/encode/httpx ?

**Comment by jonathanslenders** [comment]
It was, thanks for pointing out!
