### ISSUE TITLE
Request time out / rate limit support

### ISSUE THREAD

**Issue by blackpungas** [projectdiscovery/httpx#315]
Hi there,

Im using httpx to get information on different endpoints on the same server, and there is no way to rate limit the requests per second(as I read on the Help menu), I reduced them by changing the number of threads used but still there is a lot of requests performed

is there any other way to do this?

**Comment by ehsandeep** [comment]
@blackpungas `httpx -threads 1` try this?

**Comment by blackpungas** [comment]
yup, that still got me banned from some servers

**Comment by nil0x42** [comment]
while using options that generate additional requests (`-http2`, `-vhost`, `-pipeline`, ...) it would be useful to at least be able to define a minimum time between two requests on the same IP/target

**Comment by ehsandeep** [comment]
@blackpungas `rate-limit` flag is added to control the number of requests to send per second.

**Comment by blackpungas** [comment]
wow! YES! 

you're awesome :) thanks guys

regards
