### ISSUE TITLE
`-deny` option doesn't work as expected

### ISSUE THREAD

**Issue by nil0x42** [projectdiscovery/httpx#317]
**Describe the bug**
The `-deny` option blocks every host when a single IP is specified. `-deny` option only works when combined with `-allow 0.0.0.0/0`.

**Environment details**
- `httpx -version`: v1.1.0
- `go version`: go1.16.5 linux/amd64
- `uname -a`: 5.4.0

### Reproducing the error:
> Example with `github.com` as target (it's IP is in `140.82.121.0/24`)

```bash
# denying 1.1.1.1 should keep everything working, because this IP is not used by github
echo github.com | httpx -verbose -ip -deny 1.1.1.1
[DBG] Failure 'http://github.com': GET http://github.com giving up after 1 attempts: Get "http://github.com": no address found for host

# the -deny option only works as expected if `-allow 0.0.0.0/0` is added as an option:
echo github.com | httpx -verbose -ip -allow 0.0.0.0/0 -deny 1.1.1.1
https://github.com [140.82.121.4]

# now denying 140.82.121.0/24 (CIDR of github.com's ip) ,it also works as expected:
echo github.com | httpx -verbose -ip -allow 0.0.0.0/0 -deny 140.82.121.0/24
[DBG] Failure 'http://github.com': GET http://github.com giving up after 1 attempts: Get "http://github.com": no address found for host
```

**Comment by ehsandeep** [comment]
@nil0x42 Now this has been fixed in the [dev](https://github.com/projectdiscovery/httpx/tree/dev) branch, thanks for flagging this.

**Comment by ehsandeep** [comment]
@nil0x42 changes merged into master.
