### ISSUE TITLE
Can export methods such as  html/Excel/csv  be added to the new version?

### ISSUE THREAD

**Issue by Hacker0x07** [projectdiscovery/httpx#324]
**Is your feature request related to a problem? Please describe.**
When httpx detects the subdomain of http/https, it supports -json and -o export methods by default. The -json method is more troublesome during use, and it is also more difficult to filter data. The information exported by the -o method is garbled. Can it be improved to support multiple formats, such as html/excel/csv?

**Describe the solution you'd like**
Improve the httpx output data, for example: in the detection process, whether it is possible to customize the output status code (200, 301, 302, etc.) in the information collection, instead of outputting all the status code data at once. In the process of information collection, there is often no need to collect status code data such as 400, 403, 404, 500, 501, 502, 503, and can be modified to the following output methods:
"cat domain.txt | httpx -status-code=200,301,302" or "cat domain.txt | httpx -status-code=200" 
And output formats such as Excel/html/csv, which are convenient for filtering data after testing.

Whether the specified data can be exported using -json export method, for example:
"cat domain.txt | httpx -status-code=200 -json -o domian.json"（Only output the url and status code, the default output data is too much, it is too troublesome to extract the desired information）

I also hope that the official website can provide a tutorial "How to quickly export data" (quickly filter out the required information)

**Comment by ehsandeep** [comment]
Thank you for sharing additional context @Hacker0x07, this is already being tracked here - https://github.com/projectdiscovery/httpx/issues/270 soon we will add more output format support to httpx, closing this issue as we are tracking this feature in the linked issue.
