### ISSUE TITLE
Exclude cdn

### ISSUE THREAD

**Issue by organiccrap** [projectdiscovery/httpx#328]
Similar to naabu's -exclude-cdn, skip port scans for CDNs when -ports are used and checks for 80,443

**Comment by ehsandeep** [comment]
@organiccrap This is now supported in the dev version, and works similarly to naabu. I'm not sure what your use case is, but for mass port scanning, naabu or any other port scanner should be used instead of httpx, as it's not the tool's primary function.

**Comment by organiccrap** [comment]
Hi @ehsandeep The use case is more to mass port scanning of known http/https ports, instead of TCP port scanner. Thanks for implementing the feature. Testing the function will get back if any issue.

**Comment by ehsandeep** [comment]
Changes are now merged into the master code.
