### ISSUE TITLE
what is the situation i need to recreate a AsyncClient

### ISSUE THREAD

**Issue by RonaldinhoL** [projectdiscovery/httpx#329]
i create a AsyncClient on my app init and keep it until my app exit. it this right?

i got many network error, but i dont't know if i need to recreate a client.

such as:
+ RuntimeError('Cannot send a request, as the client has been closed.')
the most
+ ReadTimeout('')
+ ProxyError('')
+ ProxyError('401 Unauthorized')
+ WriteError('Connection lost')
+ WriteError('[SSL: SSLV3_ALERT_BAD_RECORD_MAC] sslv3 alert bad record mac (_ssl.c:2627)')
+ WriteError('[WinError 64] 指定的网络名不再可用。')
The specified network name is no longer available
+ WriteError('[WinError 121] 信号灯超时时间已到')
The timeout period of the signal lamp has expired

help!

**Comment by Mzack9999** [comment]
@RonaldinhoL I think the issue was reported in the wrong repository. From a rapid look it seems like you are dealing with a closed instance, but you might find better support on the official repository at https://github.com/encode/httpx

**Comment by RonaldinhoL** [comment]
> @RonaldinhoL I think the issue was reported in the wrong repository. From a rapid look it seems like you are dealing with a closed instance, but you might find better support on the official repository at https://github.com/encode/httpx

sorry...
