### ISSUE TITLE
Adding flag to extract response content type

### ISSUE THREAD

**Issue by 0ktavandi** [projectdiscovery/httpx#33]
improvement of HTTPX for checking HTTP response based on content-type of given url list?
ex :
https://example.com/adsadsa > HTML
http://example.com/asdsadsaadssada > JSON

**Comment by bimkos** [comment]
Can you send an example of the launch flags?

**Comment by bauthard** [comment]
If I'm right @0ktavandi suggesting a feature to add flag `content-type` which will also list content-type header of the response if available, as an example:- 

```bash
> cat urls.txt | httpx -content-type 

https://mta-sts.hackerone.com [text/html]
https://mta-sts.managed.hackerone.com [text/html]
https://mta-sts.forwarding.hackerone.com [text/html]
https://docs.hackerone.com []
https://www.hackerone.com []
https://api.hackerone.com [application/json]
https://support.hackerone.com [text/html]
https://resources.hackerone.com [text/html]
```

this is doable and would be good information to have. 

@0ktavandi please confirm.

@bimkos FYI^

**Comment by 0ktavandi** [comment]
nice guys ! keep it up
