### ISSUE TITLE
sorry!when can we use this project as a golang library?

### ISSUE THREAD

**Issue by Nyx2020** [projectdiscovery/httpx#335]
**As this title**
I wanna know that when can we use httpx as project subfinder's EnumerateSingleDomain method in our project?maybe i'm too anxious

**Comment by Mzack9999** [comment]
@Nyx2020 All packages are exported, so indeed, it's possible to use httpx as a library. Anyway, httpx is not meant to enumerate subdomains. For that, I think you should look into subfinder.
