### ISSUE TITLE
v1.1.1: Better error message for websites resolving to blacklisted IP

### ISSUE THREAD

**Issue by nil0x42** [projectdiscovery/httpx#353]
It would be useful to have different error message when domain can't be resolved, vs when domain resolves to an IP denied by `-deny` flag (or outsite of `-allow`)

```sh
echo -e 'dailymotion.com\nINVALID' | httpx -silent -json -deny 195.8.0.0/16 -probe
```
```json
{"timestamp":"2021-08-10T06:11:27.264699898Z","url":"http://dailymotion.com","input":"dailymotion.com","error":"no address found for host","failed":true}
{"timestamp":"2021-08-10T06:11:27.276467986Z","url":"http://INVALID","input":"INVALID","error":"no address found for host","failed":true}
```
both erros are the same: `no address found for host`

**Describe the solution you'd like**
An more explicit error message like `IP not allowed`, or `IP filtered out` for the `-deny` case would be great

**Comment by ehsandeep** [comment]
thank you for creating GH issue for this @nil0x42, this is now updated with **denied address found for host**

```sh
echo example.com | ./httpx -ip -deny 93.184.216.34 -json -probe -silent | jq .

{
  "timestamp": "2021-08-15T15:57:56.474027+05:30",
  "url": "http://example.com",
  "input": "example.com",
  "error": "denied address found for host",
  "failed": true
}
```
