### ISSUE TITLE
bug with output http title

### ISSUE THREAD

**Issue by Malayke** [projectdiscovery/httpx#37]
Hi, I find a bug, httpx can not correct output none ASCII string, like Chinese

```
▶ echo https://tnw.qq.com  | httpx -title -silent 
https://tnw.qq.com [The Next Web����վ_��Ѷ�Ƽ�_��Ѷ��]
```
I try to fix it by myself, but I'm not good at go

the correct output is:
```
echo https://tnw.qq.com  | httpx -title -silent | iconv -f gbk
https://tnw.qq.com [The Next Web中文站_腾讯科技_腾讯网]
```

**Comment by bimkos** [comment]
I don't know what will happen to other requests. Do you think this will be a universal solution? Can I add a switch for encodings?

**Comment by bauthard** [comment]
@bimkos, adding a flag for this will increase the complexity, as a "user" we don't know when we going to encounter for the cases like this, so we can't be sure when to use a flag or not, so surely we need to come up with something which works in existing flow.

**Comment by bauthard** [comment]
```bash
> echo tnw.qq.com  | ./httpx -title -silent -follow-redirects
https://tnw.qq.com [The Next Web中文站_腾讯科技_腾讯网]
```

@Malayke this is fixed now.
