### ISSUE TITLE
Add headless mode

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/httpx#384]
- [x] Add rendered dom/html to json output

**Comment by M09Ic** [comment]
I think this is a useful feature, before I encountered a similar requirement, I had to use python selenium to solve it

**Comment by powerpunkorg** [comment]
Would be nice to have headless in httpx. Some features are only httpx related, like technology detect. Or it's possible to get html content by nuclei headless and pass it to httpx somehow ?

**Comment by rewiaca** [comment]
Would be nice to have headless in httpx. Some features are only httpx related, like technology detect. Or it's possible to get html content by nuclei headless and pass it to httpx somehow ?
