### ISSUE TITLE
Add screenshot support

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/httpx#385]
Along #384 add support for screenshot capability via **-screenshot** option

**Comment by M09Ic** [comment]
I think this is a useful feature, before I encountered a similar requirement, I had to use python selenium to solve it

**Comment by 1mansh0w** [comment]
Any updates on this? I think this feature request is great in terms of efficiency, because otherwise you have to redo all the requests just for taking screenshots.

**Comment by forgedhallpass** [comment]
@M09Ic @1mansh0w 

Currently this ticket is under advisement and would require headless support first. See the referenced issue above.
In the meantime as an alternative, you can use nuclei to achieve the same:

```sh
nuclei -u https://nuclei.projectdiscovery.io -id screenshot -headless # creates a file named nuclei.projectdiscovery.io.png
```
