### ISSUE TITLE
[Feature] Maybe we need to support socks5/4/4a proxy

### ISSUE THREAD

**Issue by hl0rey** [projectdiscovery/httpx#387]
Maybe we need to support socks5/4/4a proxy.
Socks proxy is often required for Intranet scanning. Currently, only HTTP proxies are supported, which greatly limits the application scenarios of the tool.

**Comment by hl0rey** [comment]
Alright,I will do it by myself

**Comment by jsgv** [comment]
Was support for this added?

**Comment by bfnserra** [comment]
Follow up on this. I bookmarked this and checking time to time. That could be a great addition to this amazing tool. @ehsandeep any idea if this is planned ?

**Comment by Mzack9999** [comment]
@bfnserra It's already supported with `-proxy` cli option:

```console
$ echo https://api.myip.com | httpx -proxy socks5://127.0.0.1:9050 -debug
```
