### ISSUE TITLE
it is impossible to disable -random-agent flag (and set permanent User-Agent)

### ISSUE THREAD

**Issue by rivalsec** [projectdiscovery/httpx#391]
**Describe the bug**
it is impossible to disable -random-agent flag (and set permanent User-Agent through -H flag)

**Environment details**

- `httpx -version` v1.1.2
- `go version` go1.16.5 darwin/arm64
- `uname -a` Darwin MacBook-Air-Vladimir.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64

**Error details**
After this command
```
echo "https://example.com/" | httpx -http-proxy http://127.0.0.1:8080 -random-agent false -H "User-Agent: testagent"
```
i see in burp proxy in request headers random user-agent every time
And without -random-agent false it's the same

**Comment by rivalsec** [comment]
i closed it.
duplicate of https://github.com/projectdiscovery/httpx/issues/382

**Comment by ehsandeep** [comment]
@rivalsec this is now fixed in the dev version.
