### ISSUE TITLE
--all and --exclude flags option

### ISSUE THREAD

**Issue by afaq1337** [projectdiscovery/httpx#409]
Could you please add a feature to run all flags at once?

For example:

**-all** flag option will launch all the available probes and **-exclude** as well to remove a specific one or two probes from the list.

**Comment by ehsandeep** [comment]
Hello, @afaq1337!

Thank you for raising an issue. I'm not sure what you're trying to do with the "all" flag, as those flags are not supposed to be used together.

See the [notes](https://github.com/projectdiscovery/httpx#-notes) for reasons why they can't and shouldn't be combined, closing this issue as this can not be implemented.

**Comment by afaq1337** [comment]
@ehsandeep, Thanks for the feedback! I got the point. But for example, I have been using these many flags to probe the website every time.

``httpx -title -tech-detect -status-code -cdn -web-server -follow-redirects -silent -ip``

Isn't that possible that we can run the basic enum like above to the website just one go?
