### ISSUE TITLE
Infinite recursion in LoadCidrsFromSliceOrFile()

### ISSUE THREAD

**Issue by nil0x42** [projectdiscovery/httpx#416]
**Describe the bug**
function `LoadCidrsFromSliceOrFile()` is prone to infinite recursion bug.
Giving `-allow` or `-deny` a file whose name is present among line of the file leads to infinite recursion.
https://github.com/projectdiscovery/httpx/blob/b71c3a7a3e39ffd40a2de28d08cf660569548421/common/fileutil/fileutil.go#L79-L94

**How To reproduce**
```bash
echo tmp > tmp
echo google.com | httpx -deny tmp
```

**Comment by ehsandeep** [comment]
@nil0x42 we have pushed a fix for this in linked PR https://github.com/projectdiscovery/httpx/pull/420, can you check and confirm the same?
