### ISSUE TITLE
Custom host header

### ISSUE THREAD

**Issue by AlessandroZ** [projectdiscovery/httpx#42]
Hi, 

It could be awesome if I could overwrite the host header like that: 
```
echo "http://example.com" | httpx -http-proxy http://127.0.0.1:8080 -H "Host: test"
```

Other header are well rewritten (User-Agent, etc.), except this one.
I know you have a vhost option but it would be much easier to use if I could check it like that.

Love your tool, thanks a lot.

**Comment by bauthard** [comment]
This is fixed and now supports custom HOST headers as well. @AlessandroZ 

```bash
echo http://example.com | ./httpx -silent -http-proxy http://127.0.0.1:8080 -H "Host: test"
```

![image](https://user-images.githubusercontent.com/8293321/88268411-09643180-ccf0-11ea-9870-734632c9860b.png)

**Comment by AlessandroZ** [comment]
Cool, thanks a lot. :+1:

**Comment by hassaanahmad813** [comment]
How to use multiple headers and multiple cookies in httpx for example
httpx -u https;//www.example.com -H "Header1: Value1, Header2: Value2"
httpx -u https://www.example.com -Cookie "Cookie1: Value1, Cookie2: Value2"
The documentation is not saying it clearly.
