### ISSUE TITLE
-silent options only working if we give after httpx -silent .

### ISSUE THREAD

**Issue by balook** [projectdiscovery/httpx#43]
-silent options only working if we give after httpx -silent .
but not if we give httpx -options -silnet

**Comment by bauthard** [comment]
```bash
> echo k5qoyjj6xonvb14v9k3asp6n6ec60v.burpcollaborator.net | httpx -status-code -silent 
https://k5qoyjj6xonvb14v9k3asp6n6ec60v.burpcollaborator.net [200]
```

looks like a typo on your side? works for me. @balook

**Comment by balook** [comment]
how to print only a specific response  from httpx ? lkle only 200

**Comment by bauthard** [comment]
```bash
cat urls.txt | httpx -status-code | grep 200
```

we will add native support later https://github.com/projectdiscovery/httpx/issues/40
