### ISSUE TITLE
The software only supports charset="UTF-8"

### ISSUE THREAD

**Issue by pandak1d** [projectdiscovery/httpx#441]
The software only supports charset="UTF-8". If the title of charset="euc-kr" will appear garbled, is there a golang package that can automatically convert the encoding format according to charset, just like the library in python
```
mychar = chardet.detect(response.content)
response.encoding = mychar['encoding']
```
![image](https://user-images.githubusercontent.com/69457324/143391484-d01865b1-ca9d-475f-88d2-a821137e492b.png)
![image](https://user-images.githubusercontent.com/69457324/143392359-29d0a007-6ac9-45a0-8151-788b5d14c6c3.png)

**Comment by ehsandeep** [comment]
```console
echo https://www.100yearshop.co.kr/shop/main/index.php | httpx -title -silent -timeout 20
https://www.100yearshop.co.kr/shop/main/index.php []
```

**Comment by pandak1d** [comment]
Like this is garbled！！！
![image](https://user-images.githubusercontent.com/69457324/144558368-c8d253eb-5ff5-469a-8dca-efb17b13ec18.png)

**Comment by pandak1d** [comment]
Why was it removed
