### ISSUE TITLE
Implement rate limit per minute (rlm) support

### ISSUE THREAD

**Issue by ImNightmaree** [projectdiscovery/httpx#442]
### Please describe your feature request:
In line with Nuclei's configuration options, implement the -rlm flag which will allow users to rate limit per minute, rather than solely on a per-second basis.

### Describe the use case of this feature:
Where a bug bounty program specifies rate limiting on a per-minute basis rather than per-second, it could be handy. It would also bring alignment to other projects where this option exists.

**Comment by ehsandeep** [comment]
Related PR in nuclei - https://github.com/projectdiscovery/nuclei/pull/896
