### ISSUE TITLE
Stats information is not aligned with actual scan process - divided by 2

### ISSUE THREAD

**Issue by NagliNagli** [projectdiscovery/httpx#443]
### httpx version:
1.10

### Current Behavior:

Scans seems to end correctly, yet the "stats" show that we only got to 50% of our domains, probably an issue with the stats implementation rather of httpx stopping at 50%

### Expected Behavior:

Having the stats aligned with the end of the scan, so when it's 50% it should actually be 100%.

### Steps To Reproduce:

1. cat domains | httpx -stats
2. observe that the scan ends when you reach 50%

-->

### Anything else:

![Screen Shot 2021-11-27 at 19 51 11](https://user-images.githubusercontent.com/35578316/143691628-ca508131-dee2-41f8-ac56-637f77c036cd.png)

**Comment by ehsandeep** [comment]
most probably errors generated by `max-host-error` is not counted or aligned with stats, but this needs further investigation to confirm.

**Comment by ehsandeep** [comment]
@NagliNagli noticed you mentioned using `httpx 1.1.0`, at the time of creating this issue, `1.1.3` was the latest one and we just published `v1.1.4`, this specific issue may exist in the current version but make sure you always use the latest version to avoid facing issues that may be fixed in latest versions.

**Comment by LuitelSamikshya** [comment]
Issue could not be replicated in the latest dev and master version. Stats shows that 100% of the domains are covered. 


<img width="669" alt="Screen Shot 2021-12-06 at 2 36 25 PM" src="https://user-images.githubusercontent.com/85764322/144919144-0cc7a328-1842-4b5c-91b5-5769ba52f6bd.png">

**Comment by ehsandeep** [comment]
@NagliNagli Can you confirm if you are still able to reproduce this issue with latest release of httpx?

**Comment by ehsandeep** [comment]
@NagliNagli closing this issue as this is not reproducible in the latest version of httpx (1.1.4), feel free to ping me back if you have a working example to share.
