### ISSUE TITLE
New feature to display / filter / match against line count of the response "body"

### ISSUE THREAD

**Issue by zeroc00I** [projectdiscovery/httpx#453]
I was thinking that would be awesome if line number parameter could be accepted as content-length.
i mean, the tool could allow a user requires line numbers retrieve from the http requests to the target

Line numbers are fairly used on tools like ffuf.
I've used httpx alot and i think that only this parameter is currently missing to be a full tool to bug hunters =)

Thank you

**Comment by ehsandeep** [comment]
```console
echo https://example.org | ./httpx -path wordlist.txt -line-count

https://example.org/1 [47]
https://example.org/2 [47]
https://example.org/3 [47]
```

```console
echo https://example.org | ./httpx -path wordlist.txt -mlc 47

https://example.org/1 [47]
https://example.org/2 [47]
https://example.org/3 [47]
```

```console
echo https://example.org | ./httpx -path wordlist.txt -flc 47
```

Flags:

```yaml
   -lc, -line-count     Display Response body line count
   -mlc, -match-line-count    Match Response body line count
   -flc, -filter-line-count    Filter Response body line count
```

**Comment by ehsandeep** [comment]
@zeroc00I this is now supported in [dev](https://github.com/projectdiscovery/httpx/tree/dev) version with the following PR - https://github.com/projectdiscovery/httpx/pull/468

we have added both, `line `count and `word` count support.
