### ISSUE TITLE
FR: URI bruteforcing (dirbusting)

### ISSUE THREAD

**Issue by hazcod** [projectdiscovery/httpx#478]
### Please describe your feature request:
It would be nice to be able to retry a probe against a list of subdirectories/URIs, akin to dirbuster.

### Describe the use case of this feature:
Sometimes a target is not listening on `/`.

**Comment by ehsandeep** [comment]
@hazcod `path` flag supports this already, you can feed a list of paths to query or let me know if I misunderstood the feature request?

**Comment by hazcod** [comment]
@ehsandeep Seems like I missed that one. thanks!
