### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by z7701858** [projectdiscovery/httpx#480]
### Expected Behavior:
![image](https://user-images.githubusercontent.com/32709921/148635055-12867e0c-529d-47a3-bdbb-c16e9a9b5cfb.png)

### Steps To Reproduce:

Run 'httpx -l target.txt -path "///////../../../../../../etc/passwd"'
See error
![image](https://user-images.githubusercontent.com/32709921/148635077-32598a70-ca49-402a-90cc-9cb5a6cf4709.png)
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x9002d3]

goroutine 14 [running]:
github.com/projectdiscovery/httpx/runner.(*Runner).analyze(_, _, {_, _}, {_, _}, {_, _}, {0xc000eea780, 0x1b}, ...)
        /home/runner/work/httpx/httpx/runner/runner.go:874 +0xe93
github.com/projectdiscovery/httpx/runner.(*Runner).process.func1({0xc000eea780, 0x1b}, {0x9fe1ef, 0x3}, {0xa042ab, 0xa})
        /home/runner/work/httpx/httpx/runner/runner.go:651 +0x125
created by github.com/projectdiscovery/httpx/runner.(*Runner).process
        /home/runner/work/httpx/httpx/runner/runner.go:649 +0x965
```

**Comment by slowmistio** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x1501253]

goroutine 291 [running]:
github.com/projectdiscovery/httpx/runner.(*Runner).analyze(_, _, {_, _}, {_, _}, {_, _}, {0xc00079e600, 0xe}, ...)
	/home/runner/work/httpx/httpx/runner/runner.go:874 +0xe93
github.com/projectdiscovery/httpx/runner.(*Runner).process.func1({0xc00079e600, 0xe}, {0x16011f1, 0x3}, {0x160717e, 0xa})
	/home/runner/work/httpx/httpx/runner/runner.go:651 +0x125
created by github.com/projectdiscovery/httpx/runner.(*Runner).process
	/home/runner/work/httpx/httpx/runner/runner.go:649 +0x965

**Comment by atastycookie** [comment]
```
➜ httpx -l REDACTED_DOMAIN_LIST.txt --path '////////////////../../../../../../../../etc/passwd' -status-code -mc 200 -ms 'root:'

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.1.4

		projectdiscovery.io

Use with caution. You are responsible for your actions.
Developers assume no liability and are not responsible for any misuse or damage.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x15bed01]

goroutine 13 [running]:
github.com/projectdiscovery/httpx/runner.(*Runner).analyze(0xc000288500, 0xc0001b3090, 0x16eda67, 0xa, 0xc0001bd5c0, 0x11, 0x16e7a73, 0x3, 0xc0001bd5c0, 0x11, ...)
	/Users/REDACTED/go/pkg/mod/github.com/projectdiscovery/httpx@v1.1.4/runner/runner.go:874 +0x6d41
github.com/projectdiscovery/httpx/runner.(*Runner).process.func1(0xc0000e4fa0, 0xc000288500, 0xc0001b3090, 0xc0001bd5c0, 0x11, 0xc0000fe370, 0xc0000ea480, 0xc0001bd5c0, 0x11, 0x16e7a73, ...)
	/Users/REDACTED/go/pkg/mod/github.com/projectdiscovery/httpx@v1.1.4/runner/runner.go:651 +0xff
created by github.com/projectdiscovery/httpx/runner.(*Runner).process
	/Users/REDACTED/go/pkg/mod/github.com/projectdiscovery/httpx@v1.1.4/runner/runner.go:649 +0x785
```

**Comment by CreditMint** [comment]
Hi, I have the same error.

**Comment by aviadhahami** [comment]
Hitting the same problem, can repro on Ubuntu

**Comment by oways** [comment]
Solved this issue by adding # at the end of the path 

Example:
```
-path "///////../../../../../../../etc/passwd#"
```

**Comment by aviadhahami** [comment]
> Solved this issue by adding # at the end of the path
> 
> Example:
> 
> ```
> -path "///////../../../../../../../etc/passwd#"
> ```

I think not, but dyt there's any impact on the parsers?

**Comment by oways** [comment]
httpx reading the content of the path that you provide locally first (in your pc) to check for multiple paths and if it is not valid it jumps to the second choice which is fetching for website path, this is why by adding ```#``` at the end will be a good workaround as it converts it to invalid local path and it does not effect the actual URI path.

In this case ``` ///////../../../../../../../etc/passwd ``` is a valid system file path for unix based systems

Check the following screenshot:

<img width="960" alt="Screen Shot 2022-01-09 at 1 15 03 PM" src="https://user-images.githubusercontent.com/11142952/148678150-17152442-a0fe-4785-9294-a5e2c8efca11.png">

And for the error yes it is related to parsing as the following value causing the error ``` :*:/ ``` which is part of passwd file:

<img width="1163" alt="Screen Shot 2022-01-09 at 1 26 59 PM" src="https://user-images.githubusercontent.com/11142952/148678451-c0307c9f-d8ff-4ef1-a31f-c03c406cb58e.png">

**Comment by ehsandeep** [comment]
This is now fixed with latest release - https://github.com/projectdiscovery/httpx/releases/tag/v1.1.5

**Comment by aviadhahami** [comment]
thx for the quick response @ehsandeep 👍
