### ISSUE TITLE
Please, add BodySHA256 match/filter

### ISSUE THREAD

**Issue by atlassion** [projectdiscovery/httpx#488]
Hi all!  why not add option BodySHA256 match/filter ?
`echo http://site/file.png | httpx | jq -Mcr '.["body-sha256"]'`
pic.:
`httpx -path /path/any_pic.png -msha sha256_HASH`

or js :
`httpx -path /path/any_file.js -msha sha256_HASH`
etc

**Comment by M09Ic** [comment]
I need a similar function, but it's md5.
So, I was wondering if I could support custom common hash types.
Like:
`echo url | httpx -hash md5,sha1,sha256`

**Comment by ehsandeep** [comment]
@atlassion recently multiple hash support was introduced to httpx, so it's not feasible to add new flags to match/filter by each hash type instead we suggest using json format for output and doing the post-processing on output file as you need or simple grep will also work for this case:

```console
chaos -silent -d hackerone.com | httpx -hash md5 -silent | grep bb44d26003a2b044e235aae2fc8427f7

https://mta-sts.managed.hackerone.com [bb44d26003a2b044e235aae2fc8427f7]
https://mta-sts.forwarding.hackerone.com [bb44d26003a2b044e235aae2fc8427f7]
https://mta-sts.hackerone.com [bb44d26003a2b044e235aae2fc8427f7]
```
