### ISSUE TITLE
Feature request: support -simhash

### ISSUE THREAD

**Issue by M09Ic** [projectdiscovery/httpx#489]

**Comment by ehsandeep** [comment]
@M09Ic Can you also include information for the below fields?

- Please describe your feature request:
- Describe the use case of this feature:

**Comment by M09Ic** [comment]
Sorry, I forgot to add a description.
Before, I used simhash to determine the page similarity. So I want to add simhash probe for body/header/all. 

I used to use this library:https://github.com/mfonda/simhash

**Comment by M09Ic** [comment]
I think, we can add the -hash [hashtype] option
for example:
choice
'-hash [md5/sha1/sha256/mmh3/simhash]` 

multi args
`-hash md5,simhash `
