### ISSUE TITLE
Extending path support to take file as input

### ISSUE THREAD

**Issue by bauthard** [projectdiscovery/httpx#51]
Reference:- https://github.com/projectdiscovery/httpx/issues/47

For now, we are adding support to take a single path as input, if it's needed we can later add file input support as well, this issue for tracking purposes.

**Comment by sabeesh03** [comment]
subfinder -d lghhghd.com | httpx -path /phpinfo.php -status-code -content-length -title
flag provided but not defined: -path
root@bheem:~# httpx -version
    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   / 
 / / / / /_/ /_/ /_/ /   |  
/_/ /_/\__/\__/ .___/_/|_|  
             /_/            
                projectdiscovery.io
[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Current Version: 1.0.2

**Comment by bauthard** [comment]
Deleted the above comment as it was unrelated to this issue and resolved already.

**Comment by bauthard** [comment]
This can be done with nuclei fuzzing support.

**Comment by bauthard** [comment]
This support added into `dev` branch https://github.com/projectdiscovery/httpx/commit/2112a440fcbe069d6f110d508241a62ce134d499 with `paths` flag accepting file input.
