### ISSUE TITLE
`-http-proxy` blocked by `-deny` options

### ISSUE THREAD

**Issue by nil0x42** [projectdiscovery/httpx#513]
It looks like `-http-proxy` access is denied if proxy IP is within `-deny` address list.

e.g:
`httpx -http-proxy http://127.0.0.1:8443 -deny 127.0.0.0/8 < /tmp/site-list`
proxy connection is denied...

The proxy should not depend on -deny/-allow restrictions. I example above, i deny `127.*` IPs to prevent httpx from trying to open ports 443/80 on localhost if a domain resolved to localhost. But i still want httpx to be usable by httpx.

**Comment by ehsandeep** [comment]
Unfortunately, this behavior will remain the same, an attempt to support this feature introduced additional complexities to handle in the underlying library.
