### ISSUE TITLE
Support jarm algorithm for tls

### ISSUE THREAD

**Issue by M09Ic** [projectdiscovery/httpx#549]
### Please describe your feature request:
I found that httpx contains cryptoutil, which has the fingerprintSHA256 attribute. I tested it, fingerprintSHA256 and JARM algorithm do not have the same result. Is it possible to support the JARM algorithm? Thanks

```console
echo hackeorne.com | httpx -silent -hash jarm

https://hackerone.com [29d3dd00029d29d00042d43d00041d5de67cc9954cc85372523050f20b5007]
```

```console
echo hackeorne.com | httpx -json -silent | jq .hashes

{
  "body-md5": "d41d8cd98f00b204e9800998ecf8427e",
  "body-mmh3": "-1840324437",
  "body-sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  "body-simhash": "18446744073709551615",
  "header-md5": "f04436074c0e0fe5dda7d54877d9637d",
  "header-mmh3": "995155223",
  "header-sha256": "82088d86e12b9a4e404108569eee7582152754c107f73b9052255a9a439e033f",
  "header-simhash": "14425844467790233390",
  "jarm": "29d3dd00029d29d00042d43d00041d5de67cc9954cc85372523050f20b5007"
}
```

python version:
https://github.com/salesforce/jarm  

go version:
https://github.com/RumbleDiscovery/jarm-go

### Describe the use case of this feature:
jarm result:
```
 python .\jarm.py www.baidu.com
Domain: www.baidu.com
Resolved IP: 180.101.49.11
JARM: 29d1fb00029d29d1fc29d1fb1fb29dfcafcab2e75118e87142efdb7e13a350
```

httpx -tls-probe fingerprintSHA256 from debug:
`4d6fe423120ed053746cacbe266198cab638aa2d0a03b03c8178ab17263d8737`

Is it possible to add the -jarm flag to support the jarm algorithm for tls. like: `echo https://baidu.com | httpx -hash jarm`

**Comment by ehsandeep** [comment]
@M09Ic this is now supported in the latest release, thanks for suggesting this feature.
