### ISSUE TITLE
Cookies Aren't Included in Redirects

### ISSUE THREAD

**Issue by wdahlenburg** [projectdiscovery/httpx#554]
### Current Behavior:
Setting a cookie on httpx with the `-fr` flag to follow redirects will drop the cookie on the subsequent requests.

```
echo http://127.0.0.1:4000/foobar | ./httpx -proxy http://127.0.0.1:8080 -H "Cookie: foo=bar" -fr
```

![image](https://user-images.githubusercontent.com/4451504/159520579-1d240311-45d9-4ad4-b3ed-70eeb3541902.png)
![image](https://user-images.githubusercontent.com/4451504/159520666-a4b80d17-219c-4c39-b4b4-84be3516135b.png)

This behavior doesn't appear to happen with other headers. Adding the `X-Forwarded-For` header to the same request shows the header in the redirected request:

```
echo http://127.0.0.1:4000/foobar | ./httpx -proxy http://127.0.0.1:8080 -H "Cookie: foo=bar" -H "X-Forwarded-For: 127.0.0.1" -fr
```
![image](https://user-images.githubusercontent.com/4451504/159520775-2b096527-309d-4555-9818-fe13d97c51ca.png)
![image](https://user-images.githubusercontent.com/4451504/159520829-cb39105d-895a-42a4-b512-a5d14d58cea8.png)

### Expected Behavior:

While the site responding with the redirect could intentionally redirect the user and cookies off-site, it'd be nice to be able to force the httpx client to use the cookies on the subsequent requests.

### Steps To Reproduce:
1. Identify an endpoint that performs a redirect
2. Send that through httpx with the cookie header set to some value (-H "Cookie: foo=bar") and a proxy enabled to view the traffic
3. Observe that the first request includes the cookie, but the second one does not.

**Comment by ehsandeep** [comment]
@wdahlenburg, this should be fixed in the latest release.
