### ISSUE TITLE
add TLS SNI and let HTTPS have priority 

### ISSUE THREAD

**Issue by 0xAwali** [projectdiscovery/httpx#566]
it's possible to let users specify TLS SNI like this one https://github.com/ffuf/ffuf/issues/440 and make HTTPS have the priority.

Add a new -sni flag that will be used when establishing TLS connections:

```
echo hackerone.com | httpx -sni www.hackerone.com
```

**Comment by ehsandeep** [comment]
@0xAwali HTTPS is already on priority and probed as default. Did you notice different behavior in any case?

**Comment by 0xAwali** [comment]
while trying scan the internet then use [tls-scan](https://github.com/prbinu/tls-scan) to get what belong to my org  by parsing the TLS-Certificate so I figured out , if I put my hostname as sni I get what I need but now I wanna parse favicon too so best option here to do both is httpx so adding sni will be good .
 plus httpx parse favicon wrongly e.g. [apullo](https://github.com/ninoseki/apullo) parse
 `<link rel="shortcut icon" href="favicon/location"/>` and that is the correct way

**Comment by DonatoReis** [comment]
@0xAwali I agree, HTTPS must take priority in the call

**Comment by DonatoReis** [comment]
> @0xAwali HTTPS is already on priority and probed as default. Did you notice different behavior in any case?

in my calls, even though the domain is https, it returns http

**Comment by ehsandeep** [comment]
> > @0xAwali HTTPS is already on priority and probed as default. Did you notice different behavior in any case?
> 
> in my calls, even though the domain is https, it returns http

Do you have an example that you can share?

**Comment by 0xAwali** [comment]
awesome as usual

**Comment by 0xAwali** [comment]
sorry for that but this one not overwrite SNI , I checked multiple times by using wireshark 

![Screenshot_2022-05-07_11_47_32](https://user-images.githubusercontent.com/54332136/167249074-5d3e82da-eb1f-4c07-bd60-e601789c3588.png)

**Comment by ehsandeep** [comment]
> sorry for that but this one not overwrite SNI , I checked multiple times by using wireshark
> 
> ![Screenshot_2022-05-07_11_47_32](https://user-images.githubusercontent.com/54332136/167249074-5d3e82da-eb1f-4c07-bd60-e601789c3588.png)

Thanks for pointing this out @0xAwali, should be fixed with https://github.com/projectdiscovery/httpx/pull/614

**Comment by 0xAwali** [comment]
yah I checked now , I can confirm that
