### ISSUE TITLE
http-proxy still ignored, user-agent trimming issue 

### ISSUE THREAD

**Issue by Haones** [projectdiscovery/httpx#58]
Hello, 

I'm using httpx v0.8, the command:
`cat urls.txt | httpx -http-proxy http://*.*.*.*:3128 -mc 200,302 -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0' -H 'Cookie: ...' -o result.txt`

For some reason httpx still fetches given URL list with my default IP which results in 403 errors from the server. What is interesting is that when I use ffuf with the same proxy setting and those 2 same headers, everything works as expected. 

I tried to check the source code of **cmd/httpx.go** and find the issue myself, but I don't have go knowledge at all so after a few comparisons of how it's done in ffuf and in httpx I didn't spot the reason why proxy still ignored in httpx.

**Comment by bauthard** [comment]
Thank you @Haones, I will try to reproduce this and update here.

**Comment by Haones** [comment]
I checked this issue: https://github.com/projectdiscovery/httpx/pull/56

He says here that for some reason -H passed with semicolon inside of the -H option body trims twice instead of first semicolon occurrence. In case of my issue it actually may matter since I used proxy to bypass Cloudflare and Cloudlfare will still ban certain request if the `User-Agent:` doesn't match the one for which `cf_clearance=` cookie was created. So probably http-proxy works, but request still denied because `User-Agent:` header being trimmed in actual request sent by **httpx**.

So the bug fixed in pull 56 is:
Passing option: `-H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0'`
Results in: 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv'
Instead of expected: 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0'

**Comment by Haones** [comment]
Yeah, confirming that #56 PR is the issue here. I just proxied httpx to burp to see how it passes user-agent and it was like that:
![image](https://user-images.githubusercontent.com/31140223/89466196-0b140780-d77c-11ea-9c90-169181458265.png)

**Comment by Mzack9999** [comment]
@Haones I'm not able to reproduce this. Some changes have been implemented, hopefully this got resolved indirectly. Let us know if you still face the issue and I will have another look. Thanks for the very detailed issue!

**Comment by bauthard** [comment]
@Haones you can do `GO111MODULE=auto go get -u -v github.com/projectdiscovery/httpx/cmd/httpx@master` to update with the recent changes and retest the issue.

**Comment by Haones** [comment]
Hello, had to update without using `@master` string, since it results in error:
```
>GO111MODULE=auto go get -u -v github.com/projectdiscovery/httpx/cmd/httpx@master
go: cannot use path@version syntax in GOPATH mode
```

Retests I made:
1. `> echo https://cloudflare_host/ | httpx -http-proxy hxxp://x -H "Cookie: cf_clearance=" -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.27 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/601.1.27" -status-code` 
Returned **200**, everything works as expected, http-proxy flag **fixed**.
2. `> echo https://cloudflare_host/ | httpx -http-proxy hxxp://x -H "Cookie: cf_clearance=" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0" -status-code`
Returned **403**, debugging this request shows that httpx actually sent request with `User-Agent: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv`, everything after **colon** still stripped away.

Conclusion: `-http-proxy` flag appears to be working now. `-H` flag still strips away everything after a second **colon**. So: `-H "Header: value : value2"` results in `Header: value` when request is performed. Workaround for this is just to use header without multiple **colons**, but I do really think this should be fixed.

Thanks!

**Comment by bauthard** [comment]
![image](https://user-images.githubusercontent.com/8293321/91263340-f086ea00-e78d-11ea-8e02-069d0cb93f91.png)

@Haones I tried to repo the user-agent issue you listed here, but I'm not able to reproduce it, as you can see the above screenshot.

**Comment by Haones** [comment]
Hello @bauthard,

My bad, I had 2 different httpx versions installed, was a bit confused since they're all reporting same version. Just ran command again with the newest version, trimming issue is fixed now.

Thank you!
