### ISSUE TITLE
httpx has no results

### ISSUE THREAD

**Issue by MSI0072** [projectdiscovery/httpx#583]
### Steps To Reproduce:
1. echo umm.ac.id | httpx -sc
![image](https://user-images.githubusercontent.com/63404067/163699911-baa9fce4-0d83-4ca0-9bc4-57682add1f06.png)

**Comment by jimen0** [comment]
Works just fine for me using the linux amd64 binary from the releases tab.

```console
$ echo "api.hackerone.com" | ./httpx-v1.2.1 -title -tech-detect -status-code -silent
https://api.hackerone.com [200] [HackerOne API] [Algolia,Cloudflare]
$ file httpx-v1.2.1
httpx-v1.2.1: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=ZyroPqMVqft5vgU_sjp4/TLPuW6Wm3PrTTdGc4Unt/mGPBhngWb9s86xXhiiwn/NzBaS132-M68Oq954P9t, stripped
```

What binary are you using @MSI0072? How was it built? How is the environment where it's being ran configured? (Run `env` command)

cc @ehsandeep

**Comment by MSI0072** [comment]
httpx: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=rWiKk6pKvhvyxwcGlDY1/thCO48Qm1MPzd632sMmd/8YsBAMs4WSQ1G6tgZnVU/ZbYZoZYNU22zJihuaBp7, not stripped

**Comment by MSI0072** [comment]
> Works just fine for me using the linux amd64 binary from the releases tab.
> 
> ```
> $ echo "api.hackerone.com" | ./httpx-v1.2.1 -title -tech-detect -status-code -silent
> https://api.hackerone.com [200] [HackerOne API] [Algolia,Cloudflare]
> $ file httpx-v1.2.1
> httpx-v1.2.1: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=ZyroPqMVqft5vgU_sjp4/TLPuW6Wm3PrTTdGc4Unt/mGPBhngWb9s86xXhiiwn/NzBaS132-M68Oq954P9t, stripped
> ```
> 
> What binary are you using @MSI0072? How was it built? How is the environment where it's being ran configured? (Run `env` command)
> 
> cc @ehsandeep

httpx: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=rWiKk6pKvhvyxwcGlDY1/thCO48Qm1MPzd632sMmd/8YsBAMs4WSQ1G6tgZnVU/ZbYZoZYNU22zJihuaBp7, not stripped

**Comment by MSI0072** [comment]
thank you, now it can be used


> Works just fine for me using the linux amd64 binary from the releases tab.
> 
> ```
> $ echo "api.hackerone.com" | ./httpx-v1.2.1 -title -tech-detect -status-code -silent
> https://api.hackerone.com [200] [HackerOne API] [Algolia,Cloudflare]
> $ file httpx-v1.2.1
> httpx-v1.2.1: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=ZyroPqMVqft5vgU_sjp4/TLPuW6Wm3PrTTdGc4Unt/mGPBhngWb9s86xXhiiwn/NzBaS132-M68Oq954P9t, stripped
> ```
> 
> What binary are you using @MSI0072? How was it built? How is the environment where it's being ran configured? (Run `env` command)
> 
> cc @ehsandeep

**Comment by MSI0072** [comment]
> Works just fine for me using the linux amd64 binary from the releases tab.
> 
> ```
> $ echo "api.hackerone.com" | ./httpx-v1.2.1 -title -tech-detect -status-code -silent
> https://api.hackerone.com [200] [HackerOne API] [Algolia,Cloudflare]
> $ file httpx-v1.2.1
> httpx-v1.2.1: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=ZyroPqMVqft5vgU_sjp4/TLPuW6Wm3PrTTdGc4Unt/mGPBhngWb9s86xXhiiwn/NzBaS132-M68Oq954P9t, stripped
> ```
> 
> What binary are you using @MSI0072? How was it built? How is the environment where it's being ran configured? (Run `env` command)
> 
> cc @ehsandeep

thank you, now it can be used

**Comment by ehsandeep** [comment]
Closing as this is resolved @MSI0072, thank you @jimen0 for confirming.
