### ISSUE TITLE
[FTL] error in -cdn flaq failed all command 

### ISSUE THREAD

**Issue by Ph33rr** [projectdiscovery/httpx#599]
Hello, again

command ; 
httpx -status-code -content-length -title -tech-detect -cdn -ip -follow-host-redirects -random-agent -json -o res.json

when i use flaq -cdn

```[FTL] Could not create httpx instance: could not create cdn check: Get "https://cdn.nuclei.sh": dial tcp: lookup cdn.nuclei.sh: Temporary failure in name resolution```

**Comment by jimen0** [comment]
```diff
diff --git a/common/httpx/httpx.go b/common/httpx/httpx.go
index b33c9a5..27bb645 100644
--- a/common/httpx/httpx.go
+++ b/common/httpx/httpx.go
@@ -16,6 +16,7 @@ import (
 	"github.com/microcosm-cc/bluemonday"
 	"github.com/projectdiscovery/cdncheck"
 	"github.com/projectdiscovery/fastdialer/fastdialer"
+	"github.com/projectdiscovery/gologger"
 	pdhttputil "github.com/projectdiscovery/httputil"
 	"github.com/projectdiscovery/rawhttp"
 	retryablehttp "github.com/projectdiscovery/retryablehttp-go"
@@ -142,7 +143,7 @@ func New(options *Options) (*HTTPX, error) {
 	if options.CdnCheck || options.ExcludeCdn {
 		httpx.cdn, err = cdncheck.NewWithCache()
 		if err != nil {
-			return nil, fmt.Errorf("could not create cdn check: %s", err)
+			gologger.Error().Msgf("could not create cdn check: %v", err)
 		}
 	}
 ```

If this works for you I'd be happy to contribute it, @Mzack9999 @ehsandeep

**Comment by ehsandeep** [comment]
@Ph33rr thank you for reporting this, this is a valid issue, and the client should not be stopped upon cdn endpoint failure for unknown reasons.

@jimen0 please go ahead with PR when possible, thank you.

**Comment by jimen0** [comment]
Done.

**Comment by ehsandeep** [comment]
@Ph33rr this is now fixed in the dev version with https://github.com/projectdiscovery/httpx/pull/602, could you also share your environment details where you reproduced this error as `cdn.nuclei.sh` should be accessible as the API is working very well, so possibly an issue with connecting Cloudflare host in a specific environment? VPN?

**Comment by Ph33rr** [comment]
@ehsandeep ubuntu 20 LTS  its cloud without VPN
