### ISSUE TITLE
CNAME not displayed with -ports flag

### ISSUE THREAD

**Issue by JoshuaMart** [projectdiscovery/httpx#604]
**HTTPX Version :** v1.2.1

Hi,
When the `-ports` option is used with `-cname` it is not displayed anymore

### Current Behavior:
```
root@5131dca14ebb: echo "www.dnsimple.com" | httpx -silent -cname
https://www.dnsimple.com [dnsimple.com]

root@5131dca14ebb: echo "www.dnsimple.com" | httpx -silent -cname -ports 80,443
http://www.dnsimple.com
https://www.dnsimple.com
```

### Expected Behavior:
That the cname is also displayed with the `-ports` option

### Steps To Reproduce:
```
echo "www.dnsimple.com" | httpx -silent -cname -ports 80,443
```

Regards

**Comment by jimen0** [comment]
The difference comes from the following snippet:

```diff
+	gologger.Info().Msgf("[-] About to get DNS data of domain=%s", domain)
	ips, cnames, err := getDNSData(hp, domain)
	if err != nil {
		ips = append(ips, ip)
	}
+	gologger.Info().Msgf("[-] IPs=%#+v, cnames=%#+v, err=%v", ips, cnames, err)
```

```console
$ echo "www.dnsimple.com" | httpx -cname -ports 80,443
[INF] [-] About to get DNS data of domain=https://www.dnsimple.com:443
[INF] [-] About to get DNS data of domain=https://www.dnsimple.com:80
[INF] [-] IPs=[]string{}, cnames=[]string(nil), err=<nil>
http://www.dnsimple.com
[INF] [-] IPs=[]string{}, cnames=[]string(nil), err=<nil>
https://www.dnsimple.com

...

$ echo "www.dnsimple.com" | httpx -cname              

[INF] [-] About to get DNS data of domain=www.dnsimple.com
[INF] [-] IPs=[]string{"104.245.210.170"}, cnames=[]string{"dnsimple.com"}, err=<nil>
https://www.dnsimple.com [dnsimple.com]
```

Following the code path, the difference seems to come from the fastdialer module and not from httpx itself. Followed it until the following call at fastdialer:

```go
func (d *Dialer) GetDNSData(hostname string) (*retryabledns.DNSData, error)
```

The results are:

```console
With no -ports flag:
[+] dnsData.A=[]string{"104.245.210.170"}, dnsData.AAAA=[]string(nil)`

vs

With -ports flag:
[+] dnsData.A=[]string(nil), dnsData.AAAA=[]string(nil)
```

Will try to find some time later today to dig deeper and contribute a patch for this.

**Comment by jimen0** [comment]
Hi @Mzack9999 @ehsandeep - based on the above, is fastdialer's `GetDNSData(hostname string)` expected to be able to work with strings such as `https://www.dnsimple.com:443` or should it always receive just DNS names such as `www.dnsimple.com`? Once you answer that, I can work on a patch and submit it.

Thanks!

**Comment by Mzack9999** [comment]
@jimen0 Unfortunately, I've seen your comment only now, and meanwhile, a solution was already worked at https://github.com/projectdiscovery/httpx/pull/625. Your suggestion is 100% correct and should be implemented shortly. Thanks for your help!
