### ISSUE TITLE
Host behind WAF deny connection with known User-Agent in Random UA list

### ISSUE THREAD

**Issue by Phoenix1112** [projectdiscovery/httpx#624]
hello. i am using last version. i have a target. but httpx can not find it 

command:

```
echo "app.iciparisxl.nl" | httpx -timeout 20
```

```    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.2.1

                projectdiscovery.io

Use with caution. You are responsible for your actions.
Developers assume no liability and are not responsible for any misuse or damage.
```

The website opens smoothly in the browser and there is no timeout problem. I tried using the -resolvers flag. I tried almost 10 times and got the correct result only 1 time, and even if I run the same command later, it didn't work.

```
cyberthereaper@LAPTOP-TSBG6N4F:~$ echo "app.iciparisxl.nl" | httpx -resolvers 8.8.8.8,8.8.4.4,1.1.1.1,1.0.0.1

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.2.1

                projectdiscovery.io

Use with caution. You are responsible for your actions.
Developers assume no liability and are not responsible for any misuse or damage.
http://app.iciparisxl.nl
```

```
cyberthereaper@LAPTOP-TSBG6N4F:~$ echo "app.iciparisxl.nl" | httpx -resolvers 8.8.8.8,8.8.4.4,1.1.1.1,1.0.0.1

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.2.1

                projectdiscovery.io

Use with caution. You are responsible for your actions.
Developers assume no liability and are not responsible for any misuse or damage.
cyberthereaper@LAPTOP-TSBG6N4F:~$ echo "app.iciparisxl.nl" | httpx -resolvers 8.8.8.8,8.8.4.4,1.1.1.1,1.0.0.1 -timeout 20

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.2.1

                projectdiscovery.io

Use with caution. You are responsible for your actions.
Developers assume no liability and are not responsible for any misuse or damage.
````

**Comment by jimen0** [comment]
This seems to depend on the `User-Agent` header selected by `httpx`, which is random by default.

```console
$ echo "app.iciparisxl.nl" | httpx -silent -random-agent=false -timeout 5 -status-code -H "user-agent: Mozilla/5.0 (X11; U; FreeBSD; i386; en-US; rv:1.7) Gecko"
https://app.iciparisxl.nl [404]
```

If you let `httpx` choose the UA for you, sometimes it will work but most of the times it will fail since it'll select a UA Akamai doesn't answer to.

FYI @ehsandeep @Mzack9999

**Comment by ehsandeep** [comment]
>  it'll select a UA Akamai doesn't answer to.

@jimen0 do you think we can filter out or use a limited set of random UA that are usable in the real world would solve this issue?

**Comment by jimen0** [comment]
Hi @ehsandeep - Well, as you can see in projectdiscovery/nuclei#655 I'm in favor of identifiable-by-default UAs to make detection job a little bit easier.

If you build a simple echo server and put it behind Akamai, then you could identify the blocked UAs from the ones httpx randomly chooses from and remove them from the list. Bonus: this would allow you to have an integration test and quickly identify whenever Akamai blocks a UA httpx uses 😉.

I guess what you propose could work but I don't support it 😅.

**Comment by Mzack9999** [comment]
It seems like this isn't a default Akamai behaviour but rather a specific [server setting](https://techdocs.akamai.com/property-mgr/reference/latest-useragent), probably a wildcard matcher like:
```
Mozilla/5.0 (?; FreeBSD;)
```
