### ISSUE TITLE
how to fix it

### ISSUE THREAD

**Issue by sasholy** [projectdiscovery/httpx#632]
echo "testphp.vulnweb.com" | httpx  
Usage: httpx [OPTIONS] URL
Error: Missing argument 'URL'.
-----------------------------------
echo "http://testphp.vulnweb.com/redir.php" | httpx -status-code -content-length -ip -cdn -title -tech-detect -random-agent
Usage: httpx [OPTIONS] URL
Error: no such option: -s
--------------------------------
echo "http://testphp.vulnweb.com" | httpx -title -status-code -tech-detect -follow-redirects
Usage: httpx [OPTIONS] URL
Error: no such option: -t

Kali Linux                                                 
go version go1.18.1 linux/amd64

thx.

**Comment by AaronChen0** [comment]
What you are using now is https://www.python-httpx.org, from another different project. Probably you install it via `apt install httpx` or `pip install httpx`. That's wrong way to get httpx.

You shall install httpx via `go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest`.

**Comment by ehsandeep** [comment]
@sasholy see https://github.com/projectdiscovery/httpx/discussions/516

**Comment by sasholy** [comment]
go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest

cat sub.txt | httpx
Usage: httpx [OPTIONS] URL

Error: Missing argument 'URL'.


httpx -list sub.txt -silent -probe
Usage: httpx [OPTIONS] URL

Error: No such option: -l

?

**Comment by sasholy** [comment]
ok, run only ./httpx

**Comment by Ayush765** [comment]
E: Unable to locate package httpx
i unable to delete it what should i do?

**Comment by 0xweb01** [comment]
@ehsandeep 
i have the same problem

$ cat domains | httpx | tee -a alive 

Usage: httpx [OPTIONS] URL

Error: Missing argument 'URL'.

**Comment by sullo** [comment]
> @ehsandeep i have the same problem
> 
> $ cat domains | httpx | tee -a alive
> 
> Usage: httpx [OPTIONS] URL
> 
> Error: Missing argument 'URL'.

When you execute "httpx" like that it will search your $PATH environment variable, and it is finding the python program first.

You should change your command to:
`cat domains | ./httpx | tee -a alive`

or the full path to httpx like:
`cat domains | /home/user/cmd/httpx/httpx | tee -a alive`

or, lastly, you could update your $PATH to put httpx's path before python's.

**Comment by tytyieq** [comment]
> > @ehsandeep i have the same problem
> > $ cat domains | httpx | tee -a alive
> > Usage: httpx [OPTIONS] URL
> > Error: Missing argument 'URL'.
> 
> When you execute "httpx" like that it will search your $PATH environment variable, and it is finding the python program first.
> 
> You should change your command to: `cat domains | ./httpx | tee -a alive`
> 
> or the full path to httpx like: `cat domains | /home/user/cmd/httpx/httpx | tee -a alive`
> 
> or, lastly, you could update your $PATH to put httpx's path before python's.

i try this all and doesnt work also..!!

**Comment by djabthDZ** [comment]
install httpx-toolkit vai this command : apt-get install httpx-toolkit 

Usage :

httpx-toolkit -h

cat subs.txt | httpx-toolkit --title --status-code 

just use the same command but instead httpx use httpx-toolkit and it will running correctly

**Comment by AliYar-Khan** [comment]
please change the package name to someother since it is conflicting with python package httpx

**Comment by zodmagus** [comment]
Finally figured out why httpx wasn't working properly. For some reason there's a package on Kali called python3-httpx that needs to be purged. Once you do that either install it via go or via pdtm and it works fine.

**Comment by sinarpagi** [comment]
try to install the latest httpx.
go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest

the go to your go path directory. 
eg. cd ~/home/go/bin

then copy httpx to directory /usr/bin (as root)

**Comment by mactoby** [comment]
> try to install the latest httpx. go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
> 
> the go to your go path directory. eg. cd ~/home/go/bin
> 
> then copy httpx to directory /usr/bin (as root)

Thanks! it works and fixed the error.

**Comment by Prabhjeet93** [comment]
I was also getting the same error and tried many things, but the sudo command (sudo httpx -h) fixed the issue.

**Comment by arunravi94** [comment]
[INF] Current httpx version v1.7.0 (latest)
[WRN] UI Dashboard is disabled, Use -dashboard option to enable
