### ISSUE TITLE
Dependency [h11<0.13.0] conflict while using alone with Hypercorn[h11==0.13.0]

### ISSUE THREAD

**Issue by noctoid** [projectdiscovery/httpx#636]
Hi, I just found out a issue while building an RPC framework which is run by Hypercorn which requires 0.13.0 that conflicts with the httpx's requirement which is h11<0.13.0.

Is there anyway to lift the constraint of h11 version number lower than 0.13.0? or there is a must situation that we indeed require such version?

On the other hand, humbly asking, is there a more simple way to fix this conflict issue?

**Comment by jimen0** [comment]
Hi @noctoid - Maybe you wanted to post this in https://github.com/encode/httpx instead?

**Comment by noctoid** [comment]
> Hi @noctoid - Maybe you wanted to post this in https://github.com/encode/httpx instead?

Good point
