### ISSUE TITLE
Force HTTPS with port 443

### ISSUE THREAD

**Issue by JoshuaMart** [projectdiscovery/httpx#648]
### httpx version: 1.2.1

Currently, when the port option is specified, HTTPX makes an HTTP/HTTPS request for each port.
Except that this is a problem with port 443, when trying with HTTPS, if the request is in timeout, it is a url with the HTTP scheme that will be returned, which is a bit of a false positive.

```
root@ycnskzdsssvg:/tmp# echo "domain.tld" | httpx -silent -sc -cl -location -title -td -ports 443 -timeout 60
http://domain.tld:443 [400] [] [15] [] [Apache]
```

While the target is reachable in HTTPS but takes time to respond :
```
root@ycnskzdsssvg: curl -I -k https://domain.tld
HTTP/1.1 503 Service Unavailable
```

I think that in the case of port 443 it would be mandatory to force HTTPS scheme and not to test the HTTP scheme on port 443

Regards

**Comment by ehsandeep** [comment]
@JoshuaMart @sullo this is already supported and mentioned in the notes section https://github.com/projectdiscovery/httpx#-notes

We can specify a scheme to use with ports to connect.

```
echo google.com | httpx -p https:443
```

**Comment by JoshuaMart** [comment]
Ah, I missed that part
Thanks, it seems to solve my problem :)

**Comment by sullo** [comment]
hmm... I did look around and didn't see it. I think that should be documented up with the help text on -ports. I'll tackle it to make it more clear.

**Comment by molitona** [comment]
> @JoshuaMart @sullo this is already supported and mentioned in the [notes section. ](https://github.com/projectdiscovery/httpx#-notes)
> 
> We can specify forced scheme to use with ports to connect:
> 
> ```
> echo google.com | httpx -p https:443
> ```

Hi, 
I got a lot of ```400 The plain HTTP request was sent to HTTPS port``` on domain:xxx entries in a file when scanning them.

All of them with http by httpx --> http://domain:xxx  

It seems logical that non 443 and 80 ports should be scanned with  both http and https scheme 'cause we dunno what's behind them. But, in my case only HTTP is used on non standard ports which caused the error.

-nf and -nfs doesn't solve anything
