### ISSUE TITLE
Choose user agent type

### ISSUE THREAD

**Issue by brenocss** [projectdiscovery/httpx#649]
### Please describe your feature request:

```zsh
echo hackerone.com | httpx -user-agents mobile,headless,desktop-new-versions
```
```zsh
echo hackerone.com | httpx -user-agents desktop-old-versions
```
### Describe the use case of this feature:

Use a random user agent, but in the chosen category. This feature should be added in nuclei too

**Comment by brenocss** [comment]
https://github.com/projectdiscovery/httpx/pull/1230

**Comment by ehsandeep** [comment]
https://github.com/projectdiscovery/httpx/pull/1230#issuecomment-1938868119
