### ISSUE TITLE
bash script hanging

### ISSUE THREAD

**Issue by Sy3Omda** [projectdiscovery/httpx#66]
Hi,

i`m running httpx against 310383 lines in vps server with 1 GB of ram and 1 vcpu .
BUT the bash script is hanging after while when it comes to run httpx against this file .
the question is dose this has something to do with linux (ubuntu 20.04) itself ?
because i am running htop and everything seems to be normal !

**Comment by bauthard** [comment]
Hey @Sy3Omda, 

Unless you can provide any context, we really can't help here, we had similar issue here https://github.com/projectdiscovery/httpx/issues/61 but we didn't manage to reproduce it, it works well as listed in the comment and it turned to be network issue at the user end. 

> the question is dose this has something to do with linux (ubuntu 20.04) itself?

No, httpx works cross-platform, so OS shouldn't be an issue.

**Comment by Sy3Omda** [comment]
this screenshot maybe could describe what i mean 
![2020-08-15 09_27_14-Window](https://user-images.githubusercontent.com/48482029/90307852-b3dc0880-deda-11ea-9cc8-0405f56bed9f.png)

**Comment by bauthard** [comment]
Thank you, we have one known case where it gets stuck, I will get back to this when we push fix for that and check again on this.

**Comment by bauthard** [comment]
Closing as duplicate https://github.com/projectdiscovery/httpx/issues/61, this will be fixed before the next release.

**Comment by baskarEITB** [comment]
#!/bin/sh

#######################################
# Bash script to install an AMP stack and PHPMyAdmin plus tweaks. For Debian based systems.

# In case of any errors (e.g. MySQL) just re-run the script. Nothing will be re-installed except for the packages with errors.
#######################################

#COLORS
# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan

# Update packages and Upgrade system
echo -e "$Cyan \n Updating System.. $Color_Off"
apt-get update -y && sudo apt-get upgrade -y

## Install AMP
echo -e "$Cyan \n Installing Apache2 $Color_Off"
apt-get install apache2 apache2-doc apache2-mpm-prefork apache2-utils libexpat1 ssl-cert -y

echo -e "$Cyan \n Installing PHP & Requirements $Color_Off"
apt-get install libapache2-mod-php php php-common php-curl php-dev php-gd php-idn php-pear php-imagick php-mcrypt php-mysql php-ps php-pspell php-recode php-xsl -y

echo -e "$Cyan \n Installing MySQL $Color_Off"
apt-get install mysql-server mysql-client libmysqlclient15.dev -y

echo -e "$Cyan \n Installing phpMyAdmin $Color_Off"
apt-get install phpmyadmin -y

echo -e "$Cyan \n Verifying installs$Color_Off"
apt-get install apache2 libapache2-mod-php php mysql-server php-pear php-mysql mysql-client mysql-server php-mysql php-gd -y

## TWEAKS and Settings
# Permissions
echo -e "$Cyan \n Permissions for /var/www $Color_Off"
chown -R www-data:www-data /var/www
echo -e "$Green \n Permissions have been set $Color_Off"

# Enabling Mod Rewrite, required for WordPress permalinks and .htaccess files
echo -e "$Cyan \n Enabling Modules $Color_Off"
a2enmod rewrite
phpenmod mcrypt

# Restart Apache
echo -e "$Cyan \n Restarting Apache $Color_Off"
service apache2 restart

**Comment by baskarEITB** [comment]
#!/bin/sh

#######################################
# Bash script to install an AMP stack and PHPMyAdmin plus tweaks. For Debian based systems.

# In case of any errors (e.g. MySQL) just re-run the script. Nothing will be re-installed except for the packages with errors.
#######################################

#COLORS
# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan

# Update packages and Upgrade system
echo -e "$Cyan \n Updating System.. $Color_Off"
apt-get update -y && sudo apt-get upgrade -y

## Install AMP
echo -e "$Cyan \n Installing Apache2 $Color_Off"
apt-get install apache2 apache2-doc apache2-mpm-prefork apache2-utils libexpat1 ssl-cert -y

echo -e "$Cyan \n Installing PHP & Requirements $Color_Off"
apt-get install libapache2-mod-php php php-common php-curl php-dev php-gd php-idn php-pear php-imagick php-mcrypt php-mysql php-ps php-pspell php-recode php-xsl -y

echo -e "$Cyan \n Installing MySQL $Color_Off"
apt-get install mysql-server mysql-client libmysqlclient15.dev -y

echo -e "$Cyan \n Installing phpMyAdmin $Color_Off"
apt-get install phpmyadmin -y

echo -e "$Cyan \n Verifying installs$Color_Off"
apt-get install apache2 libapache2-mod-php php mysql-server php-pear php-mysql mysql-client mysql-server php-mysql php-gd -y

## TWEAKS and Settings
# Permissions
echo -e "$Cyan \n Permissions for /var/www $Color_Off"
chown -R www-data:www-data /var/www
echo -e "$Green \n Permissions have been set $Color_Off"

# Enabling Mod Rewrite, required for WordPress permalinks and .htaccess files
echo -e "$Cyan \n Enabling Modules $Color_Off"
a2enmod rewrite
phpenmod mcrypt

# Restart Apache
echo -e "$Cyan \n Restarting Apache $Color_Off"
service apache2 restart

**Comment by baskarEITB** [comment]
#!/bin/sh

#######################################
# Bash script to install an AMP stack and PHPMyAdmin plus tweaks. For Debian based systems.

# In case of any errors (e.g. MySQL) just re-run the script. Nothing will be re-installed except for the packages with errors.
#######################################

#COLORS
# Reset
Color_Off='\033[0m'       # Text Reset

# Regular Colors
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan

# Update packages and Upgrade system
echo -e "$Cyan \n Updating System.. $Color_Off"
apt-get update -y && sudo apt-get upgrade -y

## Install AMP
echo -e "$Cyan \n Installing Apache2 $Color_Off"
apt-get install apache2 apache2-doc apache2-mpm-prefork apache2-utils libexpat1 ssl-cert -y

echo -e "$Cyan \n Installing PHP & Requirements $Color_Off"
apt-get install libapache2-mod-php php php-common php-curl php-dev php-gd php-idn php-pear php-imagick php-mcrypt php-mysql php-ps php-pspell php-recode php-xsl -y

echo -e "$Cyan \n Installing MySQL $Color_Off"
apt-get install mysql-server mysql-client libmysqlclient15.dev -y

echo -e "$Cyan \n Installing phpMyAdmin $Color_Off"
apt-get install phpmyadmin -y

echo -e "$Cyan \n Verifying installs$Color_Off"
apt-get install apache2 libapache2-mod-php php mysql-server php-pear php-mysql mysql-client mysql-server php-mysql php-gd -y

## TWEAKS and Settings
# Permissions
echo -e "$Cyan \n Permissions for /var/www $Color_Off"
chown -R www-data:www-data /var/www
echo -e "$Green \n Permissions have been set $Color_Off"

# Enabling Mod Rewrite, required for WordPress permalinks and .htaccess files
echo -e "$Cyan \n Enabling Modules $Color_Off"
a2enmod rewrite
phpenmod mcrypt

# Restart Apache
echo -e "$Cyan \n Restarting Apache $Color_Off"
service apache2 restart
