### ISSUE TITLE
timeout problem

### ISSUE THREAD

**Issue by sdsrrt** [projectdiscovery/httpx#664]
When i was try to install httpx its show me this.Can anyone give me a solution.
![Screenshot from 2022-06-05 21-39-24](https://user-images.githubusercontent.com/73928464/173420535-15982dad-da80-4e7f-89c9-d15c139f1455.png)

**Comment by jimen0** [comment]
Hi @sdsrrt - This is a DNS problem on your side. Note the `read udp: 192.168.16.105:39967->192.168.16.1:53: i/o timeout`. It seems your machine failed to resolve `proxy.golang.org`.

This isn't a bug on httpx or Go itself. @Mzack9999 @ehsandeep

**Comment by ehsandeep** [comment]
Closing as this is network issue on the system and not related to project code.
