### ISSUE TITLE
saving http responses for same host on multiple ports makes the previous response override

### ISSUE THREAD

**Issue by AdmiralGaust** [projectdiscovery/httpx#67]
If you scan http://example.com on multiple ports, let say 80,443,8443

The final response in example.com.txt will be that returned from port 8443. Previous responses from port 443 and 80 will be overwritten.

Morever, it also lacks the functionality to specify whether I want to run https or http on port 8443. May be this functionality can be adopted from httprobe by tomnomnom. The only thing with httprobe is it does not allow to save responses.

**Comment by bauthard** [comment]
@AdmiralGaust this is fixed in master code.
