### ISSUE TITLE
httpx not running 

### ISSUE THREAD

**Issue by m7mdd77** [projectdiscovery/httpx#679]
Hi 
when i run httpx its came 

Traceback (most recent call last):
  File "/usr/bin/httpx", line 33, in <module>
    sys.exit(load_entry_point('httpx==0.23.0', 'console_scripts', 'httpx')())
  File "/usr/bin/httpx", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration

i install last go version and last httpx version

**Comment by m7mdd77** [comment]
![image](https://user-images.githubusercontent.com/88084590/176997998-8fadd16d-ef19-40c6-b045-dfa80aea8bc9.png)

**Comment by ehsandeep** [comment]
@m7mdd77 you have other httpx installed and not from projectdiscovery, more details - https://github.com/projectdiscovery/httpx/discussions/516. Make sure to install the correct version of the project to use httpx.

**Comment by m7mdd77** [comment]
so how i delete this httpx project ?

**Comment by m7mdd77** [comment]
om thanks i solve

**Comment by ehsandeep** [comment]
@m7mdd77 `which httpx` this will display the current location of the installed project, make sure to delete the binary and install the httpx again.
