### ISSUE TITLE
Full URL is sent to DNS resolver

### ISSUE THREAD

**Issue by TheTechromancer** [projectdiscovery/httpx#695]
Hello,

Recently in our testing we have noticed that when provided URLs, httpx sometimes fails to resolve DNS hosts:

![image](https://user-images.githubusercontent.com/20261699/178801158-5b118014-f65d-4dd4-b963-6bf30704ba5e.png)

 Inspecting the traffic in wireshark reveals that httpx is passing the full URL to the DNS server:

![image](https://user-images.githubusercontent.com/20261699/178798663-70305929-9790-4b30-b6dd-06a57a426542.png)

**Comment by ehsandeep** [comment]
@TheTechromancer thanks a lot for pointing this out, we were already [investigating](https://github.com/projectdiscovery/retryablehttp-go/issues/22) something which might be related to this (not confirmed).

**Comment by Mzack9999** [comment]
@TheTechromancer Thanks for opening the issue. I can confirm that the five consecutive requests with the same request-id of type A and AAAA seem to match the retryabledns default settings. Anyway, a few things are unclear. For example, the full URL `https://www.example.com:80/index.html`, from the command screenshot you provided, was never piped into `httpx`. Also, the `AAAA` shows two times `OPT OPT`. Could you confirm if the provided command is the exact one associated with the Wireshark screenshot?

**Comment by TheTechromancer** [comment]
The target corresponding to the wireshark screenshot was `https://www.example.com/index.html`, as shown in the capture. These were two separate runs; I mixed them up. So the command that generated the wireshark screenshot was:

```
echo 'http://www.example.com/index.html' | httpx -debug -json -r <dns server>
```

Just now I went back to verify this, and strangely I am no longer seeing the URL in the capture. I'm unsure why this is, since I'm using the same binary as before (version 1.2.3), but the DNS requests still fail against the custom resolver.

![image](https://user-images.githubusercontent.com/20261699/179607398-e5a14213-e296-41bf-879a-bea833eabcdb.png)

**Comment by Mzack9999** [comment]
I suspect the problem might be between https://github.com/projectdiscovery/retryabledns and the custom resolver. Would it be possible to provide more information about it: DNS server software used? Any particular configuration?

**Comment by TheTechromancer** [comment]
Sure. It is an Active Directory domain controller running Windows Server 2012 R2 with the DNS server role and a default configuration. The forwarder (upstream DNS server) is set to 8.8.8.8.

**Comment by Mzack9999** [comment]
On Hold - Not reproducible, will need a custom setup similar to the described scenario.

**Comment by Mzack9999** [comment]
The issue can't be reproduced - It seems more related to the OS configuration than the go app itself. By default, we already use system resolvers in retryabledns.
