### ISSUE TITLE
Add output delimiter option (flag) for easy parsing

### ISSUE THREAD

**Issue by jayeshjodhawat** [projectdiscovery/httpx#7]
It would be helpful if we can specify delimiter for output columns (values).

For example:
* **Currently output looks like this**
```
$ ~ httpx -l urls.txt -title -content-length -status-code -silent
https://example.com [200] [724] [Example Home Page]
```

* **Improved output**
```
$ ~ httpx -l urls.txt -title -content-length -status-code -silent -delimiter ","
https://example.com,[200],[724],[Example Home Page]
```
**OR without square brackets**
```
$ ~ httpx -l urls.txt -title -content-length -status-code -silent -delimiter ","
https://example.com,200,724,Example Home Page
```

This will help parsing output with commands like `cut`, `awk`, `sed`, etc.

**Comment by bauthard** [comment]
This can be done with `json` output, but surely this will be also useful with regular output, thanks for creating an issue for this.

**Comment by Ice3man543** [comment]
Closing this as this can already be accomplished via json flag. If there seems a need, we can reopen this in the future!
