### ISSUE TITLE
Improvement suggestion: flag to print redirection path

### ISSUE THREAD

**Issue by geraldino2** [projectdiscovery/httpx#70]
Currently, there are flags to tell httpx to follow redirections (-follow-redirects, -follow-host-redirects). However, it would be useful sometimes to don't follow the redirection, but to only print the redirection URI.

**Comment by bauthard** [comment]
Hey, this is already added in the [master code](https://github.com/projectdiscovery/httpx/pull/64), pull the master code and use `-location` header to print location header.
