### ISSUE TITLE
Ports Flag is not working with scheme

### ISSUE THREAD

**Issue by amirnsahmad** [projectdiscovery/httpx#704]
### httpx version: 
1.2.3

### Current Behavior:
 When the ports flag is used within scheme (-p https:443) it is breaking.

### Expected Behavior: 
It should probe https on port 443.

### Steps To Reproduce:

1. Run 'echo example.com | httpx -ports https:443'

### Anything else:
Response:
'[FTL] Could not cast port to integer from your value: https:443. Resulting error: strconv.Atoi: parsing "https:443": invalid syntax.'

**Comment by jimen0** [comment]
This isn't a bug. That's now how the `-ports` flag works. Per the docs:

```text
-p, -ports string[]  ports to probe (nmap syntax: eg 1,2-10,11)
```

**Comment by ehsandeep** [comment]
It looks like a bug introduced with [recent](https://github.com/projectdiscovery/httpx/pull/677) changes @jimen0, as custom scheme input is not valid anymore.

```console
echo example.com | ./httpx -ports https:443

    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.2.3

		projectdiscovery.io

Use with caution. You are responsible for your actions.
Developers assume no liability and are not responsible for any misuse or damage.
[FTL] Could not cast port to integer from your value: https:443. Resulting error: strconv.Atoi: parsing "https:443": invalid syntax.
```

**Comment by jimen0** [comment]
Then the docs should be updated too, `-ports` flag help message doesn't indicate that format is supported. @ehsandeep
