### ISSUE TITLE
Could not cast port to integer

### ISSUE THREAD

**Issue by JoshuaMart** [projectdiscovery/httpx#712]
### Current Behavior:
With the 1.2.3 update it is no longer possible to use the `https:443` syntax in the `-port` parameter

```
root@scw-amsnetukjzso:~# echo "example.com" | httpx -ports https:443
[FTL] Could not cast port to integer from your value: https:443. Resulting error: strconv.Atoi: parsing "https:443": invalid syntax.
```

### Expected Behavior:
Same as httpx v1.2.2
```
root@scw-amsnetukjzso:~# echo "example.com" | httpx -ports https:443
https://example.com
```

### Steps To Reproduce:
```
echo "example.com" | httpx -ports https:443
```

I think PR #677 is the cause of this error

**Comment by ehsandeep** [comment]
@JoshuaMart see https://github.com/projectdiscovery/httpx/issues/704, will be fixed soon.
