### ISSUE TITLE
Add httprobe like prefer-https option to avoid duplicacy

### ISSUE THREAD

**Issue by AdmiralGaust** [projectdiscovery/httpx#72]
If a server is listening on both 80 and 443 ports and the response is identical, there should be an option to avoid saving http://target.com in output file. httprobe from tomnomnom has the cool feature. You may check it out for better understanding of what I am saying.

**Comment by bauthard** [comment]
Hey, this is enabled as default with httpx, do you have any example to share?

**Comment by AdmiralGaust** [comment]
```
echo google.com|httpx -follow-redirects -o urls.txt -ports 80,443
cat urls.txt 

http://google.com:80
https://google.com:443
```
In most cases, either both responses are identical or port 80 redirects to https port 443. In such cases, I want only https port to be saved to the output file.

**Comment by bauthard** [comment]
Hey @AdmiralGaust, 

Thank you for sharing this example, as you asked to probe different ports (80,443), merging results of multiple ports into one is not the ideal action to have, as technically they are different host `host:port`. 

If you looking to probe `google.com` you can do `echo google.com | httpx`, but you are specifically want to probe two different ports, it means you are interested in the result of each port, hence two results.

**Comment by bauthard** [comment]
@AdmiralGaust Closing this out as requested feature is already enabled as default, do let me know if you have additional questions.

**Comment by AdmiralGaust** [comment]
Yes I agree I am interested in output of both the ports, but only if http is not redirecting to https. Output of httpx can be used for various purposes like directory brute-forcing. It will be a waste of resources if I do directory scan on both the ports when I know http will do nothing else but just redirect to https.

I believe the default functionality should be to write both the ports in output file, but there should be a flag to prefer https responses for those hosts which have port 80 opened only for redirection to port 443.

**Comment by bauthard** [comment]
Hey @AdmiralGaust, 

I'm not sure why you want to probe 443 and 80 separately, even it's handled already in an automated way, `echo google.com | httpx` will probe for 443, if works, it will display `https://google.com`, it it fails, it will try 80 and display `http://google.com` if works. 

we can not change port probing behavior when the custom port is used as it will also affect the behavior of **non** `80, 443` ports if used.

**Comment by AdmiralGaust** [comment]
It's not about port 80 and 443. When targeting in mass, I usually use 80,443,8080,8000 and 8443.

I want it to return a list which fits to my automated framework. It does take this list and extracts javascript, fingerprints the target, launch dirsearch against all urls and lot. Having extra http urls will slow down my scan and utilize unwanted resources. That is why I wanted it to have such feature. I was previously using httprobe which does provide this feature but again it lacks the option to save html responses. So, I switched to httpx.

**Comment by bauthard** [comment]
appreciate the added information, feel free to jump in https://discord.gg/KECAGdH to continue this conversation, if something is missing and useful for the pipeline we can work on it.

**Comment by its0x08** [comment]
Hello,
the prefer-https option doesnt seem useful to 

> Hey @AdmiralGaust,
> 
> I'm not sure why you want to probe 443 and 80 separately, even it's handled already in an automated way, `echo google.com | httpx` will probe for 443, if works, it will display `https://google.com`, it it fails, it will try 80 and display `http://google.com` if works.
> 
> we can not change port probing behavior when the custom port is used as it will also affect the behavior of **non** `80, 443` ports if used.

Because in modern dockerized and kuberneted web most of my targets run different things in every port therefore they should be scanned separatedly in my opinion.

**Comment by bauthard** [comment]
@its0x08 @AdmiralGaust I've created an issue for this at https://github.com/projectdiscovery/httpx/issues/128
