### ISSUE TITLE
Extend the scope matchers and extractors to include response headers

### ISSUE THREAD

**Issue by fail-open** [projectdiscovery/httpx#725]
### Please describe your feature request:
Currently, matchers/extractors are limited to a response body that can be extended to include response headers as well.

### Describe the use case of this feature:
In an effort to extract authentication methods in bulk, I frequently collect headers and parse out the www-authenticate header. It would be great if this extracted type (basic, digest Bearer) and any additional info (realm etc).

**Comment by forgedhallpass** [comment]
Currently extractors only work on the response body. We could easily extend this to also consider the response headers (or even the same for requests).

Other options:
* add a dedicated flag that would control the scope for matchers and extractors
* create separate flags for request headers, request body and response headers

This request should potentially affect or would require extension of the following flags:
- `-match-string`
- `-match-regex`
- `-extract-regex`
- `-extract-preset`

**Comment by forgedhallpass** [comment]
The linked PR might not handle all the cases mentioned in this ticket.
