### ISSUE TITLE
Add ResultCallback in runner.Options

### ISSUE THREAD

**Issue by lucy9x** [projectdiscovery/httpx#729]
### Describe the use case of this feature:
This is very useful when integrating nuclei with other tools to get results

For example:

```go
type Options struct {
	//other options
    .........
    ResultCallback func(result Result)
}
```

When an HTTP result is discovered, this option will be called in analyzer function https://github.com/projectdiscovery/httpx/blob/f2cd5b835348c5563c4c018dc2ed414d82ccf249/runner/runner.go#L1494

```go
result := Result{
     ......
}
if (r.options.ResultCallback != nil) {
       r.options.ResultCallback(result)
}
```

**Comment by Mzack9999** [comment]
On Hold - Depends on https://github.com/projectdiscovery/nuclei/issues/2253

**Comment by Mzack9999** [comment]
Already implemented in https://github.com/projectdiscovery/httpx/pull/825
