### ISSUE TITLE
Add option to specify custom http scheme for ports

### ISSUE THREAD

**Issue by AdmiralGaust** [projectdiscovery/httpx#73]
For ports like 8443, http gives 400 Bad request. It could be very nice if we can specify which port needs to be https. For eg:

Something like 
-http 80 -https 8443 -https 443 -http 8080

**Comment by AdmiralGaust** [comment]
or something like

-ports http:80,https:443,https:8443

**Comment by bauthard** [comment]
Hey @AdmiralGaust, everything already there, you can specify multiple ports with `-ports` flag, example:- 

```
httpx -ports 8443, 6443, 9443
```

and as mentioned in https://github.com/projectdiscovery/httpx/issues/72, you don't need to worry about scheme, as `httpx` automatically checks of `https` and fallback to `http` if `https` is not working.
