### ISSUE TITLE
csv file not utf8 with bom

### ISSUE THREAD

**Issue by HyWell** [projectdiscovery/httpx#733]
### httpx version: 

v1.2.4
<img width="649" alt="image" src="https://user-images.githubusercontent.com/21263451/186158240-89af5f70-a9aa-4337-a497-4ecb8f1531b9.png">
### Current Behavior:

csv file not utf8 with Bom
### Expected Behavior:

Add utf8 with bom at the beginning of the csv file
### Steps To Reproduce:

1.Run 'echo baidu.com | httpx -path /index.html -o result.csv -csv'
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/21263451/186159223-5628951b-bf07-4ab8-98a6-0b94e1604016.png">

2. open excel
<img width="1457" alt="image" src="https://user-images.githubusercontent.com/21263451/186159385-b9d94073-8e1d-48dc-8490-31b68302fcfc.png">
3. add utf8 with bom at the beginning of the csv file
<img width="665" alt="image" src="https://user-images.githubusercontent.com/21263451/186161146-28d2519d-668d-4a53-9f87-64368a6db53d.png">
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/21263451/186161209-cab997f0-15eb-4bdb-9a18-4ddf0cb9d3cd.png">
use '\ufefft' to file

**Comment by ehsandeep** [comment]
@HyWell this is now fixed in dev version - https://github.com/projectdiscovery/httpx/pull/887#pullrequestreview-1196958287
