### ISSUE TITLE
ConnectError: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by Thekid1000** [projectdiscovery/httpx#734]
When i try to send a req this happens. 
![image](https://user-images.githubusercontent.com/75209374/186175998-1127449c-8397-4ce5-8162-7d6f0f35b6f9.png)
Idk why this happens this is new..😐🤨🤨

**Comment by jimen0** [comment]
The above error comes from a different _httpx_ project: https://github.com/encode/httpx/blob/14a1704be507cf435fa84da75c249c2ecd1c3981/httpx/_exceptions.py#L155

Not sure if you created the issue on the wrong repository or you installed the wrong tool.

cc @ehsandeep - this is a false positive bug.

**Comment by ehsandeep** [comment]
@Thekid1000 looks like you wanted to create an issue for [https://github.com/encode/httpx](https://github.com/encode/httpx/blob/14a1704be507cf435fa84da75c249c2ecd1c3981/httpx/_exceptions.py#L155)
