### ISSUE TITLE
[feature] Adding flag to probe HTTP verbs

### ISSUE THREAD

**Issue by 0ktavandi** [projectdiscovery/httpx#76]
so the expected behavior is like this, i give the HTTPX the list of urls
and then HTTPX fetches all given url with all available HTTP METHOD request [refer to this](https://developer.mozilla.org/id/docs/Web/HTTP/Methods)

expected raw output :
```
linux$: cat givenurl | httpx <multiplemethodoptionargs>
[GET] https://crotcrot.com/aduhcrot
[POST] https://crotcrot.com/aduhcrot
[PUT] https://crotcrot.com/aduhcrot
[etc] .. . . . .
```

**Comment by bauthard** [comment]
Hey, thank you for creating an issue here to discuss more in detail, so If I get it right, you want to see all available HTTP methods supported, on the given list of URLs? @0ktavandi

**Comment by bauthard** [comment]
```
> echo test.com | httpx -verb -silent 

https://test.com [GET, POST, OPTIONS]
```

**Comment by 0ktavandi** [comment]
hmm @bauthard seems the flag is 2 : 
1. i want to see what available HTTP method support on the given url.
2. i want to fuzzing the given url with ALL HTTP METHOD REQUEST.

**Comment by bauthard** [comment]
Hey, for the 2nd nuclei suites more in terms of usability.
