### ISSUE TITLE
httpx --count feature

### ISSUE THREAD

**Issue by MadalinNitu** [projectdiscovery/httpx#793]
Hello, 

I would like to see this feature implemented in this tool. I use as a sysadmin every day to check websites and server applications. I would like to use some parameter like --count 100 and combine with --delay 1 to send 1 request with a timeout of 1 sec between requests to monitor the status of a webserver live as I debug the problem. I do this with watch -n 1 https ... but I got for each call the EULA and I this this would be a nice feature. :D

**Comment by fail-open** [comment]
If by Eula you mean the banner when it runs, use -silent and you will only get your response. Should get what you are after at that point no?

**Comment by MadalinNitu** [comment]
yep ... thats .. many thanks
