### ISSUE TITLE
Include all the JSON output keys

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/httpx#797]
Follow-up ticket for - https://github.com/projectdiscovery/httpx/issues/750

### httpx version:
dev

### Current Behavior:
`title` and many other keys are missing

### Expected Behavior:
- All the keys should accessible to list and match
- Add automatic mechanism to infer the list

**Comment by thapr0digy** [comment]
Does this include having all keys accessible within the output when using -json? I'm noticing when using -cdn and probably others that the key will be missing in the output which makes it hard for parsing.
