### ISSUE TITLE
[addition] Contribution guidelines

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [projectdiscovery/httpx#807]
### Related to 
Issue #806 

### Please describe your feature request:

Contributing Guidelines (CONTRIBUTING.md) is not involved in the repo.

### Describe the use case of this feature:

Our repo is open for contributors as it has issue templates, pull request templates, and moreover `hacktoberfest` label in the topics. I started searching for contribution guidelines but I was unable to find it. Also [THANKS.md](https://github.com/projectdiscovery/httpx/blob/master/THANKS.md) looks broken link.

Please fix it.

**Comment by ehsandeep** [comment]
Added here - https://github.com/projectdiscovery/.github/blob/main/CONTRIBUTING.md
