### ISSUE TITLE
Using httpx as library

### ISSUE THREAD

**Issue by lucy9x** [projectdiscovery/httpx#824]
it seems that httpx is not currently usable as a library

For example: Naabu or nuclei allow using as library:  https://github.com/projectdiscovery/naabu/issues/432

How to use httpx as library? 
If httpx doesn't support using as library yet, please add Resultcallback on options so that it can be used as library.

**Comment by ehsandeep** [comment]
@lucy9x https://github.com/projectdiscovery/httpx#using-httpx-as-a-library

**Comment by lucy9x** [comment]
> @lucy9x https://github.com/projectdiscovery/httpx#using-httpx-as-a-library

how to get realtime results. httpx has no option resultcallback like naabu
