### ISSUE TITLE
Go 1.18 + Some missing tests

### ISSUE THREAD

**Issue by Mzack9999** [projectdiscovery/httpx#826]
### Please describe your feature request:
- [x] Bump to go 1.18
- [x] Implement/update tests covering using httpx as a library (ref: `OnResult` https://github.com/projectdiscovery/httpx/pull/825)

Notes: this is a follow up ticket of https://github.com/projectdiscovery/httpx/issues/824

**Comment by Mzack9999** [comment]
Assigned to @foxcores

**Comment by foxcores** [comment]
I'd like to take this ticket
