### ISSUE TITLE
[issue] method flag is enabled on default 

### ISSUE THREAD

**Issue by shivammusic** [projectdiscovery/httpx#83]
**Describe the bug**
My command was  -

subfinder -d newrelic.com -silent | httpx -silent | nuclei -t /root/nuclei-templates/cves/ -o /root/Desktop/Newrelic/ResultsN/cvelikeharsh.txt -v

and i am getting o/p as -

[WRN] Could not execute step: could not build http request: parse "https://supporttest.service.newrelic.com [\x1b[35mGET\x1b[0m]": net/url: invalid control character in URL
[WRN] Could not execute step: could not build http request: parse "https://supporttest.service.newrelic.com [\x1b[35mGET\x1b[0m]": net/url: invalid control character in URL
[WRN] Could not execute step: could not build http request: parse "https://supporttest.service.newrelic.com 
so on.....
[INF] No results found. Happy hacking!

**Nuclei version**
Version is 2.1.0

**Comment by bauthard** [comment]
@shivammusic updating to [v1.0.1]( https://github.com/projectdiscovery/httpx/releases/tag/v1.0.1) will fix this issue.
