### ISSUE TITLE
Adapt prefer-https behavior with port input option 

### ISSUE THREAD

**Issue by p0mbe** [projectdiscovery/httpx#872]
### Please describe your feature request:

Can the developers add the flag -prefer-https??

### Describe the use case of this feature:

E.g. after specifying ports like http:80,8080 and https:443,4443,8443

Seeing both port 80 and port 443 on the same host is a bit tiring

**Comment by Mzack9999** [comment]
@p0mbe `httpx` currently cannot determine if the same service is exposed on different ports. If other ports are specified, a connection is attempted on all of them, first trying https, then http if no scheme options are selected.
Suppose the repetition is only limited to ports 443 and 80. In that case, you could try to provide the fqdn/IP as input without specifying any port option, httpx will attempt automatically to connect to port 443 on https, then on port 80 with http, and only the first responsive one will be reported.
