### ISSUE TITLE
Issue with probing urls with asterisk (`*`)

### ISSUE THREAD

**Issue by Phoenix1112** [projectdiscovery/httpx#878]
If there is an asterisk```*``` in a url address, httpx does not send a request to the url address.

```
echo "https://example.com/?blabla=666*666" | httpx
```

```
    __    __  __       _  __
   / /_  / /_/ /_____ | |/ /
  / __ \/ __/ __/ __ \|   /
 / / / / /_/ /_/ /_/ /   |
/_/ /_/\__/\__/ .___/_/|_|
             /_/              v1.2.5

                projectdiscovery.io

Use with caution. You are responsible for your actions.
Developers assume no liability and are not responsible for any misuse or damage.
```

**Comment by jimen0** [comment]
Hi @ehsandeep - There's an explicit rule for detecting and replacing the `*` symbol here: https://github.com/projectdiscovery/httpx/blob/e64587292ec60a7e77583038ea5c762465cd827b/runner/runner.go#LL962-L977C41

```go
// returns all the targets within a cidr range or the single target
func (r *Runner) targets(hp *httpx.HTTPX, target string) chan httpx.Target {
	results := make(chan httpx.Target)
	go func() {
		defer close(results)
		switch {
		case strings.ContainsAny(target, "*") || strings.HasPrefix(target, "."):
			// A valid target does not contain:
			// *
			// spaces
			// trim * and/or . (prefix) from the target to return the domain instead of wilcard
			target = strings.TrimPrefix(strings.Trim(target, "*"), ".")
			if !r.testAndSet(target) {
				return
			}
			results <- httpx.Target{Host: target}
```

The `testAndSet` call returns `false` and therefore the target is ignored.

https://github.com/projectdiscovery/httpx/blob/e64587292ec60a7e77583038ea5c762465cd827b/runner/runner.go#LL405C7-L405C11

I'm not that used to this part of the codebase, but that's where the tool decides to ignore targets with `*`.

**Comment by ehsandeep** [comment]
Feature wise, It should be tls-probe option where it removes the * from dns names obtained from SSL certificate before probing.

**Comment by ehsandeep** [comment]
@Phoenix1112 this is now fixed in dev with - https://github.com/projectdiscovery/httpx/pull/911
