### ISSUE TITLE
-fcdn can't save bug

### ISSUE THREAD

**Issue by AM8bit** [projectdiscovery/httpx#912]
### httpx version:

v1.2.5

### Current Behavior:

cat urls.txt | httpx -silent -fcdn -o urls.out

The result file(urls.out) was not written

### Expected Behavior:
It should be filtered for the CDN host to save to the result file

### Steps To Reproduce:
install v1.2.5
cat urls.txt | httpx -silent -fcdn -o urls.out

### Anything else:

cat urls.txt | httpx -silent -fcdn -p 80-89,8080,81,8089,8069,7001,8000 -o urls.out

**Comment by ehsandeep** [comment]
@AM8bit, you need to specify the cdn names to filter, for example - `cat urls.txt | httpx -silent -fcdn cloudflare,azure`

```console
httpx -h fcdn

Flags:
   -fcdn, -filter-cdn string[]  filter host with specified cdn provider (azure, cloudflare, cloudfront, fastly, incapsula, oracle, google, akamai, sucuri, leaseweb)
```
