### ISSUE TITLE
multiple matchers?

### ISSUE THREAD

**Issue by 0xspade** [projectdiscovery/httpx#936]
Is it possible to put a multiple matchers for example:

`httpx -mr '<some-regex>' -ms '<some-string>' -mr '<some-regex-again>' -ms 'some-string-again'`

is this possible? haven't tried this yet but better to ask first :)

**Comment by ehsandeep** [comment]
it works!

```
echo hackerone.com | httpx -title -fr -ms hackerone -ms and -ms program
```
