### ISSUE TITLE
Public Go Api?

### ISSUE THREAD

**Issue by x72hoor** [projectdiscovery/httpx#94]
I mean, accessing httpx from another Go project/code (without os exec)?

You may want to EXPORT methods, in stead of making those PRIVATE?

Sorry for bad english.

Thanks

**Comment by Mzack9999** [comment]
@x72hoor The core is already packaged as module, you can import it an use in your code. Have a look at the `main` function about how to initialize it https://github.com/projectdiscovery/httpx/blob/d26783f5c2dc50aa17ea4c91e301977a1d5e0311/cmd/httpx/httpx.go#L59

**Comment by bauthard** [comment]
Closing as this has been answered, we will document this information better in future.
