### ISSUE TITLE
Custom header input with Host does not work

### ISSUE THREAD

**Issue by marcopolo157** [projectdiscovery/httpx#95]
The httpx wont send HTTP request if the flag `-H` is included with `Host: something` custom header.

```
echo "https://postb.in/1599380591722-3710830304771" | httpx -H "Host: test"
```

**Comment by bauthard** [comment]
@marcopolo157 you need to use `-unsafe` flag for the custom host header.

**Comment by marcopolo157** [comment]
@bauthard thanks!

**Comment by bauthard** [comment]
@marcopolo157 please close the issue once you confirmed.

**Comment by marcopolo157** [comment]
Hmm, it still does not work, i'm getting only DNS request

```
echo "https://8fogpq9e1duul88p3qcwemd5rwxtli.burpcollaborator.net" | httpx -unsafe -H 'Host: test'

```

![Screenshot from 2020-09-06 10-36-11](https://user-images.githubusercontent.com/68386571/92321766-e639db00-f02c-11ea-8216-96d47d93e3cf.png)

**Comment by bauthard** [comment]
@marcopolo157 try with `ncat` or your server to verify this, burp collaborator has something in place to not allow this.

**Comment by marcopolo157** [comment]
It does work, thanks!
