### ISSUE TITLE
Extend GoLang 1.18 support

### ISSUE THREAD

**Issue by Paradoxis** [projectdiscovery/httpx#950]
After updating my system, it appears I can no longer install `httpx` due to the fact that GoLang 1.19 is required, however a lot of other tools on my system still require GoLang 1.18 as they aren't up to date with go 1.19+ yet. The following is a trace whilst installing the tool:

```
$ go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
github.com/projectdiscovery/httpx/runner
# github.com/projectdiscovery/httpx/runner
/home/kali/go/pkg/mod/github.com/projectdiscovery/httpx@v1.2.6/runner/runner.go:1705:21: req.URL.JoinPath undefined (type *url.URL has no field or method JoinPath)
note: module requires Go 1.19
```

Would it be possible to extend the support for 1.18 a little longer? Given that it's less than a year old it would really be appreciated, if possible.

**Comment by ehsandeep** [comment]
@Paradoxis, httpx utilizing features introduced in go 1.19, so unfortunately, that won't be possible, alternatively, you can install httpx or any other pd projects by downloading binary itself or use - https://github.com/projectdiscovery/pdtm
