### ISSUE TITLE
Feature request: string/regex search in response bodies

### ISSUE THREAD

**Issue by xEHLE** [projectdiscovery/httpx#97]
It would be nice to have a feature that lets us specify either a string or regex pattern to search for in the response bodies and print if it found something to the output.
Example:
httpx -l domains -contains "admin"
http://example.com [true]
http://example2.com [false]

httpx -l domains -contains "\".*jquery\.js"
http://example.com [true]
http://example2.com [false]

**Comment by vay3t** [comment]
I think that the objective of the project is not that, also you can use curl and parallel with grep

**Comment by bauthard** [comment]
Hi @xEHLE, 

We ended up adding a matcher/filter for the response body (header+body) to align with other matcher/filters we have for status and length. 

```sh
echo hackerone.com | ./httpx -silent -match-string hackerone
https://hackerone.com
```

```sh
echo hackerone.com | ./httpx -silent -filter-string hackerone
```
