### ISSUE TITLE
install / compilation error with cockroachdb/pebble

### ISSUE THREAD

**Issue by anoduck** [projectdiscovery/httpx#988]
### Current Behavior:

During execution of `go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest` the install failed on the required dependency pebble. It ejected the following set of errors:

```
# github.com/cockroachdb/pebble/vfs
/go/bin/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230207164304-7d1e4ba7ffd0/vfs/disk_usage_unix.go:18:27: stat.Bsize undefined (type unix.Statfs_t has no field or method Bsize)
/go/bin/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230207164304-7d1e4ba7ffd0/vfs/disk_usage_unix.go:18:48: stat.Bfree undefined (type unix.Statfs_t has no field or method Bfree)
/go/bin/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230207164304-7d1e4ba7ffd0/vfs/disk_usage_unix.go:19:28: stat.Bsize undefined (type unix.Statfs_t has no field or method Bsize)
/go/bin/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230207164304-7d1e4ba7ffd0/vfs/disk_usage_unix.go:19:49: stat.Bavail undefined (type unix.Statfs_t has no field or method Bavail)
/go/bin/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230207164304-7d1e4ba7ffd0/vfs/disk_usage_unix.go:20:28: stat.Bsize undefined (type unix.Statfs_t has no field or method Bsize)
/go/bin/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230207164304-7d1e4ba7ffd0/vfs/disk_usage_unix.go:20:49: stat.Blocks undefined (type unix.Statfs_t has no field or method Blocks)
```

System: OpenBSD Current 7.2
Go Version: go1.19.4 openbsd/amd64

An issue has been created and opened in the pebble repository for this as well. https://github.com/cockroachdb/pebble/issues/2341

### Expected Behavior:

Expected a clean install without any hiccups. 

### Steps To Reproduce:

1. Create a bootable OpenBSD installation. (can be done on vm if needed)  https://www.openbsd.org/faq/faq4.html 
2. Install go as root user `pkg_add -U go`
3. Install Bash to avoid using ksh `pkg_add -U bash bash-completion``
4. Setup GOPATH `echo 'export GOPATH="$HOME/go"' >> ~/.bashrc`
5. Setup GOBIN `echo 'export GOBIN="$GOPATH/bin"' >> ~/.bashrc`
6. `source ~/.bashrc`
7. Attempt install `go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest`

### Anything else:

Not at this moment.

**Comment by Mzack9999** [comment]
@anoduck Thanks for reporting this - I removed support for pebble in hmap as also, in the past, it introduced compilation errors for arm and 386 architectures.

**Comment by anoduck** [comment]
@Mzack9999 Awesome! When should I look for the changes to be reflected in the repository?

**Comment by Mzack9999** [comment]
@anoduck as soon as `hmap` new version is released (ca 1 week) the change will be available in the `dev` branch
