### ISSUE TITLE
Problem requesting an http server

### ISSUE THREAD

**Issue by AlessandroZ** [projectdiscovery/httpx#99]
Hi, 

I don't know if something changed recently because it's the first time I see this problem. When I do a request on a http service, on my proxy I see 2 requests send, the first one is using https, and the second one http.

Server on my laptop
```
python -m SimpleHTTPServer
Serving HTTP on 0.0.0.0 port 8000 ...
```
 Trying using this command
```
 echo "http://127.0.0.1:8000/aaaaa" | httpx -title -silent -http-proxy http://127.0.0.1:8080
```

On burp I saw 2 requests to /aaaaaa. 

Thanks for your work. Have a nice day.

**Comment by bauthard** [comment]
Hey @AlessandroZ, 

This is the default behavior and feature of `httpx`, it checks for `https` first, if not working, fallback to `http`. 

> Smart auto fallback from HTTPS to HTTP as default.

**Comment by bauthard** [comment]
@AlessandroZ `-ports 80`

**Comment by AlessandroZ** [comment]
Cool, thanks your help :+1: . Have a nice day.
