### ISSUE TITLE
support multies filter strings 

### ISSUE THREAD

**Issue by passwa11** [projectdiscovery/httpx#997]
### httpx version:

1.2.7
### Current Behavior:

i want to filter multies strings from many targets response ,when i use `-fs '<html' -fs 'xss' ` only last -fs xss is work well
### Expected Behavior:

-fs support multies keywords like -fc 403,401 etc...

**Comment by ehsandeep** [comment]
@passwa11 this can be done using dsl based matcher/filter option

```
httpx -h | grep condition
   -mdc, -match-condition string      match response with dsl expression condition
   -fdc, -filter-condition string      filter response with dsl expression condition
```

For example - 

```
echo example.com | httpx -mdc "contains(body, 'yy' && contains(body, 'xx')"
```

There is a known bug with this option, and being tracked at https://github.com/projectdiscovery/httpx/issues/1019
